### PR TITLE
Nested lists addendum

### PR DESCRIPTION
**Pull request by wmertens**
some improvements to ListField, and fixes for uploading files

### CODE REVIEW

**Comment by mxstbr** [comment]
Uhhh something went wrong here

**Comment by wmertens** [comment]
better :)

**Comment by wmertens** [comment]
Oops committed the old code with `_id`. Fixed.

**Comment by wmertens** [comment]
@JedWatson without these changes you can't put files in the List

**Comment by JedWatson** [comment]
Looks great @wmertens, thanks and sorry it took me so long to review!

**Pull request merged**
