### PR TITLE
Log mongoose validation errors generated during createItems

### PR DESCRIPTION
**Pull request by webteckie**
Addresses #868 

Without the changes and if there is a mongoose validation error I get the following:

    ------------------------------------------------
    An error occurred applying updates, bailing on Keystone init.

    Error details:

With the changes and if there is a mongoose validation error I get something like the following, which is a huge help in troubleshooting:

    { [ValidationError: Validation failed]
      message: 'Validation failed',
      name: 'ValidationError',
      errors:
       { startTime:
          { [ValidatorError: Path `startTime` is required.]
            message: 'Path `startTime` is required.',
            name: 'ValidatorError',
            path: 'startTime',
            type: 'required',
            value: undefined } },
      model: 'Event',
      data:
       { name: 'Test Booking 1',
         status: 'pending',
         endTime:
          { _isAMomentObject: true,
            _isUTC: false,
            _pf: [Object],
            _locale: [Object],
            _d: Tue Jan 06 2015 19:09:37 GMT-0500 (Eastern Standard Time) },
         __ref: 'Event_1',
         __doc:
          { endTime: Tue Jan 06 2015 19:09:37 GMT-0500 (Eastern Standard Time),
            name: 'Test Booking 1',
            type: 'none',
            repeat: 'none',
            status: 'pending',
            guests: [],
            allDay: false,
            listName: 'Event',
            _id: 54ac7943a2751ad02b12ed57 } } }

### CODE REVIEW

**Comment by webteckie** [comment]
Give me a few...the "(_dashes_ + '\nUpdate ' + file + ' failed with error:\n')" line is not logging...hmmm

**Comment by webteckie** [comment]
@JedWatson not sure why the dashes...are not logging.  If I do the following:

						if (err) {
							console.error(_dashes_ + '\nUpdate ' + file + ' failed with error:\n'+err);
							if ('stack' in err) {
								console.trace(err.stack);
							}
							done(err);
						} else {

I get the following, but doesn't have enough details, in which case I prefer the first commit at the expense of not logging the update file name:

    ------------------------------------------------
    Update 0.0.1-allvacationplaces_com failed with error:
    ValidationError: Path `startTime` is required.

I've tried multiple combinations of console.error, console.log, and no combination logs all 3 things (the dashes/update-filename, the error, and the stack).  Any ideas?

**Comment by JedWatson** [comment]
@sebmck can you have a look at this?

**Comment by sebmck** [comment]
`console.trace` doesn't accept any arguments. It just dumps the current call stack. `console.error(err.stack);` should work.

**Comment by webteckie** [comment]
@sebmck according to http://nodejs.org/api/console.html console.trace does accept arguments.   Anyways,  some of the tests that I did dumped the trace correctly.   There's something going on with the logging that happens just before the trace is dumped.   I wonder if this is still a case of node exiting too quickly before the logging is dumped.  I will put a setTimeout to discard that possibility.   I will try again later tomorrow.  I will also try your suggestion in case there's something to that.

**Comment by sebmck** [comment]
@webteckie Ah right, it accepts a `message` argument, still not very relevant. There's no real way the event loop could be empty so I'm skeptical that's the case. It's likely just that mongoose messes with errors and in some scenarios the call stack isn't bound to the error (so only the `message` appears in the `stack`).

**Comment by JedWatson** [comment]
I think this change looks good, I've merged it so we can throw some more cases at it.

**Pull request merged**
