### PR TITLE
Remove mongose-unique-validator

### PR DESCRIPTION
**Pull request by timleslie**

### CODE REVIEW

**Comment by Vultraz** [comment]
Damn. :( Is there a better way to get a message other than the internal E11000 error?

**Comment by gautamsi** [comment]
I had rough day in seeding database with large number of static data 😞 due to `mongoose-unique-validator`

**Comment by Vultraz** [comment]
Oh, geez. Sorry for causing you guys trouble with this one 😞

**Comment by gautamsi** [comment]
> Oh, geez. Sorry for causing you guys trouble with this one 😞

Don't worry, I have had similar situation recently

**Comment by timleslie** [comment]
All good, sometimes you need to put something out into the real world before you know whether it’s going to work out or not.

**Pull request merged**
