### PR TITLE
Allowed configuring default/maximumPageSize for all lists

### PR DESCRIPTION
**Pull request by Vultraz**
~It occurred to me that these options make a *lot* more sense when applied to the whole Admin UI, instead of per-list. I really doubt anyone is thinking, hey, we want list A to show 50 items at once while lists B and C have 10 items and this other one has 20. Max page size makes even less sense on a per-list basis (who would want to see a completely arbitrary maximum number of items depending on the given list?)~

~This leaves the sort options untouched (since those are indeed list-dependent) and moves the `defaultPageSize` and `maximumPageSize` config options to the Admin UI ctor.~

Update: this now just adds `defaultPageSize` and `maximumPageSize` config options that allows configuring the defaults for all lists. All handling of `adminConfig` options (such as stripping whitespace) is now handled by the Admin UI app.

### CODE REVIEW

**Comment by Vultraz** [comment]
Rebased

**Comment by gautamsi** [comment]
I like this but am sure someone would want to limit few list higher size rather than small limit lists.

**Comment by Vultraz** [comment]
Hmmmm....

**Comment by VinayaSathyanarayana** [comment]
We should have per List options... taking the global Admin UI values if not set at the List level.

**Comment by Vultraz** [comment]
Ok, that's a good idea. Will do that.

**Comment by Vultraz** [comment]
Ok, this is ready.

**Comment by Vultraz** [comment]
@timleslie conflict-be-gone

**Comment by Vultraz** [comment]
I'll fix the conflicts on this after #3056 is merged.

**Comment by Vultraz** [comment]
@timleslie since that other one is stalled I just went and fixed the conflicts on this.

**Pull request merged**
