### PR TITLE
Fix Fields for using new API [WiP]

### PR DESCRIPTION
**Pull request by wmertens**
Going through all the field types and fix creating and updating them via the new API

### CODE REVIEW

**Comment by wmertens** [comment]
Ignored: All file Fields (will be replaced with Storage field and nested arrays)

Also, the Code Field needs codemirror, which it loads from the repo but that is not there. Use the CDN instead?

**Comment by JedWatson** [comment]
@wmertens this looks fantastic! thanks 😀 

@jossmac is doing a fair bit of work going through the fields as well, how do you feel about several PRs that we merge regularly (when you confirm they're stable) so we don't leave this out of master for too long? I'd hate for either of you to end up conflicting with each other or doubling up on the same work.

From my review, the location / geo / html field fixes all look good to go, as do the updates for refs. I'd be happy to merge those asap if you roll back the removal of `/legacy/` in the API paths (keep that change locally while you're testing, we can merge it last)

**Comment by JedWatson** [comment]
re: codemirror, it gets loaded from the global `window.Codemirror` which should be coming from a `<script>` tag in the template that loads [/js/lib/codemirror](https://github.com/keystonejs/keystone/tree/master/admin/public/js/lib/codemirror). Browserify-shim is set up to point at it (see [package.json](https://github.com/keystonejs/keystone/blob/master/package.json#L131)) when you do `require('codemirror')`. This has been working for me locally, are you seeing issues?

**Comment by wmertens** [comment]
@JedWatson this is ready for a first pull; more to come obviously.

I was not able to figure out why a failed create drops down to the update route. To reproduce, run `node test/e2e/server.js --notest`, go to the name list and create an incomplete name.

**Comment by JedWatson** [comment]
Awesome. Thanks @wmertens!

**Pull request merged**
