### PR TITLE
S3Files Field

### PR DESCRIPTION
**Pull request by sarriaroman**
A field to upload multiple files to Amazon S3 using the LocalFiles Field for the UI

### CODE REVIEW

**Comment by JedWatson** [comment]
@sarriaroman I really appreciate you adding this, is there any chance you'd be interested in contributing to the `file-fields` branch with myself and @creynders?

We're actually working to get rid of all the specific file fields and replace them with just *two*:

- `Types.File`
- `Types.Files`

... and each field can be bound to a storage configuration.

Unfortunately merging this PR at this stage may not be a good idea because it will conflict with our transition to the generic file field, I'm interested in @creynders view on this though...

**Comment by JedWatson** [comment]
The issue relating to the File fields is #1222

**Comment by sarriaroman** [comment]
@JedWatson I'm agree with the point of view of @creynders but I see the solution as a future solution. I will try to put work to get it faster.

This is a fast solution for a problem I had for a long time ;).

**Comment by JedWatson** [comment]
Thanks for the PR @sarriaroman and sorry for leaving it hanging so long. We'll be coming back around to file fields soon with a different approach (cc/ @mxstbr @creynders), so I'm going to close this.

**Pull request closed without merging**
