### PR TITLE
Adds debug to core files.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
Adding debug statements to keystone for much win.

### CODE REVIEW

**Comment by sebmck** [comment]
This is going to sound extremely nitpicky but the capitalisation is inconsistent in the debug messages.

**Comment by BerkeleyTrue** [comment]
yes. will correct.

**Comment by BerkeleyTrue** [comment]
corrected

**Comment by JedWatson** [comment]
Looks good to me. I like the namespacing you're using.

**Comment by BerkeleyTrue** [comment]
Ready to be merged

**Pull request merged**
