### PR TITLE
Upgrade Babel to V6

### PR DESCRIPTION
**Pull request by mekanics**
this should fix some error building:
- views/home.js
- views/item.js
- views/list.js
- fields.js:

I think it's related and fixes the following issues: 
#1934
#1865
#1514
#1411
and maybe more... 

would be nice if @JedWatson could make a new version v0.3.17 with this fix

### CODE REVIEW

**Comment by morenoh149** [comment]
:100:

**Comment by mikestopcontinues** [comment]
I would very much appreciate this! 😇

**Comment by JedWatson** [comment]
Thanks @mekanics - on that now!

We _still_ need the `object-assign` plugin for v6, I'll add that back in after merging.

**Comment by mekanics** [comment]
🍻

**Pull request merged**
