### PR TITLE
#4589: Update to Mongoose 5.0

### PR DESCRIPTION
**Pull request by gautamsi**
## Description of changes
updated mongoose to 5.2, with mongodb connection useNewUrlParser option. Also updated collection.count deprecation notice which asks to use countDocuments instead of count. this breaks away from mongoose 5.0. requires 5.2 and above. 

## Related issues (if any)
#4589 

## Testing

 - [x] List browser version(s) any admin UI changes were tested in
    - tested in Chrome browser on mac, no change to admin ui
 - [x] Please confirm you've added (or verified) test coverage for this change.
    - no code coverage change
 - [x] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by stennie** [comment]
Thanks @gautamsi!

It looks like there aren't many changes that directly affect Keystone core, but we've already started making Release Candidates for 4.0.0 GA. In order to minimise [breaking changes](https://github.com/Automattic/mongoose/blob/master/History.md#500-rc0--2017-12-28) for users upgrading to Keystone 4.0.0, we're going to hold off merging this to master until after GA.

Regards,
Stennie

**Comment by ttsirkia** [comment]
Just writing this down here: https://github.com/Automattic/mongoose/pull/5878 This is a major change and without any configuration Mongoose 5 doesn't find the old data saved with the old version because the model names in the database are different (`courses` -> `Course`)

**Comment by stennie** [comment]
@ttsirkia Thanks for flagging potential problems. The [last comment on Automattic/mongoose#5878](https://github.com/Automattic/mongoose/pull/5878#issuecomment-353991842) suggests this didn't land as a breaking change (despite the issue title):

> Upon more careful thought, we're going to err on the side of stability and include the mongoose-legacy-pluralize package by default, so no backwards breaking changes. This is something that we just haven't given devs sufficient notice about - we've had deprecation warnings about promises, useMongoClient, etc. for quite a while, so affected users have been warned about these changes even if they don't check slack, GitHub, or twitter. If we're going to drop legacy pluralization, I'd like to have a loud deprecation warning for at least a few months so we minimize the likelihood someone will be surprised by this change.

If the default has changed in a later Mongoose 5.x release, it looks like `mongoose-legacy-pluralize` can be used to enable the prior behaviour.

Regards,
Stennie

**Comment by ttsirkia** [comment]
At least when running Keystone with Mongoose 5.2 the non-pluralized model names were used in the database. This has to be investigated further when merged.

**Comment by gautamsi** [comment]
I will take a look on this soon.

**Comment by ttsirkia** [comment]
This is of course a problem only if there is an old system which is updated. If a fresh project is started, everything works fine.

**Comment by ttsirkia** [comment]
I tried this one more time with Mongoose 4.13.14 and 5.2.5. Mongoose 4 creates lower-case plurals `courses` and Mongoose 5 capitalized singulars `Course`. Of course the reason can be how KeystoneJS integrates its models to Mongoose models and Mongoose is working as expected.

**Comment by mahnunchik** [comment]
Any news?

**Comment by zenflow** [comment]
I understand that since Keystone exposes the Mongoose API, this will be a breaking change, and AFAIK can't be merged until the next major release..

> we're going to hold off merging this to master until after GA

@stennie sorry, what is "GA"?

**Comment by Kiina** [comment]
> @stennie sorry, what is "GA"?

General availability, basically this stable release

https://github.com/keystonejs/keystone/releases/tag/v4.0.0

**Comment by mahnunchik** [comment]
Any news?

**Comment by gautamsi** [comment]
it has not made to [4.0.1](https://github.com/keystonejs/keystone/milestone/11) milestone yet

**Comment by ttsirkia** [comment]
It seems that `countDocuments` is extremely slow if there is a large number of rows. `estimatedDocumentCount` works as fast as the previous `count`.

**Comment by JedWatson** [comment]
@gautamsi thanks for the work on this. Unfortunately, given the number of breaking changes involved in this move, I'm going to call it out of scope for 4.x as an outright upgrade.

We do support a way of having users provide their own copy of mongoose though, so we could potentially include a compatibility mode for projects that really want the new version. @gautamsi let me know if you're interested in looking at that.

**Comment by gautamsi** [comment]
@JedWatson I will work on this.

**Comment by ttsirkia** [comment]
I've been using this PR in my production environment without any problems. In case that there is old data, see my last comment in #4589.

**Comment by JedWatson** [comment]
@gautamsi check out https://github.com/keystonejs/keystone/blob/master/index.js#L89

There's a `mongoose` option, basically what I'm thinking is someone could set that to a copy of `v5` and if we can detect the version these changes you've made here could sit inside a code fork depending on whether they're using 4 or 5

If version detection won't work, we could potentially add another option (something like `mongoose version` which would default to `4` but would also support `5`)

**Comment by JedWatson** [comment]
@ttsirkia sounds like a good reason to support this then 🙂 

To be clear I'm not worried about breaking changes in Keystone's usage of mongoose, but if the new version requires changes in userland (which is my understanding) it would be a big breaking change for keystone to automatically include the new version.

**Comment by ttsirkia** [comment]
@JedWatson of course it depends on the client-side if something will break. I didn't change anything in my DB-related code and I've rather complex queries etc.

**Pull request closed without merging**
