### PR TITLE
Fix issue #3001 - Markdown not showing up in downloads

### PR DESCRIPTION
**Pull request by WelltokCaleb**
## Description of changes
See https://github.com/keystonejs/keystone/issues/3001 for context. Small change to MarkdownType.js.

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by jstockwin** [comment]
Thanks @WelltokCaleb! 

@keystonejs/core-devs - this looks reasonable to me, unless there is some underlying reason for using `.html` instead of `.md` that I'm completely overlooking?

**Comment by mxstbr** [comment]
LGTM, though I think @JedWatson needs to double check this. I'll mark it ready and he can merge it if he agrees!

**Comment by JedWatson** [comment]
See my comments on #3001

**Comment by WelltokCaleb** [comment]
Thanks, @JedWatson. I just left a long-ish comment/proposal on the Issue; let me know your thoughts.

**Comment by WelltokCaleb** [comment]
@JedWatson - would love your thoughts on this PR, too. :-)

**Comment by JedWatson** [comment]
Closed by #3436

**Pull request closed without merging**
