### PR TITLE
Added folder option to wysiwyg cloudinary images

### PR DESCRIPTION
**Pull request by millsy**
As per this message https://groups.google.com/forum/#!searchin/keystonejs/wysiwyg$20images$20folder/keystonejs/VxuSOzRM32g/EHDKwtZY_koJ and this issue https://github.com/keystonejs/keystone/issues/832

I have added the ability to provide an array of upload options when using the wysiwyg cloudinary editor.

```
keystone.init({
...
'wysiwyg cloudinary images options': {
        'folder': '/posts/images',
        'tags': 'test'
    },
...
});
```

### CODE REVIEW

**Comment by morenoh149** [comment]
lgtm

**Comment by bringking** [comment]
Is this going to be merged in? We need this feature to change the upload type for our Cloudinary images.. let me know if we can help in any way

**Comment by mxstbr** [comment]
Looks like a useful addition, sorry for taking so long to get back at you @millsy! Could you rebase this onto master and add a bit of documentation about this feature? Then I'll merge it and we can release it with 0.4!

**Comment by JedWatson** [comment]
We're going to revisit the cloudinary api after releasing 4.0 final, thanks for the original PR @millsy - please let us know if you're interested in updating it.

**Pull request closed without merging**
