### PR TITLE
Add language options.

### PR DESCRIPTION
**Pull request by ericelliott**
Add language negotiation options for i18n:

1. Query param, e.g., http://host:port/path?locale=en_US
2. If cookie is present, use cookie value
3. browser Accept-Language header

For details, see https://github.com/keystonejs/keystone/issues/802#issuecomment-170283978

#802

### CODE REVIEW

**Comment by JedWatson** [comment]
Looks great, @ericelliott, thanks!

**Comment by ArnauAregall** [comment]
Hi guys,

Be aware of this issue tinganho/express-request-language/issues/5; looks like a vulnerability that aparently allows to set in `language` cookie (or however you name it) *any* value by just performing a GET request.

**Comment by ArnauAregall** [comment]
> Hi guys,
> 
> Be aware of this issue tinganho/express-request-language#5; looks like a vulnerability that aparently  allows to set in language cookie (or however you name it) any value by just performing a GET request.

This problem is solved in  `express-request-language@1.1.1`. 

Greenkeeper made the PR #2313 to update the dependency, but tests are failing apparently due to language middleware... might review them because the change in 1.1.1 is super simple (see tinganho/express-request-language@9c43cf4a58c72fbd37c3461dff13aa51b7bd72be).

**Comment by ArnauAregall** [comment]
> Hi guys,
> 
> Be aware of this issue tinganho/express-request-language#5; looks like a vulnerability that aparently  allows to set in language cookie (or however you name it) any value by just performing a GET request.

Fixed in `express-request-language@1.1.3`, greenkeeper created PR #2315 to update dependency version.

**Comment by JedWatson** [comment]
Thanks for the heads up @ArnauAregall! Just merged the update.

**Comment by ArnauAregall** [comment]
Cool! 👍🏻 @JedWatson

**Pull request merged**
