### PR TITLE
Consolidated #2427 and #2497 (functional components)

### PR DESCRIPTION
**Pull request by Vultraz**
Consolidated the two for easier review. The latter had some stuff (moving route props) that's now covered in #2827, and I figured out what to do with the nonexistent `innerRef` in #2731. Should be good to go.

### CODE REVIEW

**Comment by Vultraz** [comment]
Added `EditFilterPopup`.

**Comment by Vultraz** [comment]
Added `AnimateHeight`.

**Comment by tomasztunik** [comment]
merged #2910 affects refactor of AnimateHeight

**Comment by Vultraz** [comment]
@tomasztunik resolved conflict 👍

**Comment by timleslie** [comment]
@Vultraz Sorry for the delay on this one, it's a bit more complex so I had Joss take a look, but it all looks good. And as I type this I see you've resolved the merge :-)

**Comment by Vultraz** [comment]
@timleslie talk about timing 😂

**Pull request merged**
