### PR TITLE
clean up main README: installation and usage more visible

### PR DESCRIPTION
**Pull request by htor**
many people discover and judge new projects by scimming over READMEs, so to increase adoption I think it's a good idea to put the install *and* usage sections right in sight on top. that way it is easy to see how to get up and running, just like on the website.

two main changes:
1. the main README is rearranged a bit and installation and usage sections are on top. added a "install nodejs + mongodb" too.
2. changes in v4 is moved into HISTORY so they are not taking valuable screen space in the main README.

@Noviny what do you think?

### CODE REVIEW

**Comment by htor** [comment]
@JedWatson 
what do you think? i think it would be great for new users to have a simple starting point to get up and running in the README.

**Comment by laszlotordacsanyi** [comment]
Great idea, but here are two videos that can be traced well and are excellent for teaching the basics: https://www.youtube.com/watch?v=DPXDFeUEk3g -- keystonejs
https://www.youtube.com/watch?v=pWbMrx5rVBE -- mongodb

**Comment by htor** [comment]
hi @jossmac @mxstbr any corrections or suggestions?
i'm still convinced the readme needs a little more love. should be quick and easy to do.

**Comment by htor** [comment]
@laszlotordacsanyi 
nice, i could put links to those in the readme too!

**Comment by stennie** [comment]
@htor Agree the README could use more structure and have tackled some clean up via #4666 and #4671 for the Keystone 4.0.0 RC. I'm going to close this PR since it has been superseded, but any further suggestions or feedback would be appreciated.

I think the README should serve as an overview of the project with appropriate signposts to the documentation for more details. Links to videos and other third party resources would be more appropriate for the wiki or documentation as they will tend to get outdated quickly.

Regards,
Stennie

**Comment by htor** [comment]
@stennie nice, looks like https://github.com/keystonejs/keystone/pull/4671 has removed a lot of noise from the main README which was my intention. my last suggestion now is to look at the ugly "title-table" at the top above the logo. i suggest it should be obliterated, because it serves no purpose. cheers!

**Comment by stennie** [comment]
@htor Thanks for the feedback. I assumed the strange title table had some purpose, but it doesn't appear to be useful for GitHub, npm, or Gatsby rendering as far as I can tell. This was added in #0c8bfa1cd (nominally for Gatsby) so I'll check there before removing.

**Pull request closed without merging**
