### PR TITLE
Save original file name on AWS uploads

### PR DESCRIPTION
**Pull request by Subash**

### CODE REVIEW

**Comment by Subash** [comment]
*aws, autocomplete messed up

**Comment by morenoh149** [comment]
https://github.com/Subash/keystone/blob/master/fields/types/s3file/S3FileType.js#L406 Is the `protocol` var used here?

**Comment by morenoh149** [comment]
https://github.com/Subash/keystone/blob/master/fields/types/s3file/S3FileType.js#L395 Is `path + filename` not the original filename?

**Comment by Subash** [comment]
@morenoh149, filename is a temporary file name that looks like, `ff196d9499e3a4898874e65bc131d13f`

**Comment by creynders** [comment]
@Subash we're re-writing all file fields, including s3. The original file name will automatically be saved in the new version.

**Comment by JedWatson** [comment]
@creynders maybe we should merge this into 0.3, since we're deprecating the individual file fields in 0.4, what do you think? safe to do?

**Comment by creynders** [comment]
@JedWatson you're right, there's no harm in merging it into v0.3

**Comment by JedWatson** [comment]
Cool, I'll merge it then :)

Thanks @Subash!

**Pull request merged**
