### PR TITLE
WIP - Initial Redux installation for Admin Client

### PR DESCRIPTION
**Pull request by kevinold**
This is a WIP and @JedWatson asked me to open this PR for initial review, discussion and collaboration.

Highlights:
- Installs Redux, React Redux, Redux DevTools, Redux Thunk (middleware) and Immutable
- Install a standard set of Redux directories and minor boilerplate for actions, reducers, constants, containers and utils
- Break home.js into HomeView.js and ListTitle.js components

This patch as the Home page of the Admin running through Redux.  As the screenshots attached show, using Ctrl+P will enable/disable the Redux Devtools for inspecting state.  

The reducer state is currently unpopulated.  Best practices around providing Redux with its initialState from the server are here: http://redux.js.org/docs/recipes/ServerRendering.html.

There is plenty left to do:

- Complete migration of the Home page (data to be managed in Redux)
- Migrating the remaining views to separate components
- Installation of react-router or https://github.com/jlongster/redux-simple-router (http://jlongster.com/A-Simple-Way-to-Route-with-Redux)
- Extraction of xhr methods into utility methods
- Defining and implementing reducers and overall state shape
- Defining and implementing actions
- Update server actions to use Redux on the server for initialState

screen shot 2015-11-25 at 10 37 17 pm
screen shot 2015-11-24 at 11 04 30 pm

### CODE REVIEW

**Comment by mattapperson** [comment]
Might I suggest react-router and redux-react-router

**Comment by kevinold** [comment]
@mattapperson I had that listed under the items left to do

**Comment by mattapperson** [comment]
@kevinold just voting on that vs redux-simple-router

**Comment by kevinold** [comment]
@mattapperson @JedWatson ^^^ See latest commit e843b87.  I'm trying to get redux-router wired up but am hitting an issue when rendering.  Any ideas?

screen shot 2015-12-11 at 8 42 02 am

**Comment by mattapperson** [comment]
Well somewhere you are trying to create a react component that is undefined. I will try and pull down your code later today and give it a run. But I would start by checking your components exist.

**Comment by kevinold** [comment]
@mattapperson I did just catch 26d8bd3 but that doesn't seem to fix :(

**Comment by mattapperson** [comment]
@kevinold that first error is a clear one. You still have some dissension somewhere in your react component ranks 😊

**Comment by kevinold** [comment]
This simple gist shows it might be something with the Route as provided by redux-router *shrug*: https://gist.github.com/kevinold/eb42a9c1251aa055a28b

**Pull request closed without merging**
