### PR TITLE
Fix dependson initial

### PR DESCRIPTION
**Pull request by geloescht**
## Description of changes
Check for typeof instead of doing || in Type.prototype.getDefaultValue, so an empty string is really only returned if no default value is set. (compared to when `default: false` is set). Also ensure that a boolean is always the default for a boolean fields.
There should maybe also other default default values be defined for other field types apart from boolean, but it's the most common use case and I can't think of  sensible defaults for most other field types. Feel free to discuss here.
## Related issues (if any)

#2929 

## Testing

- [x] Please confirm that you have successfully ran `npm run test`. e2e tests take too long and make me unproductive by popping up browser windows in random intervals.

### CODE REVIEW

**Comment by mxstbr** [comment]
This LGTM, while you're touching that part of the code would you mind adding unit tests for that function for different cases too? (take inspiration from the tests in `test/filter.js`)

**Comment by geloescht** [comment]
@mxstbr Well, I am not sure where I am supposed to put those tests and what I should test for. Did you mean `fields/types/*/test/filters.js`?
BTW, why do we return an empty string instead of `undefined` from getDefaultValue()? For example, how can a Number field have an empty string as a value? Would it hurt to just return undefined and let client code handle the absence of a default value?

**Comment by mxstbr** [comment]
> Did you mean fields/types/*/test/filters.js?

Yeah exactly, make a new file there called `default.js` maybe?

> BTW, why do we return an empty string instead of undefined from getDefaultValue()? For example, how can a Number field have an empty string as a value? Would it hurt to just return undefined and let client code handle the absence of a default value?

That's a question for the rest of @keystonejs/core-devs, I honestly don't know.

**Comment by geloescht** [comment]
I see. I'd rather like to have this PR merged as a hot-fix without the tests, please. I can't really come up with meaningful tests without having a guideline on what getDefaultValue() is supposed to return when there is no default value provided by the app developer (in general and / or for each field type). I fear that if I just go and invent some default default values I could break frontend code that expects this empty string. Then we'd have tests that actually break something else in order to pass.

**Comment by mxstbr** [comment]
Fair enough, thanks for the work @geloescht!

**Comment by Vincent-Loi** [comment]
Just pulled the latest commit with this merge and realised that it actually broke it? The boolean field goes missing in UI.

Think this is because of the prototype added (line 19-22) in BooleanType.js. Appears when removed. Please let me know if it's the same for you?

```
boolean.prototype.defaults = {
	default: false,
};
```

**Comment by jstockwin** [comment]
@Vincent-Loi This works fine for me. Running the test server (`node test/e2e/server.js --notest`) and then creating a new "Depends On" item, the select field appears/disappears as I toggle the boolean field. The boolean field always stays visible.

**Comment by geloescht** [comment]
@Vincent-Loi Boolean fields keep working fine for me. Is there any dependsOn involved? Maybe you relied on the broken behaviour earlier.

**Comment by Vincent-Loi** [comment]
Hm weird. I just created a test model with no dependsOn or anything but still reproduced the bug..

var keystone = require('keystone');
var Types = keystone.Field.Types;


```
var somemodel = new keystone.List('some model')
somemodel.add({
  string: { type: String },
  tickBox: { type: Types.Boolean }
})
somemodel.register();
```

## With prototype

screen shot 2016-05-26 at 4 33 24 pm

## Without prototype
screen shot 2016-05-26 at 4 33 56 pm`

**Comment by jstockwin** [comment]
@Vincent-Loi I'm not really familiar with prototyping, but this sounds like a separate issue to me, so could you please open a new issue about this?

**Comment by Vincent-Loi** [comment]
@jstockwin I was referring to the prototype I pasted above? So without this would not introduce this issue

**Comment by jstockwin** [comment]
@Vincent-Loi but this has nothing to do with "Depends On" anymore, which is what this PR fixed?

**Comment by geloescht** [comment]
I can't reproduce but we could also define the property on the object itself instead of the prototype, if that helps.

**Comment by Vincent-Loi** [comment]
Okay - I thought this was the fix for initial because the value doesn't change even if `initial: true` was set in the model.

@geloescht Hm you could but no reason why only I'm getting this issue haha

**Comment by webteckie** [comment]
yeah, don't think there's such a public property `Field.prototype.defaults`...there seems to be a private property `defaults` and a public `Field.prototype.getDefaultValue`...is this correct @geloescht ?

**Comment by geloescht** [comment]
There are no private properties in Javascript, but yes, .defaults is user internally to populate the field options with default values.

**Comment by Vincent-Loi** [comment]
Right okay. Can I also raise that the `default: true` option doesn't populate the edit form either?

**Comment by geloescht** [comment]
I still can't reproduce @Vincent-Loi 's issue, but there is definitely something fishy going on with defaults. Suddenly Boolean fields that don't have initial or required set to true become initial and required.

**Comment by geloescht** [comment]
OK, I get it. The options() function in keystone-utils works in an mindblowingly stupid way, that modifies the defaults instead of the options and then returns the modified object. Because I defined defaults on the prototype, every time you create a new field it gets the modified defaults from the previous one. IMO it should be fixed in keystone-utils. Sorry for the rant.

**Comment by geloescht** [comment]
Or maybe I should take the beating for defining defaults on the prototype.

**Comment by webteckie** [comment]
You actually had me going off to study my js again and actually wrote a sample to reproduce this...I couldn't get it to work as you intended :-)

**Pull request merged**
