### PR TITLE
Tests added and passing for validators.js

### PR DESCRIPTION
**Pull request by Noviny**
Currently all that rely on the the text methods have tests and are passing.

### CODE REVIEW

**Comment by Noviny** [comment]
@JedWatson This has been updated.

**Comment by morenoh149** [comment]
be sure to pass the linter rules as well https://github.com/keystonejs/keystone/blob/master/CONTRIBUTING.md

**Comment by Noviny** [comment]
Sorry for that. It is now linted also.

**Comment by JedWatson** [comment]
A couple of things to clean up here, but I'll merge & fix them so it doesn't get out of date and cause conflicts. Thanks for the tests!

**Pull request merged**
