### PR TITLE
[WIP] List Plugins for new-interface

### PR DESCRIPTION
**Pull request by gautamsi**
trying to port list plugins for new interface

- [x] atTracking - in progress - initial try in this wip so far
- [x] byTracking
- [ ] logging
- [ ] singleton

```ts
list(withAtTracking({...listConfig}, {...atTrackingOptions}));
```

caveat is that we would have to wrap it multiple time and also makes it difficult for adding config.

@timleslie @JedWatson  can you provide feedback on this approach?

### CODE REVIEW

**Comment by gautamsi** [comment]
@timleslie can I get some feedback to complete this? if i am going in right direction or not

**Comment by gautamsi** [comment]
@timleslie is this in roadmap, should I continue work on this?

**Comment by timleslie** [comment]
Hi @gautamsi, at the moment we're not looking to support these features until we've finalised the new API implementation.

**Comment by gautamsi** [comment]
Okay

**Comment by gautamsi** [comment]
it is live here - https://www.npmjs.com/package/@keystonejs-contrib-next/list-plugins

**Pull request closed without merging**
