### PR TITLE
add a note about homebrew

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Review by timleslie — DISMISSED** [review]
Holding off on merging pending larger website changes 👍

**Review by JedWatson — APPROVED** [review]
The website changes @timleslie mentioned have landed so I think we're good to merge this now.

Thanks for the contrib @kud!

**Comment by kud** [comment]
My pleasure! I'm a newbie with keystone and if it can help, i'll be glad :)

**Review by bladey — DISMISSED** [review]
I'm quite sure this should be `postgres://my-username@localhost/my-app`, I run into errors if I use the format `postgres://my-username:localhost/my-app`, is this right?

**Comment by kud** [comment]
> I'm quite sure this should be `postgres://my-username@localhost/my-app`, I run into errors if I use the format `postgres://my-username:localhost/my-app`, is this right?

It seems that I was tired when I patched it. It's indeed `@` and not `:`, thank you. :)

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
