### PR TITLE
Fix for real deleting files on disk

### LINKED ISSUE #1382: Unable to remove uploaded files
I've added audio files to the Post model using LocalFiles and the files are uploaded and usable. However, when I try to remove them nothing happens. No errors, the file remains attached to the post and in the local storage. The entry for the audio files is:

        audio: { type: Types.LocalFiles, dest:"public/audio/uploads", prefix: '/audio/uploads', filename: function(item, file) {return item.slug + '.' + file;  } }

Any ideas on where to look for the errors?

### PR DESCRIPTION
**Pull request by jacargentina**
@JedWatson
This solved my problem when trying to removing files via code, 
May be also fixes #1382?

### CODE REVIEW

**Comment by wmertens** [comment]
:+1:

**Comment by JedWatson** [comment]
Thanks @jacargentina. I suspect there's a deeper issue here (something else has happened that's causing this fix to be required) and I'm inclined to work that out rather than band-aid it. I'll merge this in the interim and add a TODO if you need it in a hurry, let me know.

**Comment by jacargentina** [comment]
@JedWatson Yes, please merge it

**Comment by jacargentina** [comment]
Could you cherry pick this and apply on v0.4? I'm using that branch now.

**Comment by JedWatson** [comment]
@jacargentina done, let me know if you have any issues with it.

**Pull request merged**
