### PR TITLE
Add support for saucelabs in travis e2e

### PR DESCRIPTION
**Pull request by webteckie**
Add support for sauce labs as the prefer method to do nightwatch e2e ui/functional testing in the Travis CI environment.

### CODE REVIEW

**Comment by JedWatson** [comment]
Nice work @webteckie :D

**Comment by morenoh149** [comment]
@JedWatson do the tests run on your machine? I can't get them to run on osx with Firefox.

**Comment by webteckie** [comment]
@morenoh149 what are you getting?  how are you running them?  note:  travis failed the master build with some issues around the new validateInput.js module.  Not sure that's about...perhaps babel related?

**Comment by morenoh149** [comment]
I've opened bugs in [nightwatch](https://github.com/nightwatchjs/nightwatch/issues/293#issuecomment-183824463) and [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1248214) regarding Firefox freezing when `setValue` is called
```shell
------------------------------------------------
KeystoneJS Started:
e2e is ready on port 3000
------------------------------------------------

keystone done starting
Starting selenium server... started - PID:  1071

[Group001 Login /  Test001 Has Signin View] Test Suite
======================================================

Running:  Keystone should have a signin view
GET /keystone/ 302 5.436 ms
GET /keystone/signin?from=/ 200 126.232 ms
GET /favicon.ico 404 4.428 ms
 ✔ Element <div#signin-view> was visible after 9038 milliseconds.

OK. 1 assertions passed. (15.058s)

[Group001 Login /  Test002 Can Login] Test Suite
================================================

Running:  Keystone should allow admins to login to the Admin UI
GET /keystone/ 302 1.180 ms
GET /keystone/signin?from=/ 200 1.998 ms
GET /favicon.ico 404 1.489 ms
 ✔ Element <div#signin-view> was visible after 619 milliseconds.
^C
```

**Pull request merged**
