### PR TITLE
Add @select-menu-max-height variable to react.less

### PR DESCRIPTION
**Pull request by esparragito**
This is one solution to the error in [#1182]

### CODE REVIEW

**Comment by tekwiz** [comment]
+1 This fixed the issue for us

**Comment by JedWatson** [comment]
Thanks, really should have been a major version bump on react-select given that it needed a new less variable!

**Comment by esparragito** [comment]
@JedWatson On the react-select side, is there any value in trying to get a module requiring react-select to use the default.less before overriding with defined variables, just to avoid the error being thrown in the event of future updates to the less structure?

**Comment by JedWatson** [comment]
Yes, that would be good as long as the variables behaved like defaults when undefined (rather than overriding)

Haven't tested how to achieve that but it would be a great thing to look into.

**Comment by esparragito** [comment]
Including default.less at the beginning rather than the end of the keystone file lets the variable definitions behave as overrides, but I don't know if that messes anything up elsewhere.

**Comment by esparragito** [comment]
Maybe clearer: https://gist.github.com/esparragito/bfaa94ae5e0b30bea049

**Pull request merged**
