### PR TITLE
drag drop across pages

### PR DESCRIPTION
**Pull request by snowkeeper**
Can replace previous PR.  
Adds the ability to drag items across pages.
Adds `perPage` list configuration option.
#### Drag single page
dnd1
#### Drag across pages
dnd3
#### Drop onto a page
dnd2

### CODE REVIEW

**Comment by JedWatson** [comment]
@snowkeeper looks great, could you rebase though? there are conflicts, probably from recent PR merges. Makes sense that this would replace #1815 so maybe close that if it's not needed anymore?

**Comment by jonathanp** [comment]
Looks really good @snowkeeper!

**Comment by snowkeeper** [comment]
Thanks @jonathanp !

This should be ready to merge @JedWatson 

How do we get travis to pass checks again?

**Comment by snowkeeper** [comment]
We used to have a `perPage` option per the docs.  I assume it got removed at some point.  The docs have the default at **50**.  We have the current set to **100**.  Which one should we use?

**Comment by snowkeeper** [comment]
When testing I found that Microsoft Edge aggressively cached everything, including links not yet clicked.

 So changing order worked correctly, but when you switched pages the initial results were **always** displayed.  Using F12 you can verify that the correct list info is being fetched, but not applied.

You can load page 1.  In another browser make a change to an item from page 2.  Back in Edge click on page 2 and the results are stale, from the initial page load.  Again F12 shows that the correct info is fetched, but not applied.

**Pull request closed without merging**
