### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by dcousens**
The following packages have been updated
```
@keystone-6/auth@8.1.0
@keystone-6/core@6.3.1
@keystone-6/fields-document@9.1.1
create-keystone-app@10.0.3
```

#### New Features
- `[auth]` Updates the welcome page newsletter to include Thinkmill (#9335) @benderham

#### Bug Fixes
- `[core]` Fix misleading error messages when importing `.keystone/config.js` (#9359) @marekryb
- `[core]` Fixes `serxer.maxFileSize` parameter being ignored (#9348) @dcousens
- `[fields-document]` Fixes URL validation bug by using `encodeURI` to preserve percent-encoded characters during validation. (#9326) @kidneyweakx
- `[core]` Updates `prisma` minor version to `5.22.0` (#9391) @dcousens
- `[core]` Fixes `decimal` field bug (#8597) by parsing to `Decimal` before lessThan / greaterThan checks (#9262) @kennedybaird
- `[create-keystone-app]` Fix output formatting for CLI instructions (#9391) @dcousens

#### :blue_heart: Acknowledgements 
Lastly, thanks to @benderham ([#9332](https://github.com/keystonejs/keystone/pull/9332),[#9320](https://github.com/keystonejs/keystone/pull/9320)), @dcousens ([#9391](https://github.com/keystonejs/keystone/pull/9391),[#9317](https://github.com/keystonejs/keystone/pull/9317),[#9314](https://github.com/keystonejs/keystone/pull/9314)), @iamandrewluca ([#9361](https://github.com/keystonejs/keystone/pull/9361),[#9327](https://github.com/keystonejs/keystone/pull/9327),[#9328](https://github.com/keystonejs/keystone/pull/9328)), @renovate ([#9390](https://github.com/keystonejs/keystone/pull/9390),[#9389](https://github.com/keystonejs/keystone/pull/9389),[#9388](https://github.com/keystonejs/keystone/pull/9388),[#9387](https://github.com/keystonejs/keystone/pull/9387),[#9386](https://github.com/keystonejs/keystone/pull/9386),[#9381](https://github.com/keystonejs/keystone/pull/9381),[#9378](https://github.com/keystonejs/keystone/pull/9378),[#9379](https://github.com/keystonejs/keystone/pull/9379),[#9380](https://github.com/keystonejs/keystone/pull/9380),[#9377](https://github.com/keystonejs/keystone/pull/9377),[#9369](https://github.com/keystonejs/keystone/pull/9369),[#9370](https://github.com/keystonejs/keystone/pull/9370),[#9371](https://github.com/keystonejs/keystone/pull/9371),[#9372](https://github.com/keystonejs/keystone/pull/9372),[#9368](https://github.com/keystonejs/keystone/pull/9368),[#9365](https://github.com/keystonejs/keystone/pull/9365),[#9366](https://github.com/keystonejs/keystone/pull/9366),[#9367](https://github.com/keystonejs/keystone/pull/9367),[#9331](https://github.com/keystonejs/keystone/pull/9331),[#9356](https://github.com/keystonejs/keystone/pull/9356),[#9353](https://github.com/keystonejs/keystone/pull/9353),[#9355](https://github.com/keystonejs/keystone/pull/9355),[#9354](https://github.com/keystonejs/keystone/pull/9354),[#9351](https://github.com/keystonejs/keystone/pull/9351),[#9352](https://github.com/keystonejs/keystone/pull/9352),[#9346](https://github.com/keystonejs/keystone/pull/9346),[#9345](https://github.com/keystonejs/keystone/pull/9345),[#9343](https://github.com/keystonejs/keystone/pull/9343),[#9341](https://github.com/keystonejs/keystone/pull/9341),[#9342](https://github.com/keystonejs/keystone/pull/9342),[#9226](https://github.com/keystonejs/keystone/pull/9226),[#9333](https://github.com/keystonejs/keystone/pull/9333),[#9325](https://github.com/keystonejs/keystone/pull/9325),[#9324](https://github.com/keystonejs/keystone/pull/9324),[#9322](https://github.com/keystonejs/keystone/pull/9322),[#9321](https://github.com/keystonejs/keystone/pull/9321),[#9319](https://github.com/keystonejs/keystone/pull/9319)) for changes not shown above, but none-the-less appreciated.

#### :eyes: Review
See https://github.com/keystonejs/keystone/compare/2024-08-28...2024-11-07 to compare with our previous release.

### CODE REVIEW

**Comment by iamandrewluca** [comment]
@dcousens can you also release a new version of `create-keystone-app`?

**Comment by dcousens** [comment]
@iamandrewluca what would the changeset say?

**Comment by iamandrewluca** [comment]
The only changes in `create` I see, is this PR https://github.com/keystonejs/keystone/pull/9327

**Comment by dcousens** [comment]
@iamandrewluca I will merge this on the morrow

**Comment by iamandrewluca** [comment]
Btw, the link to the Review section of this PR description seems to be invalid. That link it does not show any diff

> See https://github.com/keystonejs/keystone/compare/2024-08-28...2024-11-05 to compare with our previous release.

**Comment by dcousens** [comment]
@iamandrewluca the pull request description is the draft for the GitHub release that will be published after this is merged.

The merge commit will be tagged with the merge date, `2024-11-06`, and used as the tag for the GitHub release.  That is when the link will be up.

**Pull request merged**
