### PR TITLE
bugfix(types.html): add check if remove function exists

### PR DESCRIPTION
**Pull request by pavethiran**
## Description of changes
Added check for remove function

## Related issues (if any)
#3844 

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by jstockwin** [comment]
@pavethiran the build is failing due to a linting error. You've got a `!=` instead of a `!==`. You should be able to check the linting by running `eslint .`. Would you mind fixing that? Thanks!

**Comment by bassjacob** [comment]
Looking at the tinymce docs `remove` should always exist, no? What are the circumstances where `remove` is no longer a function/how can we reproduce this?

**Comment by pavethiran** [comment]
@bassjacob To reproduce, just make a List containing a "Types.Html"-field.

This is the setting from my List.
```javascript
embed: {
  type: Types.Html,
  wysiwyg: true,
  required: false,
  initial: false,
  dependsOn: {
    'fullscreen.type': 'embed'
  }
},
```

**Comment by JedWatson** [comment]
@pavelvlasov I can't replicate this using latest keystone linked to the [`keystone-test-project`](https://github.com/keystonejs/keystone-test-project)

Can you provide some more info? I added a `dependsOn` setting to the second `HTML` field (`content.extended`) in the `Post` model, and adding / removing editors worked just fine.

Tested on Safari Version 10.0.2 (macOS Sierra) with the same version of TinyMCE included by default in Keystone's Admin

**Comment by bassjacob** [comment]
@pavethiran I think github completed the wrong username in Jed's message. Are you able to provide some more info for the context of this PR, we aren't able to reproduce the error. A project with the error occurring would be the best example if possible.

**Pull request closed without merging**
