### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by dcousens**
The following packages have been updated
```
@keystone-6/auth@7.0.3
@keystone-6/core@5.8.0
```

#### New Features
- `[core]` Adds `{field}.hooks.validate.[create|update|delete]` hooks, deprecates `validateInput` and `validateDelete` (throws if incompatible) (#9057) @dcousens
- `[core]` Adds `{list}.hooks.validate.[create|update|delete]` hooks, deprecates `validateInput` and `validateDelete` (#9056) @dcousens
- `[core]` Add `async` to `extendHttpServer`, to support `await` on startup (#9026) @dcousens

#### Bug Fixes
- `[auth]` Fix `createInitial*` and `send*MagicAuthLink` to throw if the expected type from `sessionStrategy.start` is not a string (#9018) @dcousens
- `[core]` Use `db.idField` of `{ kind: 'number', kind: 'Int' }` internally for singletons (#9027) @dcousens
- `[core]` Fixes the `text` field type to accept a `defaultValue` of `null` (#9057) @dcousens
- `[core]` Fix `image` field type to use consistent sub-field ordering (#9017) @dcousens
- `[core]` Fix `config.server.cors` type preventing value of `false` (#9026) @dcousens
- `[core]` Fix `defaultIsFilterable` and `defaultIsOrderable` types preventing value of `true` (#8809) @dcousens
- `[core]` Fix global locking by dropping global `p-limit` on `context.query`/`context.db` (#8809) @dcousens
- `[core]` Deprecates `extendHttpServer`'s `graphqlSchema` argument, use `context.graphql.schema` instead (#9028) @dcousens
- `[core]` Fix static relationship resolution errors to conform to nominal error structure (#9042) @dcousens
- `[core]` Fixes `createExpressApp` to use `context.graphql.schema`, not the GraphQLSchema argument (#9029) @dcousens
- `[core]` Deprecates `ExtendGraphQLSchema` type, use type `(schema: GraphQLSchema) => GraphQLSchema` instead (#9029) @dcousens

#### :seedling: New Contributors
Thanks to the following developers for making their first contributions to the project!
- @dagrinchi ([#9039](https://github.com/keystonejs/keystone/pull/9039))
- @Grumaks ([#9064](https://github.com/keystonejs/keystone/pull/9064),[#9063](https://github.com/keystonejs/keystone/pull/9063))
- @PaulAroo ([#9025](https://github.com/keystonejs/keystone/pull/9025),[#9019](https://github.com/keystonejs/keystone/pull/9019))

#### :blue_heart: Acknowledgements 
Lastly, thanks to @dcousens ([#9071](https://github.com/keystonejs/keystone/pull/9071),[#9071](https://github.com/keystonejs/keystone/pull/9071),[#9071](https://github.com/keystonejs/keystone/pull/9071),[#9071](https://github.com/keystonejs/keystone/pull/9071),[#9068](https://github.com/keystonejs/keystone/pull/9068),[#9055](https://github.com/keystonejs/keystone/pull/9055),[#9053](https://github.com/keystonejs/keystone/pull/9053),[#9048](https://github.com/keystonejs/keystone/pull/9048),[#9043](https://github.com/keystonejs/keystone/pull/9043),[#9034](https://github.com/keystonejs/keystone/pull/9034),[#9033](https://github.com/keystonejs/keystone/pull/9033),[#9032](https://github.com/keystonejs/keystone/pull/9032),[#9015](https://github.com/keystonejs/keystone/pull/9015),[#9016](https://github.com/keystonejs/keystone/pull/9016),[#9012](https://github.com/keystonejs/keystone/pull/9012),[#9011](https://github.com/keystonejs/keystone/pull/9011)), @molomby ([#9047](https://github.com/keystonejs/keystone/pull/9047)), @renovate ([#9060](https://github.com/keystonejs/keystone/pull/9060),[#9059](https://github.com/keystonejs/keystone/pull/9059),[#9065](https://github.com/keystonejs/keystone/pull/9065),[#9044](https://github.com/keystonejs/keystone/pull/9044),[#9045](https://github.com/keystonejs/keystone/pull/9045),[#9050](https://github.com/keystonejs/keystone/pull/9050),[#9040](https://github.com/keystonejs/keystone/pull/9040),[#9031](https://github.com/keystonejs/keystone/pull/9031),[#9030](https://github.com/keystonejs/keystone/pull/9030),[#9024](https://github.com/keystonejs/keystone/pull/9024),[#9021](https://github.com/keystonejs/keystone/pull/9021),[#9020](https://github.com/keystonejs/keystone/pull/9020),[#9022](https://github.com/keystonejs/keystone/pull/9022),[#8952](https://github.com/keystonejs/keystone/pull/8952)) for changes not shown above, but none-the-less appreciated.

#### :eyes: Review
See https://github.com/keystonejs/keystone/compare/2024-02-07...2024-03-28 to compare with our previous release.

### CODE REVIEW

**Comment by dcousens** [comment]
This will be :green_circle: to merge next Tuesday, hopefully alleviating potential any headaches for the weekend :rabbit2:

**Comment by dcousens** [comment]
- Fix issues
- Add https://github.com/keystonejs/keystone/pull/9039 fix

**Comment by borisno2** [comment]
Howdy @dcousens
It doesn't look like this PR bumped the version numbers, so there was no release to npm https://www.npmjs.com/package/@keystone-6/core 😢

**Comment by PaulAroo** [comment]
@dcousens 👀

**Comment by dcousens** [comment]
@borisno2 huh, I think I'll review that CI action, as I didn't manually run ` pnpm changeset version`, which is the difference between this and the snapshot CI action.

Rather than `git` shenanigans, I will update the publish workflow in a different pull request.

**Pull request merged**
