### PR TITLE
Exception with the JSON download & Fix

### PR DESCRIPTION
**Pull request by export-mike**
Hi!

Firstly can I say going through this codebase is a joy, I've known of keystone for awhile and tinkered with it in my spare time - its great to see how its evolved. 

I found that this was throwing an exception when you click to download data as json.

you can reproduce the bug at http://demo.keystonejs.com/keystone/posts download > json > download

the server hangs with no response... 

this fixes the issue, the flow is now similar with the CSV download. Which is where I pinched the 'list-to-array' require from. Its now fixed for this scenario.

A few other points I have noted for discussion:
- Do we also want it to be a json file download or json response?
- we should probably also have an exception handler to return 500 from express for anything else?
- I notice the user can enter "password" into the query string and reveal the hash, is this expected behaviour? I assume its safe under a users logged in session
- I've noticed the require for 'baby-parse' is within the handler? do we want to hang the server on request? https://github.com/keystonejs/keystone/blob/master/admin/server/api/list/download.js#L9

If you're after any more help on issues or more info on this bug, I'd be more than happy to help! 

Thanks 

Mike

## Description of changes

I've added the missing check for "is a string" if so then convert to an array which done by the third-party dependency 'list-to-array'.

## Testing

a note: I got this selenium error before I made changes on the branch, this has actually prevented me from getting the selenium tests to pass. 

```Timed out while waiting for element <.primary-navbar [data-section-label="octicon-sign-out"]> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
    at Object.after (/Users/MikeJames/projects/keystone-play/keystone/test/e2e/adminUI/tests/group006Fields/commonFieldTestUtils.js:13:22)
```

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by JedWatson** [comment]
Nice, thanks @export-mike!

Going to merge this fix as-is, but to answer your questions:

> Do we also want it to be a json file download or json response?

We should be setting the content type header to `application/json`, yes

> we should probably also have an exception handler to return 500 from express for anything else

I think we have a generic 500 handler in keystone by default..? honestly, that's a broader area we should review. The route for the download should call `next(err)` if it gets an error.

> I notice the user can enter "password" into the query string and reveal the hash, is this expected behaviour? I assume its safe under a users logged in session

This has actually been fixed, see the [PasswordType](https://github.com/keystonejs/keystone/blob/master/fields/types/password/PasswordType.js#L127-L129) implementation - we need to update the demo to the latest version

> I've noticed the require for 'baby-parse' is within the handler? do we want to hang the server on request?

It's a trade-off to speed up the time to initial boot for the application, we do a fair bit of this deferred require for heavier packages. It's not ideal - it either blocks the first time a json download is requested, or every time keystone starts, we've optimised to speed up the initialisation.

> If you're after any more help on issues or more info on this bug, I'd be more than happy to help!

... yes please, help with any of the outstanding issues (or testing / bugs you can find) would be fantastic 😀

**Comment by JedWatson** [comment]
@webteckie @jstockwin can either of you help out with the testing issue @export-mike ran into?

> a note: I got this selenium error before I made changes on the branch, this has actually prevented me from getting the selenium tests to pass.

**Comment by jstockwin** [comment]
@export-mike We'll probably need a few more details. Do you have a longer snippet of that error? There should be more info than that. Also your operating system and browser. I assume the problem is still there on current master?

**Comment by export-mike** [comment]
@jstockwin 
```npm run test-e2e```
On further inspection it appears to be losing connection to mongo. I installed mongo via homebrew and not touched any configuration for it, so its got to be something my end. I am however running this on a beaten up old mac I have been carrying around...

```
✖ Expected element <.EditForm-container .field-type-datearray[for="fieldB"] .FormField:nth-of-type(2) input[type="text"]> to be visible - element was not found  - expected "visible" but got: "not found"
    at Array.forEach (native)
    at Array.forEach (native)
    at Object.DateArray field should show correctly in the edit form (/Users/MikeJames/projects/keystone-play/keystone/test/e2e/adminUI/tests/group006Fields/testDateArrayField.js:102:29)


FAILED:  1 assertions failed and 24 passed (1m 2s / 62077ms)
 ✖ Timed out while waiting for element <.primary-navbar [data-section-label="octicon-sign-out"]> to be present for 60000 milliseconds.  - expected "visible" but got: "not found"
    at Object.after (/Users/MikeJames/projects/keystone-play/keystone/test/e2e/adminUI/tests/group006Fields/commonFieldTestUtils.js:13:22)

------------------------------------------------
Mongoose connection "error" event fired with:
Error: connection timeout
    at Db.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
Error: connection timeout
    at Db.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/MikeJames/projects/keystone-play/keystone/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/MikeJames/.nvm/versions/node/v6.9.4/bin/node" "/Users/MikeJames/.nvm/versions/node/v6.9.4/bin/npm" "run" "test-e2e"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! keystone@4.0.0-beta.5 test-e2e: `node test/e2e/server.js --env default`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keystone@4.0.0-beta.5 test-e2e script 'node test/e2e/server.js --env default'.
```

**Comment by export-mike** [comment]
@JedWatson 

> I think we have a generic 500 handler in keystone by default..? honestly, that's a broader area we should review. The route for the download should call next(err) if it gets an error.

I found this was actually not responding to the client, it was as if a callback wasn't being called, I'll investigate further. 

> I've noticed the require for 'baby-parse' is within the handler? do we want to hang the server on request?

I see thats an interesting performance method! I haven't seen/heard of this before, it makes total sense.

**Pull request merged**
