### PR TITLE
Remove legacy auth-passport

### PR DESCRIPTION
**Pull request by timleslie**
See #5025 

Note this package now lives over in [keystonejs/keystone-5](https://github.com/keystonejs/keystone-5)

### CODE REVIEW

**Comment by gautamsi** [comment]
How do we plan to add this (passport login) back in next?

**Comment by timleslie** [comment]
> How do we plan to add this (passport login) back in next?

That's something that's on our design backlog at the moment. We don't have a concrete answer for this just yet.

**Comment by gautamsi** [comment]
if you have any crude thought, I can spend some time on this to create initial PR

**Comment by timleslie** [comment]
> if you have any crude thought, I can spend some time on this to create initial PR

We're not at that stage yet, this feature is a not ready for any kind of development work yet.

**Comment by JedWatson** [comment]
It's off topic for this PR but since you asked @gautamsi 

I really like the way Redwood presents their roadmap: https://redwoodjs.com/roadmap

And I think this format is something we'll adopt, so it's easier to follow along where different things are at in the process from "needs design" 🤔 to "help please" 🙂

**Review by JedWatson — APPROVED** [review]

**Pull request merged**
