### PR TITLE
Move auth strategy setup and management to list level

### PR DESCRIPTION
**Pull request by Vultraz**
~Implements option 1 from #2004 (doesn't key the strategies by custom name yet). Also adds the three hooks requested in #2001 (no `session` argument passed to `beforeUnauth`, though).~

Implements option 2 from #2004 (auth strats keyed by name).

~Only difference from the suggested implementation is I pass the list with your desired auth directly to the Admin UI app instead of just the key.~
```js
const authList = keystone.createList('User', {
  fields: {
    name: { type: Text },
    email: { type: Text, isUnique: true },
    isAdmin: { type: Checkbox },
    password: { type: Password },
  },
  authStrategies: {
    password: {
      type: PasswordAuthStrategy,
    },
  },
});

module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new AdminUIApp({ enableDefaultRoute: true, authStrategy: 'User.password' }),
  ],
};
```

Lemme know if I got the patch levels right (does this count as a major version bump due to API changes?)

@molomby / @timleslie

### CODE REVIEW

**Comment by Vultraz** [comment]
Which format is preferred?
js
```
  authStrategies: [
    { type: PasswordAuthStrategy }
  ],
```
or
```
  authStrategies: [
    new PasswordAuthStrategy()
  ],
```
I was thinking the latter is more consistent with how other classes (adapters, etc) are used. What do you think?

**Comment by molomby** [comment]
Hey @Vultraz thanks for the PR. We've haven't really finished the design process on either of those issues though so implementation might be a bit premature...

* #2001 is waiting on feedback on the API design. The current design is being documented; I'll push the branch in a bit
* #2004 is has open questions too; I'm leaning towards the second "named" variation personally
* It would be nice to keep these issues separate for smaller PRs; there's no reason to batch them. Likewise, the changes to `KeystoneLogo.js` etc. should be PR'd separately.

Regardless, we'll try to use these changes as a basis for the code updates.

**Comment by Vultraz** [comment]
The KeystoneLogo change has already been merged separately. I'll rebase it out.

**Comment by Vultraz** [comment]
Anything new on this?

**Comment by MaciejPara** [comment]
@Vultraz  +1

**Comment by Vultraz** [comment]
@timleslie @molomby Revisiting this in light of the recent provider changes. Now it used the keyed-by-strategy-name version, and I tossed the hooks stuff since that should be done separately.

**Comment by Vultraz** [comment]
Rebased and resolved conflicts.

**Comment by Vultraz** [comment]
Fixed conflicts.

**Comment by timleslie** [comment]
I'm having a look through this at the moment. I'm not ready to merge this yet, but there are some changes in here which I'd like to isolate and merge separately to the major changes. Hopefully handling the easier parts of this will give me the clarity to make a decision on the major parts 👍

**Comment by gautamsi** [comment]
is this going to see light?

**Comment by Vultraz** [comment]
Hopefully. I'm just waiting to see what tim decides with this.

**Comment by Vultraz** [comment]
@timleslie anything new for this?

**Comment by molomby** [comment]
Sorry @Vultraz, this PR might be no longer relevant.

We're currently working on some larger changes that will repackage auth in a way that solve these ^^ problems and also decouple a auth from the core Keystone classes. This'll make the auth system more flexible for solution devs but also lets us be more opinionated with our "out of the box" tooling. In addition, it'll allow auth packages to contribute pages, routes, etc. to the Admin UI, allowing interfaces and process for things like forgotten password, magic links, social auth, etc. (with out of the box implementations of that stuff too).

**Comment by timleslie** [comment]
As per @molomby's comments above, this line of development is no longer relevant for [`keystone-next`](https://next.keystonejs.com/apis/auth).

**Pull request closed without merging**
