### PR TITLE
Implements parseFormat and parseStrict options

### PR DESCRIPTION
**Pull request by ttsirkia**
This pull request adds two new options for `DateType` and `DatetimeType`. The new options are `parseFormat` and `parseStrict`.

With these options, user can define a custom input format for dates. If `parseStrict`is used, only the given format will be used, otherwise the default options are also used. If `parseFormat`is given without `parseStrict`, the given format will be tried before the default formats.

The format can be a comma-separated string or an array of strings.

Because the Admin UI doesn't know anything about these new options, `parseStrict` should be not be used if the Admin UI is in use. For this reason, `parseStrict` defaults to false.

Implements #1156

### CODE REVIEW

**Comment by ttsirkia** [comment]
It would be highly appriciated to get this accepted. I'd like to avoid this kind of lines before using `UpdateHandler`:

```javascript
req.body.arrivalTime = moment(req.body.arrivalDate, 'D.M.YYYY H:mm');
req.body.arrivalTime = req.body.arrivalTime.isValid() ? req.body.arrivalTime.format('YYYY-MM-DD H:mm') : null;
```

**Comment by ttsirkia** [comment]
@JedWatson any thoughts?

**Comment by ttsirkia** [comment]
Implemented in ee26dbf, closing this.

**Comment by dcousens** [comment]
Thanks @ttsirkia,  could you may resubmit your documentation fixes and tag me?  There is still some useful code here :)

**Pull request closed without merging**
