### PR TITLE
Doc updates and minor functionality improvements for file field/adapters

### PR DESCRIPTION
**Pull request by Vultraz**
EDIT: Summary of current changes:
* `fileAdapter` is now properly treated as mandatory in File fields.
* `src` is now mandatory for `LocalFileAdapter`.
*  `path` now defaults to `src` if not provided for `LocalFileAdapter`.
* Improved documentation for both file adapters and the File field.
* Fixed this warning:
```
DeprecationWarning: File upload property ‘stream’ is deprecated. Use ‘createReadStream()’ instead.
```

### CODE REVIEW

**Comment by MadeByMike** [comment]
@Vultraz `path` is the public url used to retrieve the image and `src` is the location to upload the file. 

Although they will often match with a static server, they can differ. For example you might have a path configured on your webserver to resolve files from the root `/photo.jpg` even though the source is `/uploads/images/photo.jpg` 

Perhaps you can suggest different names? I'm open to that if it's clearer. Although we should do so in a way that `path` and `src` continue to work.

You are correct in assuming that an adapter is required and maybe this should be enforced with code. I'm also open to PRs on this.

**Comment by Vultraz** [comment]
What about `uploadTo` and `serveFrom`?

**Comment by MadeByMike** [comment]
> What about `uploadTo` and `serveFrom`?

Maybe `uploadDir` and `publicPath` /shrug

**Comment by Vultraz** [comment]
I noticed those keys were actually renamed recently, so I think I'll leave them be.

Anyway, I added a few non-doc commits (made `adapter` mandatory, fixed a deprecation warning).

**Comment by Vultraz** [comment]
Ok why are these tests not running...

**Comment by Vultraz** [comment]
Ok, I've dropped the general prettier commit since this does need some review. Updated the first post with a summary of changes.

**Comment by MadeByMike** [comment]
We can merge these changesets - you only need one

**Comment by Vultraz** [comment]
One changeset it is!

**Pull request merged**
