### PR TITLE
add back Promise since some OS cannot find the native Promise

### PR DESCRIPTION
**Pull request by gemscng**
I am not sure if others encounter this problem. We do not have problem in MacOS but it fail to find Promise in Ubuntu.

### CODE REVIEW

**Comment by JedWatson** [comment]
This is a good fix for that problem, @gemscng.

Before we merge though, could you confirm which version(s) of node you are using? As far as I know, Promise has been natively available since 0.12

**Comment by gemscng** [comment]
node -e 'console.log(process.versions.v8);'
3.28.71.19

**Comment by JedWatson** [comment]
Thanks for that @gemscng. I'd love to know why this is happening, but this is a clean + safe workaround anyway so I'm happy to merge.

**Comment by yoshuawuyts** [comment]
`Promise` should be available on `Node>=0.12` on Ubuntu:

screen shot 2016-04-23 at 12 25 57

Could you perhaps verify you're not running any odd flags when starting Node / try running:
```js
console.log(process.version)
```
Cheers!

**Comment by gemscng** [comment]
Thanks @yoshuawuyts  for the tips. I found out the problem. I think @JedWatson is safe to reverse this commit. 
There are 2 version of node in the system. one from nvm and one in /usr/bin.
But anyway, it is solved even without this commit after i upgrade /usr/bin to 0.12.

It is wired that when i run "node -v" command, it return 0.12.7 from nvm. 
But when i start the node using "NODE_ENV=dev,android,cms node keystone.js",  it use back the node in /usr/bin. 
Any hint's @yoshuawuyts ?

**Pull request merged**
