### PR TITLE
Update node version to 22

### PR DESCRIPTION
**Pull request by gautamsi**

### CODE REVIEW

**Comment by dcousens** [comment]
Can you update the `examples/*/sandbox.config.json` files too?

**Comment by gautamsi** [comment]
@dcousens have update version in sandbox but it seems codesandbox does not like this version, may have to change some config for supporting this nodejs version for codesandbox

**Comment by dcousens** [comment]
@gautamsi what issue presents?

**Comment by gautamsi** [comment]
see https://ci.codesandbox.io/status/keystonejs/keystone/pr/9417/builds/568305

`Error: Invalid node version "22"`

**Comment by dcousens** [comment]
Following up in https://github.com/codesandbox/codesandbox-client/issues/5865#issuecomment-2526389404

**Pull request merged**
