### PR TITLE
[v0.3] Change the color of the navbar in the admin

### PR DESCRIPTION
**Pull request by dam1**
Very simple setting, but useful to know which env you are working on.

in keystone config

`keystone.init({'admin color': '#009933', ... `

related #1255

### CODE REVIEW

**Comment by creynders** [comment]
:+1:

**Comment by webteckie** [comment]
Wouldn't it better to support #2242 so that other customization is possible?

**Comment by creynders** [comment]
@webteckie sure, but this is a PR and the other seems to involve a lot more work. But obviously it would be great if you could come up with a backwards compatible solution, i.e. small change here makes it compatible with what you have in mind in #2242

**Comment by webteckie** [comment]
@creynders I may be missing something here but at dont see the value of this small tweak at the expense of another keystone config.  Am I missing something?

**Comment by mxstbr** [comment]
Agreed @webteckie, I don't think this is necessary. Lets wait for #2242 instead of adding a global config var.

**Comment by mxstbr** [comment]
We decided to go with #2462, which allows you to change everything.

Thanks so much for contributing, we really appreciate it!

**Pull request closed without merging**
