### PR TITLE
[WIP] Refactor content field impl to work with slate 0.50 and up

### PR DESCRIPTION
**Pull request by Vultraz**
~~Very very WIP! Don't do anything with this yet.~~
Still WIP but coming together.

### CODE REVIEW

**Comment by Vultraz** [comment]
@jesstelford I'm confused as to how images are supposed to be stored when using the plain `image-container`/`image` block. Do they get saved separately in the DB? Uploaded to local filesystem?

**Comment by Vultraz** [comment]
@jesstelford is the content field supposed to create a new aux list entry every time you save? 🤔 Or did I introduce a regression.

**Comment by acoreyj** [comment]
Still working on this?

**Comment by Vultraz** [comment]
I had set it aside for a while, but I can definitely pick it back up soon.

**Comment by jesstelford** [comment]
> is the content field supposed to create a new aux list entry every time you save?

Yeah, it does. Ideally it wouldn't, but I never got around to finishing that part.

It does a `disconnectAll` & a `connect` which leaves the old row as a dangling reference.

**Comment by Vultraz** [comment]
Oof 😬 Ok, so I didn't break that.

I actually think this was mostly finished. There were some bad block behaviors (especially normalizations) I needed to sort out, but the field was functional. Pre-0.5x documents could be loaded fine and are converted to the new format automatically. There were also some design changes I made based on the Slate demos (such as being able to drag in images) that did need some review, but overall I'd say this was 90% done.

**Comment by Vultraz** [comment]
Marking this as ready for review. Still WIP (rough edges to work out), but it's mostly functional and I could definitely use some feedback.

**Comment by Vultraz** [comment]
Oof. These test failures make no sense 🤔

**Comment by JedWatson** [comment]
Closing this because we're working on a new Document field built on the latest Slate version, which will supersede the Content field in the future. For now we'll leave the Content field on the version of Slate that's working, and come up with a transition-forward strategy for people to upgrade down the track.

Just wanted to say thanks for all your work on it @Vultraz and sorry it didn't end up landing!

**Pull request closed without merging**
