### PR TITLE
fix for the error when deleting items #1904

### PR DESCRIPTION
**Pull request by thomasjonas**
Fix for deleting one or multiple items for issue #1904.

### CODE REVIEW

**Comment by JedWatson** [comment]
Right, thanks @thomasjonas!

**Comment by morenoh149** [comment]
@thomasjonas does this PR close #1904 ?

**Comment by ericelliott** [comment]
Are there unit tests for `.deleteItems()`?

**Comment by thomasjonas** [comment]
@ericelliott I don't think so. At least I couldn't find any. I actually couldn't find any tests for /admin/client/lib/List.js and I'm also not sure on how to implement them.

**Pull request merged**
