### PR TITLE
Add object array type

### PR DESCRIPTION
**Pull request by sendyhalim**
Add object array type, allows to define model property like this:

```
  customers: {
    type: Types.ObjectArray,
    parts: {
      first_name: { label: 'First Name' },
      last_name: { label: 'Last Name' },
      phone: { label: 'Phone Number },
      address: { label: 'Address' }
    },
    itemLabel: 'Customer'
  }
```
- `itemLabel` is label for each item in `customers`
- `label` is label for each property of `customer`

### CODE REVIEW

**Comment by milosdakic** [comment]
+1

**Comment by milosdakic** [comment]
@sendyhalim this is exactly what I was after!

Do the individual parts still have the ability to use the Keystone types? Would love to be able to set a part that requires a particular type.

**Comment by sendyhalim** [comment]
@milosdakic No currently it  assumes you want it to be string `<input type="text">`, if I have time on the weekend, I will make it to conform the given type.

**Comment by JedWatson** [comment]
This is great, thanks @sendyhalim. I appreciate how light-weight the solution is for a first round, and that you've added tests :+1: 

Different input types were the first thing I though of too, I've been thinking on how we can nest real Keystone field types but that's a larger solution and I think I'd be happy to add this so there's at least _something_ in place while we're working on other prerequisites.

I think that we should be able to offer an easy upgrade path too, because the stored data in mongo would remain the same if you turned a `string` part into a `Types.Text` field.

Would love to see what else you can up with for different data types for parts though, if you get time!

**Comment by sendyhalim** [comment]
@JedWatson I haven't found any good solution to nest real keystone field types, so I think the simplest approach (for now) is to add type option (should be string) and do a switch statements based on `type` value.

```
  customers: {
    type: Types.ObjectArray,
    parts: {
      first_name: { label: 'First Name'}, // defaults to text
      last_name: { label: 'Last Name', type: 'text' },
      phone: { label: 'Phone Number, type: 'text' },
      address: { label: 'Address', type: 'textarea' }
    },
    itemLabel: 'Customer'
  }
```

supported types: 
- number
- text
- email
- date
- datetime
- hidden
- url
- password
- color
- month
- week
- textarea

**Comment by SlashmanX** [comment]
Any updates on this? Works really well for me, would love to see it merged, if even only temporarily

**Comment by NatsumiHoshino** [comment]
Any updates? I've been checking back every once in a while and this PR seems to have been forgotten.

**Comment by morenoh149** [comment]
@sendyhalim could you rebase onto master. Sorry the PR hasn't been merged yet.

**Comment by sendyhalim** [comment]
@morenoh149 sure, I will try to rebase it to master.

**Comment by sendyhalim** [comment]
Anyway, let met try it manually first, to make sure it works after the rebase.

**Comment by sendyhalim** [comment]
I just realized that the master branch is not stable yet and it's hard to test it manually, should I re-submit the pull request to branch 0.3.x? @morenoh149?

**Comment by SlashmanX** [comment]
I've added a slight adjustment to this which allows displaying this field as a column in the list view. If this is needed I can submit a PR after (if it is) it's merged

**Comment by morenoh149** [comment]
@sendyhalim not sure. Perhaps you should wait till master settles down.

**Comment by sendyhalim** [comment]
@morenoh149 anw I just tested it on branch `v0.3.x`, it works fine.

**Comment by aaroncalderon** [comment]
I hope this feature gets applied soon. So close...

**Comment by JedWatson** [comment]
We've been implementing this in #3282 which is planned to be merged for the 4.0 final release, so I'm going to close this now. Thanks for the original implementation @sendyhalim

**Comment by sendyhalim** [comment]
@JedWatson Cool! You're welcome :beers:

**Pull request closed without merging**
