### PR TITLE
Add graphql.schemaPath configuration

### PR DESCRIPTION
**Pull request by marekryb**
This pull requests adds two new configuration options:
- `graphql.schemaPath`
Allows you to define path of generated GraphQL schema (default: `schema.graphql`)
Motivation:
Quite commonly I create custom mutations through `extendGraphqlSchema` because I need to use transaction over multiple tables and/or increment/decrement counter. In these situations, I would like to completely disable some operations through `graphql: { omit: { create: true, update: true } }` on these lists, but for sake of having Admin UI working, I cannot do this. This sometimes causes confusion among fellow developer(s) or a 3rd party as they start using some mutations that are not intended to be ever used and later they have to change it over.
In all recent projects I am using keystone as a route in nextjs (as in examples/framework-nextjs-*-directory) so I do not need Admin UI in production. In development however, Admin UI is commonly preferred over direct database access.  So what I actually need is to have two GraphQL schemas: one used inside nextjs (no AdminUI) and one for standalone server (with AdminUI).

~~- `graphql.excludeKeystoneMeta`
Allows you to exclude `keystone: KeystoneMeta!` query from the GraphQL API that is used by the Admin UI. 
This is seems reasonable in cases where AdminUI is disabled (either through `ui.isDisabled: true` or because using it within framework like nextjs). Initially I was thinking to use `ui.isDisabled` as a condition for dropping the query rather than new config option, but this would be breaking change with no way to opt-out.~~

### CODE REVIEW

**Comment by dcousens** [comment]
@marekryb this is awesome!

For `graphql.excludeKeystoneMeta`, I am happy to make that drop with `ui.isDisabled`, as we are already on a breaking change merge cycle - but I guess my question is, how problematic are the set of currently merged breaking changes for you.

**Comment by marekryb** [comment]
@dcousens Okay. I removed excludeMetaSchema and tied it to ui.isDisabled. Many tests are failing, but I am pretty sure it is not because of this PR.

I looked briefly at recent PRs and see no problem. https://github.com/keystonejs/keystone/pull/8765/commits/268d70386c138b93048dd6c86fd7604fb56efe04 removes meta from sudo() which is fine. This PR goes further and removes it also from the final client schema.

I am confused though about what is happening in the repo. Eg. PR https://github.com/keystonejs/keystone/pull/8767 which was supposedly merged to main in https://github.com/keystonejs/keystone/commit/a04d66d48880e39f5495a134d95d1934a036ecf7, but it says `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` and I cannot see it on the main branch. WTH? I noticed this one specifically because it fixes test in a file that I am also modifying.

**Comment by dcousens** [comment]
@marekryb thinking about this, for future major version updates, we'll endeavor to merge major pull requests to a separate branch that will be rebase merged moments prior to release.

This should set us up for a minimal amount of git work while leveraging the same pull request workflows we use now.

**Comment by marekryb** [comment]
@dcousens Ok, thank you for explaining. Separate branch seems more natural indeed.
Let me know when/if I need to rebase or do some other work on this PR.

**Comment by dcousens** [comment]
@marekryb we have reset the `main` branch to the tag `2023-08-15` and moved all of the existing breaking changes into a new branch, please see https://github.com/keystonejs/keystone/pull/877

**Comment by dcousens** [comment]
@marekryb we have removed any references to the `excludeKeystoneMeta` and `ui.isDisabled` changes from this pull request, and are going to merge them with our other changes in an upcoming pull request.

We will ensure to add your name as the following on the merge and commit messages for that upcoming pull request, as we will be using your commits and idea :yellow_heart: 
```
    Co-authored-by: Marek Rybczynski <marek.rybczyn@gmail.com>
```

**Review by dcousens — APPROVED** [review]

**Pull request merged**
