### PR TITLE
WIP: Introducing Modal component into EditForm

### PR DESCRIPTION
**Pull request by adnasa**
# WIP and needs a review

Since I'm not fully aware/sure about the roadmap of this project, I decided to just code and get carried away and see where it takes me.

What I did, was effectively remove the __confirm__ action that was triggered when a user chooses to reset/delete the post in the `EditForm` component. I introduced the Modal component to enhance that experience.

--- 

### Changes

- the state tree has been amended with a `modal` state sub.
- `handleReset` sets the state of the form's modal component to display the modal. a `meta` is followed in the modal state to later detemine which action to take when a user confirms. Same thing for `handleDelete`
- `handleDeleteAction`/`handleResetAction` is the action to take when a user confirms through the modal.

----

### Methods introduced in the EditForm component

- handleResetAction
- handleDeleteAction
- closeModal
- renderModalButtons

---

### TODO (later)

- [ ] Display a __flash message__ once an action is failed (e.g deleteItem can cause a form error)

---

### SS

img

--- 

Enjoy!

### CODE REVIEW

**Comment by adnasa** [comment]
Now there we go. build passed :bowtie:

**Comment by JedWatson** [comment]
@adnasa - thanks, this looks great! I'm about to go through the code more closely & will comment if necessary, but from your description + screenshot I'm really happy with it. One minor change is we'd use a text style button for the `cancel` and probably make the primary action a danger button but that's easy to do.

@jossmac do you want to give this a quick review as well?

**Comment by JedWatson** [comment]
Merged, @jossmac is going to clean up the styling a bit but otherwise looks good! thanks again @adnasa.

**Comment by adnasa** [comment]
oh.. @jossmac didn't have to do that. I should clean up my own mess :smile: 
thanks again!

**Comment by JedWatson** [comment]
@adnasa - don't worry, @jossmac sits next to me so it was easy for us to review it and figure out how / what we wanted changed. We can all get more done when we work together :grinning:

For reference do check out #1888, there is some good code in there that is worth being across, but also thanks for the great start on this! Feel free to grab something else you think needs doing next.

**Comment by JedWatson** [comment]
Oh actually - I just realised, I don't think we added support for error messages. Do you want to take a look at that @adnasa?

**Comment by adnasa** [comment]
@JedWatson yes I've thought about that as well. I will take a look at it some time this week. :+1:

**Pull request merged**
