### PR TITLE
Added Code type to database documentation

### LINKED ISSUE #1070: Need Docs: Code field type
I just realised the Code field is completely missing from the Database docs.

We need to add it, should be pretty simple, something along the lines of:

- Code field is a String path
- Uses CodeMirror for the editor UI
- Supports options `heigh` (default 180) and `language`
- Valid language options are
    - `c`
    - `c++`
    - `objectivec`
    - `css`
    - `asp`
    - `c`
    - `vb`
    - `xml`
    - `php`
    - `html`
    - `ini`
    - `js`
    - `java`
    - `coffee`
    - `lisp`
    - `perl`
    - `python`
    - `sql`
    - `json`
    - `less`
    - `sass`
    - `sh`
    - `ruby`
    - `jsp`
    - `tpl`
    - `jade`

### PR DESCRIPTION
**Pull request by jdr0dn3y**
Fixes #1070

### CODE REVIEW

**Comment by morenoh149** [comment]
👍

**Comment by JedWatson** [comment]
Great, thanks @jdr0dn3y

**Comment by damianoviscardi** [comment]
"Code" is missing in the left column summary

**Comment by morenoh149** [comment]
@damianoviscardi is this missing in the latest documentation on https://keystonejs.com/, https://github.com/keystonejs/keystonejs-site or somthing else?

**Comment by JedWatson** [comment]
Thanks for pointing that out @damianoviscardi, I just added it and it'll be published with the next release.

**Pull request merged**
