### PR TITLE
Fix: Cloudinary TinyMCE Uploads

### PR DESCRIPTION
**Pull request by andrewlinfoot**
For some reason the upload image plugin was removed causing the `'wysiwyg cloudinary images': true` to not work.

### CODE REVIEW

**Comment by andrewlinfoot** [comment]
@JedWatson I saw you added an In Progress label? Are you working on a new implementation of this?

**Comment by morenoh149** [comment]
the `in progress` labels are autogenerated by waffle.io (I believe) they don't mean much

**Comment by JedWatson** [comment]
@morenoh149 I wish I could figure out how to disable the waffle integration, we're not actively using it...

Thanks @andrewlinfoot, merging it now!

**Comment by LorbusChris** [comment]
@JedWatson https://github.com/waffleio/waffle.io/wiki/FAQs#delete-project

**Comment by morenoh149** [comment]
I deleted on my waffle.io account. Not sure if that actually removes it though.

**Pull request merged**
