### PR TITLE
Fix windows issues in view resolver

### PR DESCRIPTION
**Pull request by gautamsi**
Fixed issues with Windows due to view path resolving changes in #6414 

this is similar to fix in #4636

I would insist to release a fix soon, possibly club few more such issues without waiting for next release cycle

### CODE REVIEW

**Review by mitchellhamilton — CHANGES_REQUESTED** [review]
Could you explain how exactly it breaks, the paths are escaped, so it should work already?

**Comment by gautamsi** [comment]
Generated _app.ts Import comes back as `..\..\..\..\xxx\yyy`

**Comment by mitchellhamilton** [comment]
Okay, could you move the replace to `serializePathForImport`?

**Comment by gautamsi** [comment]
@mitchellhamilton Done

**Pull request merged**
