### PR TITLE
[WIP] JSON & Memory Database Adapters

### LINKED ISSUE #1177: Add a `json` database adapter
This will greatly simplify our demo projects and minimum getting started requirements.

The adapter can be "dumb" and just read/write disk on every adapter request. It's not meant for prod.

### PR DESCRIPTION
**Pull request by jesstelford**
Fixes #1177

Introduces 2 new database adapters:
- `@keystone-alpha/adapter-json`: A local `.json` file as the database storage engine
- `@keystone-alpha/adapter-memory`: An in-memory storage engine

## `@keystone-alpha/adapter-json`

```javascript
const { JSONAdapter } = require('@keystonejs/adapter-json');
const keystone = new Keystone({
  name: 'My Awesome Project',
  adapter: new JSONAdapter(),
});
// ...
keystone.connect('./database.json');
```

## `@keystone-alpha/adapter-memory`

```javascript
const { MemoryAdapter } = require('@keystonejs/adapter-memory');
const keystone = new Keystone({
  name: 'My Awesome Project',
  adapter: new MemoryAdapter(),
});
// ...
keystone.connect();
```

## TODO

Things left to do:

- [x] handling of `where` clauses
  - [x] Simple field clauses
  - [x] `AND` clauses
  - [x] `OR` clauses
  - [x] Nested relationship where clauses
  - [x] Support all field types
    - [x] `CalendarDay`
    - [x] `Checkbox`
    - [x] `CloudinaryImage`
    - [x] `Color`
    - [x] `DateTime`
    - [x] `Decimal`
    - [x] `File`
    - [x] `Float`
    - [x] `Integer`
    - [x] `OEmbed`
    - [x] `Password`
    - [x] `Relationship`
    - [x] `Select`
    - [x] `Slug`
    - [x] `Text`
    - [x] `Unsplash`
    - [x] `Url`
    - [x] `Uuid`
- [x] All of ☝️ but for the `Memory` adapter
- [ ] Tests
  - [ ] api-tests/uniqueness/unique.test.js
  - [ ] api-tests/queries/search.test.js
  - [ ] api-tests/queries/limits.test.js
  - [ ] packages/email/tests/index.test.js // Not sure if I need to fix this snap or if a local issue
- [ ] Relationship tests
  - [ ] api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  - [ ] api-tests/relationships/nested-mutations/two-way-backreference/to-one-required.test.js
  - [ ] api-tests/relationships/nested-mutations/create-and-connect-many.test.js
  - [ ] api-tests/relationships/nested-mutations/create-and-connect-singular.test.js
  - [ ] api-tests/relationships/nested-mutations/disconnect-many.test.js
  - [ ] api-tests/relationships/nested-mutations/connect-many.test.js
  - [ ] api-tests/relationships/nested-mutations/create-singular.test.js
  - [ ] api-tests/relationships/nested-mutations/create-many.test.js
  - [x] api-tests/relationships/nested-mutations/connect-singular.test.js
  - [x] api-tests/relationships/nested-mutations/disconnect-singular.test.js
  - [x] api-tests/relationships/nested-mutations/disconnect-all-many.test.js
  - [x] api-tests/relationships/nested-mutations/reconnect-many-to-one.test.js
  - [x] api-tests/relationships/nested-mutations/disconnect-all-singular.test.js
  - [ ] api-tests/relationships/crud/many-to-many.test.js
  - [ ] api-tests/relationships/crud/one-to-one.test.js
  - [x] api-tests/relationships/crud/one-to-many-one-sided.test.js
  - [ ] api-tests/relationships/crud/many-to-many-one-sided.test.js
  - [x] api-tests/relationships/crud/one-to-many.test.js
  - [ ] api-tests/relationships/crud-self-ref/many-to-many.test.js
  - [ ] api-tests/relationships/crud-self-ref/one-to-one.test.js
  - [x] api-tests/relationships/crud-self-ref/one-to-many-one-sided.test.js
  - [ ] api-tests/relationships/crud-self-ref/one-to-many.test.js
  - [ ] api-tests/relationships/filtering/filtering.test.js
  - [ ] api-tests/relationships/crud-self-ref/many-to-many-one-sided.test.js
  - [ ] api-tests/relationships/filtering/nested.test.js
  - [ ] api-tests/relationships/filtering/access-control.test.js
  - [ ] api-tests/queries/relationships.test.js

### CODE REVIEW

**Comment by mitchellhamilton** [comment]
I'm so hyped for this!!! 😍

**Comment by gautamsi** [comment]
> Switch all the demos, etc, to use the JSON adapter

please don't change all, switch only simple todo demo or fork it to use with this.

**Comment by jesstelford** [comment]
I'm thinking we want to add a step to the `create-keystone-app` which will ask what database adapter to use, that way everyone who is consuming demos is covered. For the demo codebases stored in the repo, I want to switch to JSON files on disk for ease of setup and debugging - my development workflow now involves a lot of back and forth in the demos and mongo.

**Comment by gautamsi** [comment]
Strong case to have nextjs like examples folder,  separate the demo with examples and use memory store for demos, let examples be more full.

What I mean is we copy current demos to examples folder and then use json adapter for current demos. When possible someone can update  `create-keystone-app` to use `--example` switch to load the examples from here.

**Comment by VinayaSathyanarayana** [comment]
Waiting for this

**Comment by timleslie** [comment]
Closing this PR as it is no longer part of the roadmap for [`keystone-next`](https://next.keystonejs.com/roadmap#streamlined-back-end-with-prisma)

**Pull request closed without merging**
