### PR TITLE
test(e2e): Add chromedriver package to allow running tests in chrome

### PR DESCRIPTION
**Pull request by jstockwin**
## Description of changes

cc @webteckie Can you test this locally when you get a chance. Works fine for me....
## Testing
- [ ] Please confirm `npm run test-all` ran successfully.

…without having to manually download drivers.

### CODE REVIEW

**Comment by webteckie** [comment]
@jstockwin all travis checks show green but no e2e test ran :-)

**Comment by jstockwin** [comment]
@webteckie - didn't think I'd touched Travis, but you should be able to run
tests on chrome locally.

**Comment by jstockwin** [comment]
No e2e ran as it's a PR from my fork

**Comment by webteckie** [comment]
@jstockwin can we check if it can run successfully in travis?

**Comment by jstockwin** [comment]
@webteckie yeah I'll push it, but it's literally nothing to do with Travis,
I've not touched Travis at all. Can you just check that the tests run in
chrome for you locally?

**Comment by jstockwin** [comment]
@webteckie I've pushed to keystonejs now, so there's a proper build [here](https://travis-ci.org/keystonejs/keystone/builds/163945234).

**Comment by JedWatson** [comment]
@jstockwin @webteckie what should we be doing with this?

**Comment by webteckie** [comment]
@JedWatson no clue...dont think I ever understood the intention of this PR...I'll leave up to @jstockwin to fill in.

**Comment by jstockwin** [comment]
All this PR does is allow devs to run our test suite in Chrome rather than Firefox. I figured this might help for people who don't have Firefox installed. 

It worked for me locally. If it's not something we're interested in then I'm happy to close. 

Cc// @jedwatson @webteckie

**Comment by jstockwin** [comment]
Maybe let's just close it. We can always pick this up another time if needed.

**Pull request closed without merging**
