### PR TITLE
GeoPoint display fixes for Type.GeoPoint and Type.Location

### PR DESCRIPTION
**Pull request by WingedToaster**
This fixes a crash when a GeoPoint is added as a column on the index page and there is no GeoPoint saved for the record. This also updates the location field to display the coordinates in Lat/Lng instead of Lng/Lat when editing the record.

### CODE REVIEW

**Comment by morenoh149** [comment]
@WingedToaster why should we prefer Lat/Lng over Lng/Lat ?

**Comment by WingedToaster** [comment]
Other humans (read: non-MongoDB/GeoJSON programmers) would typically read and enter the data in it in Lat/Lng format, no?

Also, in it's current state the render of Lat/Lng when one is displaying and editing Types.Location is inconsistent with how Types.GeoPoint is rendered when it is being displayed and edited. <a href="https://github.com/keystonejs/keystone/blob/master/fields/types/geopoint/GeoPointField.js#L18-36">Types.GeoPoint is rendered in Lat/Lng format</a>

**Comment by JedWatson** [comment]
Thanks @WingedToaster, looks good.

**Comment by dcousens** [comment]
@Winged this caught me, expected `Lat/Lng`, got `Lng/Lat`. 

However, this is a breaking change @JedWatson.

**Comment by WingedToaster** [comment]
Sorry about that...what's the bug?

**Comment by dcousens** [comment]
I had code that relies on them being the other way.  :)

**Comment by JedWatson** [comment]
@dcousens they were just changed for display, what are you doing that would break with this? the data is stored in the same format...

The location field displays `Lng / Lat` so we should ensure it is consistent everywhere, I'll open another issue for that.

**Comment by WingedToaster** [comment]
Just to be clear there is a bug fix on this commit/PR so if the Lat/Lng display change ends up getting reverted back, the <code>if</code> statement on <a href="https://github.com/keystonejs/keystone/blob/890ddd7268a59d0196702749b4dfaa0905b7bcc7/fields/types/geopoint/GeoPointType.js#L65">Line 65</a> should remain.

**Comment by morenoh149** [comment]
@WingedToaster for future PRs please do try to make them as granular as possible. So the project can selectively integrate proposals.

**Pull request merged**
