### PR TITLE
Automate dependency maintenance.

### PR DESCRIPTION
**Pull request by ericelliott**
After this PR, we'll want to turn on Greenkeeper.io.

└[∵┌]└[ ∵ ]┘[┐∵]┘

### CODE REVIEW

**Comment by jonathanp** [comment]
:+1:

**Comment by ericelliott** [comment]
This PR has 4 major version bumps that need to be investigated more carefully by somebody more familiar with the code.

(☞ﾟ∀ﾟ)☞ @JedWatson

**Comment by JedWatson** [comment]
Two things to call out:

- `multer` currently needs to be pinned at `0.1.8` (see #1563)
- `qs` needs to be pinned at `4.0.0`, this is aligned with the dependency in `history`.

`qs` is basically (╯°□°)╯︵ ┻━┻

they've migrated the package to es6 without shipping a transpiled build, which means we would need to change our build process to babelify it ourselves and use in node.js would break compatibility with 0.10/12 which Keystone still currently targets.

So for that, and to prevent duplicates in the client-side bundle (w/ history), we're leaving it where it is until there's a better option. I'd like to move away from it entirely.

I haven't tested babel-eslint@5.0.0-beta4 but I expect we can work through any issues that come up (if any)

Everything else looks :+1:

**Comment by ericelliott** [comment]
> they've migrated the package to es6 without shipping a transpiled build, which means we would need to change our build process to babelify it ourselves and use in node.js would break compatibility with 0.10/12 which Keystone still currently targets.

We should file this as a bug against their repo.

**Comment by ericelliott** [comment]
> I haven't tested babel-eslint@5.0.0-beta4

I found a bug in this today. I'm going to re-pin an older version.

**Comment by JedWatson** [comment]
Good to go! Thanks @ericelliott

**Comment by JedWatson** [comment]
> We should file this as a bug against their repo.

From issues I've already read, they're aware and don't care. The whole project has had a call for maintainers. It also looks like client side support is being dropped, based on a thread on the history repo (where we're discussing moving to a different package)

**Comment by ericelliott** [comment]
Is there an issue tracking the replacement?

**Comment by JedWatson** [comment]
@ericelliott rackt/history#121

**Comment by ericelliott** [comment]
:+1:

**Pull request merged**
