### PR TITLE
File fields

### PR DESCRIPTION
**Pull request by JedWatson**
@sebmck has contributed a functionally complete (?) implementation of generic `File` and `Files` fields.

The job from here is to merge the latest changes in and ensure the fields work correctly across all the use-cases (including the implementation of the backwards compatible field types for `LocalFile` etc, which will remain until `0.4.0`)

Once these are up and running, we'll create branched `Image` versions of them which will resolve the issues floating around to make `File` fields play more nicely with images (including previews, etc)

Please sound out here if you're interest / capable of helping with the effort to get this merged!

### CODE REVIEW

**Comment by typ90** [comment]
I'm in...no doubt :+1:

**Comment by creynders** [comment]
So, I tried to identify which commits have happened in the mean time that affect any of the existing file field/type files. I used:

```sh
git log d636282..master --pretty=oneline --follow fields/types/cloudinaryimage
git log d636282..master --pretty=oneline --follow fields/types/cloudinaryimages
git log d636282..master --pretty=oneline --follow fields/types/localfile
git log d636282..master --pretty=oneline --follow fields/types/localfiles
git log d636282..master --pretty=oneline --follow fields/types/s3file
git log d636282..master --pretty=oneline --follow fields/types/Field.js
git log d636282..master --pretty=oneline --follow fields/types/Type.js
```

To get all commits that affected file field files, then unduped them and this is the result:

f3369d727cd7e302346238270dda58f203ff267d Added space += className in CloudinaryImageField.js and added JSX quotes in EmailField.js
601b4e1c294c94ef642bf98f6b32bc5060e4e8de ESLint syntax fixes mainly focused on 'semi, quotes' - up tofields/types/code/test/server.js
96318a06b540f5aeb73218ec9076a09614893a41 Use filename without suffix as default publicID for cloudinary
ee6f552178efdda88d561ed00e03a53d7d86d3b2 Adding displayName to field components
35f74a1c962fa445b3dd8e0902256e9ab544d013 Fixed '' back to "" on JSX attributes
22674909e14c9b3139c67c53e74a51610f618720 ESLint syntax clean up up to fields/types/localfile/LocalFileType.js
c5c274f67bebc754e3f04c341050c831e8ca3940 Extract prepost functionality to separate module
2100c010b9aee5089e2ae6b92cf74da2c1b58f1e upload field should collapse
319a9d3460e00ed3614acde772fe888abc0d786e Pass full file object to filename option function
285cc4bf231a4e74ce2ba4ff919ed7b39dc2c549 Store originalname for localfile docs
c4f820e5fcfde24a545686bf9b18225bb199d79e ESLint syntax clean up - up to: fields/types/relationship/RelationshipType.js
05c66237a431b5316a54cc035b1bfb18d4e2e40f ESLint syntax clean up - up to: lib/core/importer.js
cbd341e51bed82a16ae9c4a1774cea0766d7b88f Revert "Merge pull request #1 from montmanu/s3file-delete"
2dbcfad2ccc9acd1b9e5044709d08feceb1ce10d Revert "Merge pull request #1 from montmanu/s3file-delete"
9dba96dba5faba02b4b02d9dd39bd46551253d43 [s3file] stop storing headers in database
2eb38b9fb86dccf43988430bae10107e2732ee57 [s3file] remove logging
de5a836ff6eaacbe86e0287a3120381506413a3b [s3file] use correct _.each() iteratee argument syntax when list is an object
a9b262e83f76e12027ae26f52f3ee0c1c1d6e124 [s3file] convert spaces to tabs to reduce diff noise
d769a346daab5b01f256b88b4c988d60276e1b3f [s3file] check _.isArray and _.isFunction before _.isObject
32eb4dbba049b971321d86ecaf98ef94dbaf8be5 [s3file] support custom headers
03b3416552e3594437d6b36552fb195051939f18 [s3FileType] delete file on remove, change
7824220065db819f79a9354ec7dd0d8c65ec93cc ESLint syntax fixes mainly focused on 'semi, quotes' - up to fields/types/Field.js
d9c91c8aee2aac58be299b7085a4eec2fa72cfea asyncdi is now an independent package
ebd3ec8ecc3c05f3a0a675f777030f1dfcafe01e Allow `value` field options to be asynchronous

So, to avoid regressions we need to make sure all of the above changes are merged/migrated to the file-field branch, before we can land this.

@JedWatson @sebmck agreed?

**Comment by creynders** [comment]
To view a diff of changes to those files:

```sh
git difftool d636282..master -- fields/types/cloudinaryimage fields/types/cloudinaryimages fields/types/localfile fields/types/localfiles fields/types/s3file fields/types/Field.js fields/types/Type.js
```

Maybe it's best to view differences file by file and make sure all applicable changes are transferred to `field-fields`?

**Comment by creynders** [comment]
I'm **really** sorry, but I'm almost certain there be dragons here, needs confirmation however, went through these just real quick:

- [ ] `pre` and `post` "move" hooks have disappeared for all file fields. 
- [ ] partial regression of 285cc4b, I only found `originalname` in CloudinaryImageType, but none of the others
- [ ] partial regression of ee6f552, no `displayname`s for any of the file fields.
- [ ] full regression of 2100c01, no `shouldCollapse` for local file fields
- [ ] full regression of 319a9d3, in fact, AFAICT the whole `filename` functionality has disappeared?

I'll update with **confirmed** if I'm able to confirm this myself or get notification from someone else, and tick the boxes if solution have been pushed.

**Comment by milosdakic** [comment]
+1

**Comment by felixSchl** [comment]
What's the status of this?

**Comment by bawbb** [comment]
yup. ditto. status?

**Comment by creynders** [comment]
Status: trailing hopelessly behind. I hope to show this some love next week, since it's sorely needed. But, sooooo much has changed in the mean time and it wasn't easy to begin with ... *sigh*

**Comment by JedWatson** [comment]
@creynders if you've got time to pick this up let me know, the only way out is through and this is a huge thing we need to get behind us. Hopefully we'll have some time next week at TM to apply effort specifically to getting this over the line so let's coordinate :)

**Comment by creynders** [comment]
@JedWatson ready to put my teeth into it again. Will need to do some catching up though ...

**Comment by mahnunchik** [comment]
Hi @JedWatson @creynders 

I would like to help you with this big task.

Could you explain why https://github.com/keystonejs/storage was abandoned?

**Comment by morenoh149** [comment]
@mahnunchik that was spearheaded by @grabbou and as many oss projects lost steam

**Comment by mahnunchik** [comment]
@morenoh149 What happened to @grabbou ? If it is not a secret.

**Comment by creynders** [comment]
@mahnunchik help is more than welcome, thanks! There's a `file-fields` branch with the changes. Beware though: it's trailing behind a LOT. I just don't seem to find the time to move on with it.

**Comment by mahnunchik** [comment]
1. Maybe there is sense to rebase `file-fields` branch on to of current `master` before continuing implementation of the file fields?
1. `multer` was updated so new version can be used as dependency https://github.com/keystonejs/keystone/issues/1563
1. What do you think about operations on files `in memory`? For cloud based storage engines it does not require saving files locally. For local files it requires only one filesystem operation. https://github.com/expressjs/multer#memorystorage

**Comment by creynders** [comment]
Yeah it definitely needs to be rebased first.

**Comment by whilefor** [comment]
Any luck with the merge? it is a very useful functionality, need it so much. @creynders  @JedWatson

**Comment by whilefor** [comment]
Could I just use the branch `file-fields` for my project?

**Comment by morenoh149** [comment]
@whilefor https://docs.npmjs.com/files/package.json#git-urls-as-dependencies yes

**Comment by mahnunchik** [comment]
Hi,

I was unsuccessful with the rebase :cry:

Someone who will make the rebase should have experience in js and in React too.

**Comment by whilefor** [comment]
oh,  seems it is a big rebase

**Comment by mariohmol** [comment]
+1

**Comment by mxstbr** [comment]
This is in its current state no longer mergeable, we'll be looking into redoing this with v0.4 based on the current `master`! (PR anybody? :+1: )

**Pull request closed without merging**
