### PR TITLE
Adds "cloudinary_upload_preset" param to Wysiwyg

### PR DESCRIPTION
**Pull request by 3lijah**
This allows users to upload to cloudinary from TinyMCE.

(There's probably a better way of doing this)

### CODE REVIEW

**Comment by ra-external** [comment]
@3lijah -- Can you explain how this would work exactly within Keystone and within the Wysiwyg component?  That is, could you give a code example of what goes in the `editorConfig`, etc?  I was trying to see if I could get it to work in my app prior to the PR being merged...

**Comment by 3lijah** [comment]
> @3lijah -- Can you explain how this would work exactly within Keystone and within the Wysiwyg component? That is, could you give a code example of what goes in the `editorConfig`, etc? I was trying to see if I could get it to work in my app prior to the PR being merged...

Sure, in my code I have something like this:

```
keystone.createList('Article', {
  fields: {
   ...
    body: {
      type: Wysiwyg,
      editorConfig: {
        images_upload_url: 'https://api.cloudinary.com/v1_1/[cloud_name]/image/upload',
        cloudinary_upload_preset: [cloudinary_preset_code],
      }
    },
  },
  ...
})
```

With the `cloudinary_upload_preset` parameter in this PR, I can successfully upload to Cloudinary through the TinyMCE interface. This is a workaround for `images_upload_handler` parameter being stripped from editorConfig because it contains to a function.

**Comment by ra-external** [comment]
@3lijah -- I'm new to cloudinary.  Would the 'preset code' simply be the name of the preset, e.g. 'default-preset' (if that's what I've named the preset)? I tried what I believe was exactly what you had above, where I had a TinyMCE custom field (custom, to contain your changes) as part of an 'Article', but when I went to create the Article in the AdminUI it just hung (that is, kept displaying the animation for opening the Article sub-window).  I was wondering if I'd gotten the preset string wrong....

**Comment by Petrux99** [comment]
> This is a workaround for the `images_upload_handler` parameter being stripped from editorConfig because it's a function.

This seems like a documentation bug to me, considering the wording on https://www.keystonejs.com/keystonejs/fields-wysiwyg-tinymce/: "Accepts **any** TinyMCE config options. These will be passed to tinymce.init and can be used to override Keystone.js' default editor appearance and functionality." (my highlighting). But I'm not sure if it's the documentation that should be changed or if that filtering away of functions can be avoided for this case. Where in the source does that filtering happen?

Another thing I thought about was whether the thing this PR is trying to solve could be achieved using the CloudinaryAdapter which uses the Cloudinary SDK internally and which is already capable of uploading files there (with auth). Is that something you considered, @3lijah ?

**Comment by Vultraz** [comment]
@Petrux99  `images_upload_handler` getting stripped from the config is a bug, though not one I'm entirely sure how to solve. That will happen to any function in `editorConfig`, not just `images_upload_handler`.

**Comment by nyinyinyanlin** [comment]
> > @3lijah -- Can you explain how this would work exactly within Keystone and within the Wysiwyg component? That is, could you give a code example of what goes in the `editorConfig`, etc? I was trying to see if I could get it to work in my app prior to the PR being merged...
> 
> Sure, in my code I have something like this:
> 
> ```
> keystone.createList('Article', {
>   fields: {
>    ...
>     body: {
>       type: Wysiwyg,
>       editorConfig: {
>         images_upload_url: 'https://api.cloudinary.com/v1_1/[cloud_name]/image/upload',
>         cloudinary_upload_preset: [cloudinary_preset_code],
>       }
>     },
>   },
>   ...
> })
> ```
> 
> With the `cloudinary_upload_preset` parameter in this PR, I can successfully upload to Cloudinary through the TinyMCE interface. This is a workaround for the `images_upload_handler` parameter being stripped from editorConfig because it's a function.

I am receiving a `400:Bad Request` by this method. From my browser's web request inspection, request body doesn't include a `upload_preset` data. Why could this be?

**Comment by 3lijah** [comment]
> > > @3lijah -- Can you explain how this would work exactly within Keystone and within the Wysiwyg component? That is, could you give a code example of what goes in the `editorConfig`, etc? I was trying to see if I could get it to work in my app prior to the PR being merged...
> > 
> > 
> > Sure, in my code I have something like this:
> > ```
> > keystone.createList('Article', {
> >   fields: {
> >    ...
> >     body: {
> >       type: Wysiwyg,
> >       editorConfig: {
> >         images_upload_url: 'https://api.cloudinary.com/v1_1/[cloud_name]/image/upload',
> >         cloudinary_upload_preset: [cloudinary_preset_code],
> >       }
> >     },
> >   },
> >   ...
> > })
> > ```
> > 
> > 
> > With the `cloudinary_upload_preset` parameter in this PR, I can successfully upload to Cloudinary through the TinyMCE interface. This is a workaround for the `images_upload_handler` parameter being stripped from editorConfig because it's a function.
> 
> I am receiving a `400:Bad Request` by this method. From my browser's web request inspection, request body doesn't include a `upload_preset` data. Why could this be?

This fork has not been merged. You could try to use `https://github.com/3lijah/keystone.git` as the version in your package.json

**Comment by nyinyinyanlin** [comment]
Can you please tell me how do I do it? I have created my app using `yarn create keystone-app`. Thank you!

**Comment by bladey** [comment]
Thanks for this PR @3lijah.

**Keystone 5** has officially moved into active maintenance mode as we push towards the next major new version **Keystone Next**, you can find out more information about this transition [here](https://github.com/keystonejs/keystone/issues/4962).

In an effort to sustain the project going forward, we're cleaning up and closing old PRs such as this one.

However, you are welcome to create a PR under the [Keystone 5](https://github.com/keystonejs/keystone-5/pulls) repository.

Please let me know if you have any questions.

**Pull request closed without merging**
