### PR TITLE
Export cli functions from keystone

### PR DESCRIPTION
**Pull request by gautamsi**
this lets me run keystone programmatically from another nodejs app

```ts
import { cli } from '@keystone-next/keystone/scripts/cli';
```

### CODE REVIEW

**Comment by dcousens** [comment]
@gautamsi could you rebase this? LGTM

**Comment by gautamsi** [comment]
@dcousens done.

**Comment by dcousens** [comment]
@gautamsi is there any particular reason spawning a CLI process wasn't the preferred approach for this?

**Comment by gautamsi** [comment]
I was trying to run it programmatically when embedded inside the ElectronJS. When it is inside packed archive it does have lot of problems when accessing various directories 8f I try to run this by spawning new/child process. I have tested by exporting cli and it worked.

**Comment by gautamsi** [comment]
@dcousens should we close this?

**Review by borisno2 — APPROVED** [review]

**Pull request merged**
