### PR TITLE
change from yandex to airbnb

### PR DESCRIPTION
**Pull request by weekwood**
keystone follow airbnb code style, right?

### CODE REVIEW

**Comment by sebmck** [comment]
> keystone follow airbnb code style, right?

Not in the slightest.

**Comment by JedWatson** [comment]
@weekwood it's not that simple, there was a lot of prior conversation behind this and a lot of (invalid) errors are shown when airbnb is selected because we don't follow it entirely. The config needs to be changed quite a bit from the preset to match our standards.

We had a linter that worked until changes to jshint and the introduction of jsx, now it's a mess. I'm currently thinking our best option is to switch to babel's linter (which supports JSX and ES6) with the appropriate config set up for Keystone.

**Comment by JedWatson** [comment]
(nudge @sebmck? :)

**Comment by weekwood** [comment]
ha @sebmck counting on you :)

**Pull request closed without merging**
