### PR TITLE
Fine-tune uglify settings

### PR DESCRIPTION
**Pull request by wmertens**
## Description of changes

Nicer minified packages build for debugging

When an error occurs in KS, it is hard to debug.
With the semicolons turned off, the minified build at least has short lines so the browser debugger works faster with it.

Furthermore, IE8 is not supported so that allows further optimization.

### CODE REVIEW

**Comment by wmertens** [comment]
@jed thoughts?

**Comment by jed** [comment]
Looks good to me!

**Comment by mxstbr** [comment]
LOL @jed 

LGTM

**Comment by mxstbr** [comment]
@wmertens please don't listen to @jed again :grin: I think you meant @JedWatson

**Comment by wmertens** [comment]
LOL argh, I thought it was weird his avatar changed. Shouldn't let different domains have different aliases 😅

**Comment by JedWatson** [comment]
lol, for what it's worth, that's what I would have said!

**Comment by wmertens** [comment]
Cool, from now on we can use @jed and @JedWatson interchangeably ;)

On Thu, Jun 30, 2016 at 5:15 PM Jed Watson <notifications@github.com> wrote:

> lol, for what it's worth, that's what I would have said!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/keystonejs/keystone/pull/3097#issuecomment-229690695>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADWliVqNeyemkbnHi9jmHnaj_-wKj-Tks5qQ92pgaJpZM4JCPJ5>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Pull request merged**
