### PR TITLE
Cookie signin persistent across subdomains

### PR DESCRIPTION
**Pull request by jacargentina**
## Description of changes

Adds the `cookie signin domain` keystone option, which allows to have the same keystone instance running across subdomains and every instance remembers the logged in user.

For example: user 'sam' logs in to http://www.example.com/keystone, and later when accesing http://support.example.com he is already logged in!

## Related issues (if any)

#1895 

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks great! :+1:

**Comment by mxstbr** [comment]
Comment by @creynders over at #2954:

> I'd rather let users provide all cookie settings, i.e. something like

```js
var cookieSettings = _.defaults({ 
  signed: true, 
  httpOnly: true, 
  maxAge: 10 * 24 * 60 * 60
}, keystone.get('cookie settings'));
```

Which I think sounds reasonable.

**Comment by jacargentina** [comment]
@creynders i think the `_.defaults` call should be inverted right? I mean, respect user settings, then apply any missing property by default.

**Comment by creynders** [comment]
@jacargentina yep, that's right. I just can't seem to remember the order in which the parameters are applied in `_.assign` and `_.defaults`

**Comment by JedWatson** [comment]
:+1: looks good @jacargentina! thanks :)

**Comment by webteckie** [comment]
@jacargentina can you please add a doc issue to https://github.com/keystonejs/keystonejs-site/issues to remember to document this feature...thanks :-)

**Pull request merged**
