### PR TITLE
Object Array Field

### PR DESCRIPTION
**Pull request by micahbule**
This is a crude implementation of an Object Array Field.
NOTE: I'm creating this PR so I can get guidance on how I can possibly improve this implementation. IT'S NOT FOR ACTUAL MERGING. There's also no tests for this one. I would really love some help on creating unit tests.

Concept: I'm nesting schemas, basically putting a List object inside another List object. I've tried nesting ObjectArrayFields too, and it does work. Rendering the fields in the AdminUI is also working, including Keystone fields like Images or Color (I've got an error with TinyMCE which I still have to resolve).

There would be very weird parts here, specifically in the RelationshipField, because I had to include sublists as fields in another related list, you can just ignore that.

Oh, lastly, excuse my commit messages. Was working on this over two machines.

Field Signature

```
Customers.add({
    name: { type: String }.
    contact_method: {
        type: Types.ObjectArray,
        nestedFields: {
             method: { type: Types.Select, options: ['Mail', 'Phone', 'E-mail', 'Fax'] },
             value: String
        }
    }
});
```

### CODE REVIEW

**Comment by webteckie** [comment]
:+1: for the field signature.  I would be interested in this! Hopefully you will get feedback from others in the team.

**Comment by sachss** [comment]
+1000 and MAJOR thank you for this. Spun it up successfully with a fork of the current keystone master.  I am extremely invested in getting this feature accepted for the next release.  You mentioned unit tests, and there's of course documentation--any other ways you're looking for contribution?

I added your contact_method field into my existing User model and got "Name field is required" errors because the Name field (Types.Name) had `required=true`.  Removing the required property allowed the document to save.  Do you know why this would be?  

Thank you again, this PR and the progress you've made make my month.

**Comment by micahbule** [comment]
@sachss I'm pretty sure those errors are features of Keystone because you added the `required=true` option to the field, which makes it, obviously, required. So when you save it as blank, it will cause an error.

Would like to know though if you used Type.Name inside my implementation of ObjectArray and if it worked without the `required=true` option? I haven't tested all the fields tbh, just a few couple.

Regarding other ways to contribute to the effort, I'm not sure how this would fit in the filters for the AdminUI, so I haven't touched that part yet. Testing ALL Keystone fields and identifying errors would be a good start too.

**Comment by sachss** [comment]
@micahbule Thank you for your reply!  Here is the object model I'm using:
```javascript
var Customer = new keystone.List( 'Customer', {} );

Customer.add( {
    name          : { type: Types.Name, required: true },
    contact_method: {
        type        : Types.ObjectArray,
        nestedFields: {
            method: { type: Types.Select, options: [ 'Mail', 'Phone', 'E-mail', 'Fax' ] },
            value : String
        }
    }
} );
```
You can create the object fine, but you cannot modify it (even without populating the contact_method field) because of the required field error.  If you remove `required: true` from the model above, you are able to modify and save the object.  

I've not done any in depth analysis but suspect this may be due to the splitting in `complexFieldParser.js`.  

I think I'll start my angle of attack from the unit tests perspective (I wouldn't be doing anyone any favors with my UI work...) and hopefully dredge up any other compatibility issues that may exist.  

One more time, I really appreciate your work on this.

**Comment by micahbule** [comment]
@sachss Yeah, I think I've got the error, my bad. It's the `complexFieldParser.js` file. Will need to filter out the `ObjectArrayField` inputs from other native Keystone inputs that are also nested. Thanks for pointing out.

**Comment by mxstbr** [comment]
This is definitely a very important feature I'd like to get into a 1.0 release, thanks so much for kicking off the implementation @micahbule – great work!

The blocker with this PR is that we're in the process of overhauling the fields and the admin ui completely for 0.4, so this will probably need to be completely updated. I'll put this on hold for now, and we'll review if and how much we have to change after 0.4 is out! (Sounds reasonable? Ping me if I forget please!)

**Comment by micahbule** [comment]
@mxstbr sure thing! This isn't a completed feature anyway, rather a rough draft of it. I just made it into a PR so the community can take a look at it, use it, tinker with it, and probably help me to figure it out properly. It's actually one of my first major contributions to an open source project tbh.

**Comment by terenzeyuen** [comment]
Hi @micahbule we are so interested in this. Just tried with images (cloudinary) but it is returning no URL value. You mentioned you've got images working – what did you use, can you kindly share?
This is my setup:

contact_method: {
        type: Types.ObjectArray,
        nestedFields: {
			images: {
				type: Types.CloudinaryImage
			},
             value: String
        }
    },

**Comment by terenzeyuen** [comment]
Any help? :)

**Comment by terenzeyuen** [comment]
@micahbule did you manage to get local files working?
screen shot 2016-04-27 at 11 41 53

**Comment by bassjacob** [comment]
We've been implementing this in #3282  which is planned to be merged for the 4.0 final release, so I'm going to close this now. Thanks for the original implementation @micahbule

**Comment by SamAlbuga** [comment]
@terenzeyuen How did you manage to get this working? It's working when I use ObjectArray type!

**Comment by lukas-outlook** [comment]
Hi,
Has "Types.ObjectArray" been removed from v4 beta? Is there something I could use instead?

**Comment by NTruchaud** [comment]
Any news on this ?

**Comment by pihyper** [comment]
Need to know how to implement Object Array.

**Comment by david1542** [comment]
Was there any progress on this guys?

**Comment by aleygues** [comment]
+1

**Comment by stelio** [comment]
+1

**Comment by NeoTheSecond** [comment]
+1

**Comment by gautamsi** [comment]
Adding +1 doesn't help, locking this thread

**Pull request closed without merging**
