### PR TITLE
Fix array field bug#1593

### PR DESCRIPTION
**Pull request by loffek**
fixes issue https://github.com/keystonejs/keystone/issues/1593

Problem:
- `initial: true` on an TextArrayType breaks the React front end with "Uncaught TypeError: this.props.value.map is not a function in fields.js 109", unless `default: ['']` is set explicitly
- If the array of a TextArrayType has length zero or one, and some validation rule fails so that the "Create new"-modal is shown again with an error-message, the React Frontend breaks with "Uncaught TypeError: this.props.value.map is not a function in fields.js 109".
- Old values in the db that are not arrays probably also breaks the front end.
## Description of changes

The problem is that in the above scenarios, an ArrayField is created with `props.value` not being an array (eg. undefined or just a string). By ensuring that the value is an array before calling `.map()`, the bug is avoided.
## Related issues (if any)

https://github.com/keystonejs/keystone/issues/1593
## Testing

I couldn't find any established tests for the React frontend, so I haven't written any tests for this bug. Please let me know how this could be done if it's required.

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks like a solid fix, will check it out tomorrow! Thanks so much!

**Comment by AurelioDeRosa** [comment]
Is this fix good to merge?

**Comment by hulvei3** [comment]
How about that merge? :) Dunno if how it's behaving with the upcoming 0.4+ though..

**Comment by Noviny** [comment]
We're not accepting PRs into 0.3 anymore, sorry. Thankyou for your contribution.

**Pull request closed without merging**
