### PR TITLE
Removed some unused types from roles example

### PR DESCRIPTION
**Pull request by dominikwilkowski**
Looks like neither `ListsAPI`, `GraphqlAPI` nor `FieldAccessArgs` was being used in the role example so I removed `FieldAccessArgs` and left the other two in the comment with them pointing to `KeystoneGraphQLAPI` and `KeystoneListsAPI` respectively.

### CODE REVIEW

**Review by timleslie — APPROVED** [review]
LGTM 👍

**Review by emmatown — CHANGES_REQUESTED** [review]
Can you delete the stuff rather than commenting it out?

**Comment by dominikwilkowski** [comment]
@mitchellhamilton I'm happy to but there was a comment in there I assumed has value. All I did was make it work and removed the not-used things. Are those types now all generated?

**Comment by mitchellhamilton** [comment]
We need to look at the type generation stuff again in detail sometime but right now, having those bits in comments isn't really adding value.

**Comment by dominikwilkowski** [comment]
Removed @mitchellhamilton

**Review by emmatown — APPROVED** [review]

**Pull request merged**
