### PR TITLE
Update initial data docs

### LINKED ISSUE #2438: Same example for createItems with Simple and Array Relation Syntax in Docs
It seems to me there is a mistake in [Adding initial data](https://github.com/keystonejs/keystone/blob/3abc58831e0f9b5871569a3fa6b21be7dc269cf3/docs/guides/initial-data.md)  

Both examples of Simpla and Array Relation Syntax has the same code.

### PR DESCRIPTION
**Pull request by timleslie**
Following up on some PR requests I did a play through of this tutorial and have brought it more up to date for content and correctness when following the steps.

Fixes #2438

### CODE REVIEW

**Review by molomby-alt — APPROVED** [review]
I prefer it when sentences in markdown are on their own line (as per our much-ignored [style guide](https://github.com/keystonejs/keystone/blob/master/STYLE_GUIDE.md#text-blocks))... but I don't care about it enough to update this PR and I don't suppose you do either 🤷🏻‍♂️

**Comment by molomby** [comment]
^^ Me

**Comment by timleslie** [comment]
> I prefer it when sentences in markdown are on their own line (as per our much-ignored [style guide](https://github.com/keystonejs/keystone/blob/master/STYLE_GUIDE.md#text-blocks))... but I don't care about it enough to update this PR and I don't suppose you do either 🤷🏻‍♂️

Oh, yeah this is actually a thing for me as well, let me go through and apply that here 👍 (Also note, rules aren't rules until the linter checks them. Would love someone to find a way to implement that as a lint rule!)

**Review by molomby — APPROVED** [review]
👍🏼

**Review by gwyneplaine — APPROVED** [review]
lgtm

**Pull request merged**
