### PR TITLE
Fix attempt for issue #3979

### PR DESCRIPTION
**Pull request by t100n**
Set semicolons=true in the build command that is passed to uglifyjs.
Added 'aphrodite/no-important' to the required packages in admin/client/packages.js.

Issue #3979 :
admin/public/js/packages.js generates a Uncaught SyntaxError: Unexpected string when minified, and fails to load the admin interface.
After some digging I found that uglifyjs compresses the typeof checks into the following format "undefined"==typeof x which triggers a syntax error after passing through another minification process when deployed.

### CODE REVIEW

**Comment by Noviny** [comment]
@t100n So glad someone got to the bottom of this rabbit hole. We haven't encountered the issue, so I can't validate that this fixes it, but I take that it fixed the issue for you?

Also, why was adding aphrodite relevant to resolve this?

**Comment by t100n** [comment]
@Noviny indeed this was the solution for my problem.

I was forced to add 'aphrodite/no-important' because it was triggering a missing module while loading the admin UI, during my testing of the new packages.js file. So it was just to make it work.

**Comment by Noviny** [comment]
@t100n Thanks for providing this fix.

**Comment by Zedonboy** [comment]
@t100n where will i find all these "semicolons = true".... I should tamper with the npm package(keystone)

**Pull request merged**
