### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jackdewan**

### CODE REVIEW

**Review by noor-codes — APPROVED** [review]
Looks good 👍

**Comment by jackdewan** [comment]
No problem, @dcousens !

**Comment by jackdewan** [comment]
@dcousens found another typo 
https://keystonejs.com/why-keystone#ecommerce
Master eCommerce with Keystone, React, & GraphQL. Join Wes as he teaches you how to build a full-stack online store with of** today's best JavaScript technology.

**Comment by dcousens** [comment]
Thanks @jackdewan https://github.com/keystonejs/keystone/commit/31e172d95860beda637d3646cfb2713904df3fd9

**Pull request merged**
