### PR TITLE
test(e2e): ux boolean field

### PR DESCRIPTION
**Pull request by joerter**
@webteckie ux test for boolean field. Let me know if I'm missing anything!

### CODE REVIEW

**Comment by webteckie** [comment]
@joerter would it be possible to use the pattern the other fields use where the `name` field is the initial and use to test creation of the field via the modal and the `testA` field can be used to create/fill in the field in the edit form?  I expect the field list models to be updated with more test fields to test other options that can be configured in the field.  Thanks!  

PS: I submitted a PR today to simplify some of the selectors around lists.

**Comment by joerter** [comment]
That makes sense, will do! Also, as we add more tests for fields are going to want to keep them in alphabetical order in the file numbering and in the admin nav?

**Comment by webteckie** [comment]
Yeah, in the nav we should keep them in alphabetical order.  As far as the test sequence number that's a bit harder to accomplish.   What if after we are done new fields come about that need to be inserted in the middle of the order...that would require renaming all files after it.  For that reason I wouldn't worry about it?  Agree?

**Comment by joerter** [comment]
Agreed. Having to rename files to keep alphabetical order would get messy.

**Comment by webteckie** [comment]
Hi @joerter I just pushed some e2e changes.  They are mostly a refactoring of the global and home view selectors now that we have enhanced selectors in the client per other recent commits I did.  I still do not like the list selectors and need to think about how to improve them.  We may have to propose similar changes to the ones I pushed in the Admin UI for the global and home views.  But now it is a bit easier to digest the refactored selectors :-)  Feel free to push your PR on top of the latest changes!

**Comment by joerter** [comment]
@webteckie Thanks! I've updated my changes.

**Comment by webteckie** [comment]
@joerter excellent!  Pick your next field :-)

**Comment by joerter** [comment]
@webteckie Alright! I was thinking of going with number next

**Comment by webteckie** [comment]
All yours!  Thanks!

**Comment by mxstbr** [comment]
Awesome!!

**Comment by webteckie** [comment]
@joerter actually I just realized you used positional selectors (e.g., .field-type-boolean:nth-child(5)') for the boolean field.  I'm trying not to use positional selectors as things will get all screwed up with any insertion of other items in the page.  But I can see the reason you used positional selectors...you had no choice :-)  I just opened #2551 to address this.  If you (or anyone else) want to give that a shot feel free.  Otherwise, I'll try to look into it tomorrow evening.

**Comment by joerter** [comment]
@webteckie Cool, I'll go for it!

**Pull request merged**
