### PR TITLE
Fix configureExpress()

### PR DESCRIPTION
**Pull request by sarneaud**
`configureExpress()` was run on an Express app, and routes were added to
an Express router, but the two weren't connected together.

This version ditches the extra router and just uses the middleware by
itself to make the loading screen intercept.

Addresses https://github.com/keystonejs/keystone/issues/1887

### CODE REVIEW

**Comment by Vultraz** [comment]
This might actually fix various problems, including the issues with secure cookies and with templating engines not working.

**Comment by gautamsi** [comment]
I can confirm this does not fix the view engine stuff. but I managed to update `@keystonejs-contrib/view` without the need of this. thanks to `@Whosy`'s finding (slack).

here is the code 
https://github.com/keystonejs-contrib/keystonejs-contrib/blob/4f2acb35a8dd470ba5dcfdeb6758dd30b5e653d4/examples/blog-view/index.js#L63-L84


```js
const blogApp = {
  prepareMiddleware: ({ keystone }) => {
    const app = express();
    app.use(bodyParser.urlencoded({ extended: true }));
    app.set('views', './templates');
    app.set('view engine', 'pug');
    initRoutes(keystone, app);

    return app;
  }
}

module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new StaticApp({ path: staticPath, src: staticSrc }),
    adminApp,
    blogApp,
  ],
  distDir,
};
```

**Comment by Vultraz** [comment]
Ok, but the view engine stuff still needs to be fixed.

**Comment by gautamsi** [comment]
possible if we change few lines in this PR like this

https://github.com/keystonejs/keystone/pull/2152/files#diff-ac38b0d61846d7008d188f168fb1f6caR98

```js
configureExpress = () => null,
```

https://github.com/keystonejs/keystone/pull/2152/files#diff-ac38b0d61846d7008d188f168fb1f6caR103
```js
const customApp = configureExpress(express());
```
and 
https://github.com/keystonejs/keystone/pull/2152/files#diff-ac38b0d61846d7008d188f168fb1f6caR119

```js
app.use([...middlewares, ...(customApp ? [customApp] : []) ]);
```

**Comment by gautamsi** [comment]
@timleslie should I create a PR for changes I suggested? Or this PR should accommodate them?

**Comment by timleslie** [comment]
> @timleslie should I create a PR for changes I suggested? Or this PR should accommodate them?

A separate PR will be better, I think your proposed changes are related but different to the specific issue being addressed in this PR 👍

**Pull request merged**
