### PR TITLE
Tinymce update

### PR DESCRIPTION
**Pull request by riyadhalnur**
**ADDED:**
- Added support for the 'imagetools' plugin for TinyMCE.
- The plugin enables users to edit inline image in the tinyMCE editor

69d63ae4-7b2a-11e5-872a-c881df43255b  

Sorry about the big diff but all these files are actually TinyMCE files. There was no change made to the core. I just replaced the TinyMCE lib with the latest version.

Essentially, any inline image in the text editor can be edited using this plugin. The image can either be copy/pasted if the paste plugin is enabled or an uploaded image added using the URL if the image plugin is enabled.

### CODE REVIEW

**Comment by riyadhalnur** [comment]
@mxstbr Here you go

**Comment by mxstbr** [comment]
Thanks! So this is just an update to TinyMCE, there are no other changes?

**Comment by riyadhalnur** [comment]
Yeah, just changes to TinyMCE only. I would still test it out manually.

**Comment by mxstbr** [comment]
Do you by chance know why we don't install it [via npm](https://www.tinymce.com/docs/get-started/advanced-install/#npm)?

**Comment by riyadhalnur** [comment]
I've always wondered that for the vendor files in Keystone. TinyMCE and other 3rd party client dependencies are for some reason included in the code base itself.

**Comment by mxstbr** [comment]
Let me check that before merging this PR. Thanks for resubmitting!

**Comment by JedWatson** [comment]
@mxstbr we vendor it in because there's a customised theme file included. we're cautious about updates for the same reason - any breaking change to their stylesheet "api" needs to be tested. TinyMCE is also finnicky about where it's served from due to the way they load plugins and other assets after the page has loaded. I haven't checked recently though, so this may not be a concern anymore.

If we can vendor in any of our currently bundled dependencies with npm and use them as commonjs modules, I'm down with that, but let's deal with that whole concept in a separate issue?

This is :+1: from me - thanks @riyadhalnur!

**Pull request merged**
