### PR TITLE
Fix validation errors not showing in the admin UI

### PR DESCRIPTION
**Pull request by jstockwin**
@mxstbr - a potential fix for #2808

### CODE REVIEW

**Comment by mxstbr** [comment]
That looks reasonable. When was that `s` added, who put it there?

**Comment by jstockwin** [comment]
It hasn't been updated since it was [created](https://github.com/keystonejs/keystone/commit/4988eb7f20705e926b932936eced3975e5c5e850) 6 days ago (Sorry @JedWatson !)

**Comment by creynders** [comment]
No, the file was moved. (Sidenote: a bit surprising GH can't track history over file renames/moves)
I thought it only happened in 0.3, see #2586 
The change was introduced in baff560
The solution isn't straight forward thought, It's a cess pool TBH

**Comment by jstockwin** [comment]
Ah okay, thanks @creynders. Does that mean this PR won't actually fix the issue? 

Is it related to #2814, which is what caused me to notice the problem in the first place!

**Comment by JedWatson** [comment]
@jstockwin does this resolve the issue for you in your testing? If so, I'm happy to merge it.

**Comment by jstockwin** [comment]
@JedWatson It resolves that specific issue yes, but I was worried it might have the opposite affect on other errors, i.e. if the error name _is_ sometimes `ValidationErrors`, and that's why it was like this in the first place.

**Comment by JedWatson** [comment]
Since this is a temporary thing anyway, let's accept both in that condition maybe?

**Comment by jstockwin** [comment]
Fine with me. Will update the PR - will have to wait until a little later if that's okay though I'm afraid

**Comment by jstockwin** [comment]
@JedWatson PR updated to accept both.

**Comment by JedWatson** [comment]
:+1: Thanks @jstockwin!

**Pull request merged**
