### PR TITLE
Relationship fields now display more sensibly when noedit option is set

### PR DESCRIPTION
**Pull request by liamwooding**
If a relationship field has the noedit option set, it now displays linked documents as a list, with a link to the edit form for each (previously displayed concatenated IDs of all documents).

### CODE REVIEW

**Comment by creynders** [comment]
Competitor of #1134 (just putting this here for easier administration, NOT to dis this PR)

**Comment by liamwooding** [comment]
Should have looked through the issues before I made a pull request!

**Comment by creynders** [comment]
Haha, happens a lot to me too...

**Comment by JedWatson** [comment]
@liamwooding my apologies for not merging #1134 sooner - I had it flagged for review and only just got to it. Going with that one of the two because it's closest to our previous implementation. Thanks for the PR!

**Pull request closed without merging**
