### PR TITLE
Sign in is broken (v0.3.x)

### PR DESCRIPTION
**Pull request by gmmeyer**
If you try to sign in with just "\." it will work, given that you have the correct password. It shouldn't.

This fixes it.

### CODE REVIEW

**Comment by jonathanp** [comment]
The same regex is used in `admin/server/api/session/signin.js`, should probably add the same check there.

**Comment by erg0dic** [comment]
Can a 0.3.16 security hotfix go out for this?

Given that there are hundreds of keystonejs deployments in the wild (google -> "powered by keystonejs inurl:signin"), please consider notifying oss-security & getting a CVE # assigned.

**Comment by morenoh149** [comment]
@erg0dic this PR was merged into `v0.3.x` you can use that or are you asking for a `0.3.17` release?

**Comment by erg0dic** [comment]
An npm release & an update to HISTORY.md would be ideal. This way it will be easy for existing deployments to upgrade by bumping the version vs installing the module from git. 

Additionally, you can report the issue to the Node Security Project:
https://nodesecurity.io/report

**Comment by ericelliott** [comment]
Agreed. (☞ﾟ∀ﾟ)☞ @JedWatson

**Comment by JedWatson** [comment]
Preparing 0.3.16 for release right now

**Comment by ericelliott** [comment]
We're saved! \( ﾟヮﾟ)/

**Comment by JedWatson** [comment]
Published. I'll tweet it out as well from the KeystoneJS twitter.

**Comment by JedWatson** [comment]
I have also reported the issue to the Node Security Project so they can notify subscribers.

**Comment by erg0dic** [comment]
Thanks @JedWatson !

**Pull request merged**
