### PR TITLE
Fixing updateItem() in TextArrayType

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
Used `.getValueFromData()` to get the current data (works well with nested paths)

### CODE REVIEW

**Comment by JedWatson** [comment]
Eek! This is going to destroy data when `value === undefined` (i.e. if no value was submitted to be updated)

Also value will always `!= item.get(this.path)` because it's an array.

**Comment by JohnnyEstilles** [comment]
> Eek! This is going to destroy data when value === undefined (i.e. if no value was submitted to be updated)

Understood! So we should simply not save anything ... ???

> Also value will always != item.get(this.path) because it's an array.

`item.get()` wouldn't return an array?

**Comment by JohnnyEstilles** [comment]
What if I just update it ONLY when it's undefined?

```js
textarray.prototype.updateItem = function(item, data) {
	var value = this.getValueFromData(data);
	
	if (value !== undefined) {
		item.set(this.path, value);
	}
};
```

**Comment by JedWatson** [comment]
> item.get() wouldn't return an array?

It would, but it wouldn't be the *same* array, so the simple comparison would fail.

I've just added some more tests for TextArray (including another that fails currently) that will hopefully clarify the required behaviour.

**Comment by JohnnyEstilles** [comment]
Rescinding PR ... will give it another shot.

**Pull request closed without merging**
