### PR TITLE
Create Relationship Items Inline

### PR DESCRIPTION
**Pull request by ajlin500**
This is an initial version of creating relationship items inline. It works with both a single relationship and `many: true` relationships. It still needs things like error messages and CSRF checks. There is also a bit of hacky code but I wanted to submit a PR to get feedback on the API and overall design before I polish it off. This solution could also lead into an easy way to add a sort of Sub-collections https://github.com/keystonejs/keystone/issues/153 by using a `many: true` relationship and adding the ability to drag and drop to change the order of relationship items. Thoughts?

To add a create inline button button to a relationship field, just add `createInline: true`. Example:
`categories: {
    type: Types.Relationship,
    ref: 'PostCategory',
    createInline: true,
    many: true,
 }`

screenshot 2016-01-12 22 46 11
screenshot 2016-01-12 22 46 22
screenshot 2016-01-12 22 46 45

### CODE REVIEW

**Comment by webteckie** [comment]
This should address #282, right?

**Comment by ajlin500** [comment]
@webteckie yep, it would fix that too. I'll set up a demo site on heroku with it so you can easily play around and give some feedback. I'll ping the link here once it's up

**Comment by ajlin500** [comment]
Here is a clone of the keystone demo site using `createInline: true` for authors and categories on the Post model. http://whispering-lowlands-5074.herokuapp.com/

User: demo@keystonejs.com
Password: demo

**Comment by webteckie** [comment]
@ajlin500 Looks very good!  Thanks!

**Comment by JedWatson** [comment]
@ajlin500 this looks great. I'm really happy with your direction here... will provide a more comprehensive review when I get back to Sydney but am happy to merge in the meantime as a WIP. Please keep going with it and open another PR for handling errors / CSRF / other updates.

**Comment by JedWatson** [comment]
@ajlin500 I made some tweaks to your new API endpoint, see the referenced commit

**Comment by vikramparihar** [comment]
@andrewlinfoot  Hi.. I am new to keystonejs.. and as you show we can create category inline with reference option.  But i am still missing this feature. 
My Model code is

Project.add({
	technology: { type: Types.Relationship, ref: 'Technology', refPath: 'technology', createInline: true},
	title: {type: String, required: true, index: true, unique: true},
	features:{type: Types.Textarea},
	tags: { type: Types.Relationship, ref: 'Tag', inline: true, createInline: true, many: true },
	poster: { type: Types.LocalFile,
		dest: 'public/data/posters',
		prefix: '/data/posters/',
		allowedTypes: ['image/jpeg', 'image/png', 'image/jpg'],
		format: function(item, file){
		return ''
	}
	},
	createdAt: { type: Date, default: Date.now },
	updatedAt: { type: Date, default: Date.now },
	description:{type: Types.Html, wysiwyg: true, height: 150 }
});

But there is no option is showing for inline tags creation..  

Thanks

**Comment by andrewlinfoot** [comment]
@vikramparihar Your model code looks good. What version of Keystone are you running? The create inline feature is only available in the version 4.0 beta.

**Comment by webrocom** [comment]
@andrewlinfoot  Okay thats why.. My version is  0.3.17....

**Comment by wangshijun** [comment]
awesome feature! but not included in docs.

**Pull request merged**
