### PR TITLE
Add pagination to bottom of lists

### PR DESCRIPTION
**Pull request by mxstbr**
This adds pagination to the bottom of lists in the admin interface. Before, when you reached the bottom of a list, you'd have to scroll all the way back up to go to the next page.

I've also added a function that scrolls the window to the top after the new page is open!

### CODE REVIEW

**Comment by snowkeeper** [comment]
This would add double pagination links when Drag Drop sorting is enabled.  Adding the lower pagination in `admin/client/components/ItemsTable.js` to the conditional `tableBody` constant would work as intended.

**Comment by mxstbr** [comment]
That is a very good catch @snowkeeper, thanks for pointing that out. I'll update the PR!

**Comment by JedWatson** [comment]
On a related note, I'd **really** like to merge the droppable-pagination implementation and the "regular" pagination if someone can figure out a neat way to do it. Having two separate implementations of the same UI is not great, and it doesn't really make sense having different rules around when and why pagination appears (or why you can use the bottom pagination in drag and drop operations but not the top)

**Comment by mxstbr** [comment]
I'll can have a look at that while I'm at it, but can't guarantee anything!

**Comment by snowkeeper** [comment]
When I put it together there did not seem to be an easy way to incorporate the required functionality into the Elemental pagination setup.  Unless I am overlooking something the options would be to update Elemental to accept custom actions or simply put drag across pages on hold for now.

For reference the action used to drag across pages is to drag the row onto a pagination link and hold for 2 seconds which triggers the page change and make the dragged row available for manipulation within the new page results.

**Comment by mxstbr** [comment]
Closing this for now as it's proven too hard (as predicted...), lets do this all in one sweep with the admin interface refactor.

**Pull request closed without merging**
