### PR TITLE
react test checkbox component

### PR DESCRIPTION
**Pull request by suryagh**
## Description of changes

Unit test for react component `<Checkbox/>`
## Testing
- [x] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, LGTM!

**Comment by mxstbr** [comment]
@suryagh I'm so sorry, I thought Jed had merged this PR! My bad, we definitely wanted this!

**Comment by suryagh** [comment]
@mxstbr Oh ok. Please merge when you or @JedWatson get a chance.

**Comment by mxstbr** [comment]
Can you rebase onto master and rename the file to `.test.js`? The we'll be good to go!

**Comment by suryagh** [comment]
@mxstbr  done.
Btw - the ci-build seems to be broken for the master branch.

**Comment by JedWatson** [comment]
Ping @bassjacob

**Comment by bassjacob** [comment]
This has fallen far behind enough that I can't use this PR to get it back up to date. @suryagh can you please rebase your branch against the current master branch?

Otherwise I'm happy to grab the code out and get this in manually.

**Comment by JedWatson** [comment]
Since this PR is out of date and doesn't look like it'll be brought forward, I'm going to close it.

**Pull request closed without merging**
