### PR TITLE
Custom Logging Middleware for v0.4

### PR DESCRIPTION
**Pull request by gmmeyer**
I would love to have the ability to define my own custom logging middleware. To be honest, I'd prefer to use Winston to Morgan, if I could.

This is a PR for v0.4 that does just this.

I allow for two different manners of defining this.

* One is through an option on the keystone init.
* One is through the normal middleware hook, so that people will be able to use their normal middleware workflow rather than putting it in a weird place.

### CODE REVIEW

**Comment by JedWatson** [comment]
Looks great @gmmeyer, thanks :)

**Comment by gmmeyer** [comment]
:)

**Comment by ericelliott** [comment]
Great addition. I'll be using this, myself. Thanks!

`\( ﾟヮﾟ)/`

**Comment by webteckie** [comment]
Docs?

**Comment by ericelliott** [comment]
:+1: for docs

**Pull request merged**
