### PR TITLE
Implements file-upload via dropzone

### LINKED ISSUE #2071: Implement markdown "file upload" feature
Using http://www.dropzonejs.com/ would allow to provide markdown editor with file uploads, specially images (when just text is not enough!) and for example, a screenshot is required for explaining something.

### PR DESCRIPTION
**Pull request by jacargentina**
This fixes #2071.

It adds dropzone js library; and also updates boostrap-markdown to v2.9.0
Also includes font-awesome for the bootstrap-markdown icons.

### CODE REVIEW

**Comment by mxstbr** [comment]
We've already got `Octicons` in Keystone, why do we need another icon pack?

**Comment by jacargentina** [comment]
As i already pointed, i was trying to use upstream bootstrap-mardown. That implies not doing nasty hacks.

From bootstrap-markdown docs:

````The icon library to use. Glyphicons (glyph) and Font Awesome (fa) are supported. In order to use Font Awesome properly, you'll need to include Font Awesome stylesheet yourself. Default to glyph
````

Maybe you would like to PR on them with adding octicons as an option?

**Comment by mxstbr** [comment]
I don't think sending down another icon set just to get drag-n-drop upload working is worth it. As much as we appreciate you taking the time to submit this PR, if there's a solution without font awesome that'd be a lot better!

**Comment by jacargentina** [comment]
It serves my need. The branch will be there as reference on my fork if someody really needs it (just works)

Cheers!

**Comment by mxstbr** [comment]
Awesome, that's great to hear! We really appreciate you taking the time to implement this, sorry if I came off a bit harsh. :+1:

**Comment by jacargentina** [comment]
@mxstbr 
Please look at this https://github.com/elementalui/elemental/pull/146 which depends also on https://github.com/toopay/bootstrap-markdown/pull/232

Also, i'm rebasing my original PR with the changes. Hope now you like it. Cheers!

**Pull request closed without merging**
