### PR TITLE
Switch Keystone.Email to use keystone-email package

### PR DESCRIPTION
**Pull request by mxstbr**
~~I'm not 100% sure how I can actually test anything works, so this is mainly a random guess at the things I should be doing. Any pointers @JedWatson?~~

/cc @Noviny

### CODE REVIEW

**Comment by mxstbr** [comment]
This is insofar ready to merge as one can actually send emails now, everything works as expected! 🎉 

There probably still is some dead code laying around here and there and I'd like to add unit tests for all of this, but generally this works more or less. Up to you @JedWatson if you want to merge this or not?

**Comment by mxstbr** [comment]
-24% test coverage?! Not sure what happened there, seems accurate though.

**Comment by JedWatson** [comment]
@mxstbr conflicts!

**Comment by JedWatson** [comment]
@mxstbr tests fail

**Comment by JedWatson** [comment]
Failing tests are unrelated, this is good to merge. Thanks @mxstbr!

**Comment by mxstbr** [comment]
:tada: :tada: :tada:

**Pull request merged**
