### PR TITLE
Fix #2423

### LINKED ISSUE #2423: Wrong autokey value
Hello

I'm trying to use the "autokey" feature to generate slugs for each blog post.
Here's how I do it :

```js
var Post = new keystone.List('Post', {
    autokey: { path: 'slug', from: 'title', unique: true },
    map: { name: 'title' },
    defaultSort: '-createdAt'
});
```

Surprisingly, it works "sometimes".
For example the "Example Of Blog Post" value for the "title" field will have the slug "example-of-blog-post". Sometimes not. It will have the value of the post ID instead.

It's very hard for me to understand how/when the autokey features works as expected. But it looks like the post ID and the autokey (source field) are sometimes mixed up.

How can I help understanding and eventually fixing this?

Regards,

### PR DESCRIPTION
**Pull request by geloescht**
Please do not merge yet, would like to include a fix, too.

### CODE REVIEW

**Comment by geloescht** [comment]
Can be merged now. Not to sure about the option autokey.ingoreIncompleteSource I introduced.

**Comment by mxstbr** [comment]
Ping @JedWatson

**Comment by JedWatson** [comment]
Looks great, @geloescht! Thanks for digging in and fixing this.

**Comment by mxstbr** [comment]
Just want to mention, thanks so much for adding a test too – that is very appreciated, we need a lot more of them!

**Comment by geloescht** [comment]
Writing the test made it so much easier to find out what was going wrong - maybe we can get people who report bugs to write a test first so keystone developers and contributors can easily squash bugs one by one? Writing tests alone is no fun, but bug reporters often already post a code example that reproduces their issue and just needs to be made into a test.

**Comment by mxstbr** [comment]
Sounds like a good idea, but the question is how many bug reporters are willing to dive into the codebase and write tests for their bug? I bet not many.

**Comment by geloescht** [comment]
I think people just need to be shown that writing a test does not mean that you have to dive into a completely foreign codebase. It's basically application code, which they are already writing if they use keystone. Learning how to use a testing framework is probably the biggest hurdle.
Another thing is that most bugs in keystone are in client / browser code, which seems very hard to write tests for. At least I personally got no clue of how to do that.

**Comment by webteckie** [comment]
@geloescht regarding browser testing we are doing that too.  It's probably a bigger learning curve than writing unit tests but we are trying to put a pattern to it so it's not that difficult to add to.  Right now it is in shambles since we are going through a refactoring but soon should be in reasonable shape again.   And we are willing to help explain how-to if the README is not enough :-)

**Pull request merged**
