### PR TITLE
test(e2e): use improved po api

### PR DESCRIPTION
**Pull request by jstockwin**
## Description of changes

These changes are all @webteckie really, I just finished off the refactoring so am making the PR. 

Following updates in the `keystone-nightwatch-e2e` package we've refactored keystone's tests to use the new API. @webteckie may be able to provide more details...

Travis _should_ pass.

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by jstockwin** [comment]
@JedWatson Tests are only failing because of saucelabs. The push one passes, so if saucelabs wasn't erroring (too many active tunnels) then we'd be passing. Can you merge this please?

**Comment by jstockwin** [comment]
Slight update, so wait and see if tests pass again...

**Comment by jstockwin** [comment]
I've just added some more work to this PR, which adds the use of a default config option, and makes the code quite a bit cleaner. cc @webteckie.

**Comment by jstockwin** [comment]
@JedWatson This PR now contains all of mine and Webteckie's work. Tests are passing. Please merge.

**Comment by JedWatson** [comment]
Great, thanks @jstockwin and @webteckie!

**Pull request merged**
