### PR TITLE
Update hooks.md

### PR DESCRIPTION
**Pull request by bartduisters**
Remove redundant word

### CODE REVIEW

**Comment by chrisleyva** [comment]
Can you include this change as part of PR #2178?
As an idea, just make one Pull Request with all of your linting, formatting, grammar corrections to the `hooks.md` file?

**Comment by bartduisters** [comment]
If you prefer I can put them all in one PR tomorrow. I just click edit - do the change - open PR as I read the document.

I'll keep it in mind for the rest of the documentation.

**Comment by chrisleyva** [comment]
> If you prefer I can put them all in one PR tomorrow. I just click edit - do the change - open PR as I read the document.
> 
> I'll keep it in mind for the rest of the documentation.

Oh, I understand. In that case, don't worry. I'm not a maintainer or anything on this project, just offering some suggestions.

**Comment by timleslie** [comment]
Yeah, a single PR will make things easier for us on the maintenance side, but unless things start to get out of control I'm happy to take the changes one at a time. The overhead of pulling down the code and doing a bunch of changes in a single PR is way higher than the few buttons we need to click to merge the small PRs as they come through :-)

**Pull request merged**
