### PR TITLE
Support for mailgun

### PR DESCRIPTION
**Pull request by w01fgang**
addition to #250 
This PR adds support for [Mailgun](https://mailgun.com), alternative for Mandrill, with 10 000 free emails monthly and 5 domains for free.
Also css styles will be inlined as on Mandrill.
This is not Nodemailer, but it is the fastest solution for migrate from Mandrill.

Usage:
keystone.set('email transport', 'mailgun');
keystone.set('mailgun api key', 'key-xxxxxxxxxxx');
keystone.set('mailgun domain', 'example.com');

If these params didn't configure the Mandrill will used.

And another: I have changed selecting of the email template engine from global config, I think it's more understandable and not hardcoded as it was.

### CODE REVIEW

**Comment by mxstbr** [comment]
This looks good to me code-wise, but I'm not proficient in the mailing setup of Keystone. @JedWatson?

**Comment by JedWatson** [comment]
Looks great @w01fgang, thanks!

**Comment by remnev** [comment]
Thank you very much. Please release it with a version tag. It is very necessary right now.

**Comment by mxstbr** [comment]
You're right @remnev, we should probably release that as another 0.3.x release. @w01fgang could you remake this PR against the `0.3.x` branch?

**Comment by w01fgang** [comment]
@mxstbr Ok, I will do it.

**Comment by remnev** [comment]
@w01fgang please...

**Comment by w01fgang** [comment]
PR #2752 was merged on v3.0.x

**Comment by remnev** [comment]
@w01fgang thanks. @mxstbr please release new version of 0.3.x

**Comment by mxstbr** [comment]
@remnev will do as soon as possible. Is it mission critical for an app of yours?

**Comment by remnev** [comment]
@mxstbr yes, mandrill doesn't work. My service can't send emails... It's critical issue.

**Comment by mxstbr** [comment]
Released as 0.3.19!

**Comment by remnev** [comment]
Thank you very much!

**Comment by mxstbr** [comment]
Needs some documentation: https://github.com/keystonejs/keystonejs-site/issues/111

**Comment by TSFoster** [comment]
Hi,

v0.3.19 doesn't seem to have Mailgun support (see [v0.3.19's lib/email.js](https://github.com/keystonejs/keystone/blob/v0.3.19/lib/email.js)). Can you release a version that includes this PR?

Thanks,  
Toby

**Comment by mxstbr** [comment]
#2752 added Mailgun support for the `0.3.x` versions, and shortly thereafter we released `0.3.19` to include it.

We tagged the wrong commit on Github, my bad, but `0.3.19` includes Mailgun support!

**Comment by creynders** [comment]
@mxstbr I'm definitely not a fan of moving tags, but shouldn't it be re-referenced? This is _VERY_ confusing.

**Comment by mxstbr** [comment]
Tags can't be moved, otherwise I would've already done it. Not a big fan of that mistake either, but can't change it.

Will add a comment explaining it to the release!

**Comment by mxstbr** [comment]
Added to the tag description: https://github.com/keystonejs/keystone/releases/tag/v0.3.19

**Comment by TSFoster** [comment]
Ok, thanks for explaining!

I have two Keystone projects, `npm info keystone version` returns `0.3.19` on both projects, but one has Mailgun support and the other doesn't. Did npm originally install the wrong v0.3.19 (a week or two ago), but now it installs the right one?

**Comment by mxstbr** [comment]
No, npm is immutable so `0.3.19` will always refer to the same version.

**Comment by creynders** [comment]
@Mxstbr yeah you can't move it, but you can delete and create a new one

**Pull request merged**
