### PR TITLE
Authentication hooks

### PR DESCRIPTION
**Pull request by molomby**
Implementing authentication hooks to lists as per #2001.

Starting with docs to formalise/get agreement on the spec.

### CODE REVIEW

**Comment by timleslie** [comment]
I'm a 👍 on these APIs.

**Comment by Vultraz** [comment]
Quick aside since you're editing that file. The current Apollo Context link in the Hooks API docs is broken. The new link is `https://www.apollographql.com/docs/apollo-server/data/data/#context-argument`.

**Comment by molomby** [comment]
@Vultraz indeed it is! I've fixed them already in [this branch](https://github.com/keystonejs/keystone/commit/048c0d6579575820b376056d86bc88579a432491) but that's all caught up in #2041. I'll fix it here too.

**Comment by timleslie** [comment]
Just making a note there that the new providers API (#2418) might have implications to some of thing things outlined here.

**Comment by gautamsi** [comment]
@timleslie just curious if this list will be another `List type` (Auth list type) along the line of recent list type refactoring?

if that is the case, I guess we can have split page in documentation for each type of list, right?

**Comment by timleslie** [comment]
> @timleslie just curious if this list will be another `List type` (Auth list type) along the line of recent list type refactoring?
> 
> if that is the case, I guess we can have split page in documentation for each type of list, right?

This won't be a separate list type, this will just be adding a `hooks` parameter to `keystone.createAuthStrategy()` method. Under the hood this method uses a separate `provider` to generate the GraphQL, but it's a slightly different thing to a `List type`.

**Comment by adrianbienias** [comment]
I'd love to use those auth hooks. How come I don't see anything in docs about them?

**Pull request merged**
