### PR TITLE
Support for using a custom admin path

### PR DESCRIPTION
**Pull request by jonathanp**
This PR adds support for using a custom path to the admin UI, as discussed in #627.

If I would want to to use e.g. `/foobar` instead of `/keystone` as the path to the admin UI I would need to add the `admin path` config parameter to the `keystone.init()` call, as such:

```
keystone.init({
	'admin path': 'foobar'
});
```

I think this PR needs to be thoroughly reviewed as there's alot of files involved, but it should be feature complete AFAICT.

### CODE REVIEW

**Comment by celiao** [comment]
Is the documentation updated too?

**Comment by jonathanp** [comment]
@celiao Not yet

**Comment by jonathanp** [comment]
@JedWatson have you had any chance to look at this yet? :)

**Comment by JedWatson** [comment]
Sorry for the delay @jonathanp - have been travelling a lot lately & wanted some focus time to review this.

Looks great :+1:

The only thing I might change about it is passing the `adminPath` prop through components - seems like the code structure would be cleaner (and easier to refactor) if we referred to the `Keystone` global inside the components, rather than passing the prop down through the component hierarchy?

If you think it's better / clearer with props, I'm happy to merge as-is.

There are also some conflicts, I think it's just the changes to the links in the footer, would you mind updating your branch? Thanks!

**Comment by jonathanp** [comment]
Thanks, it's rebased now!

I agree, the passing down of `adminPath` through the component tree feels a bit weird but I think I prefer that than to reference a global from inside of the components. I think it's good to keep them as pure (only dependent on their own props) as possible.

**Comment by JedWatson** [comment]
Oh man, sorry about this - conflicts again. Master is moving fast at the moment... can I get one more rebase? I'll merge as soon as it lands so we break the cycle :)

**Comment by jonathanp** [comment]
Haha np, rebased now!

**Comment by JedWatson** [comment]
...and we're done!

Thanks :)

**Comment by jonathanp** [comment]
:boom:

**Comment by ipengyo** [comment]
this pr  Currently in which version is valid ？
@joerter

**Comment by morenoh149** [comment]
@ipengyo this was merged into master. So it's probably available in the 0.4.x line.

**Comment by tomheathershub** [comment]
Is it possible to have no admin slug or in other words have keystone run off the base url of the domain name ? e.g tomscms.co.uk/signin

**Comment by wmertens** [comment]
@tomheathershub try it, there's a good chance it will work.

**Comment by flzozaya** [comment]
Since this is now implemented as an option for `keystone.init();`, maybe it should be added to the docs?? 😄 . 
There is no mention regarding this anywhere on the Keystone Documentation page.

**Pull request merged**
