### PR TITLE
typo on getting started

### PR DESCRIPTION
**Pull request by kud**

### CODE REVIEW

**Comment by timleslie** [comment]
Hey @kud, thanks for the PR. We've got a few changes in flight with the website at the moment so we're gong to hold off on merging this PR until early next week once everything has settled down at bit 👍

**Review by timleslie — CHANGES_REQUESTED** [review]
Marking as `Request changes` to avoid merging before next Monday when the larger website changes have landed.

**Comment by kud** [comment]
Sure, no worries. 😊

**Comment by timleslie** [comment]
This fix was applied as part of the website update. Thanks @kud

**Comment by kud** [comment]
🙌🏻

**Pull request closed without merging**
