### PR TITLE
Fix signin custom redirect + test

### PR DESCRIPTION
**Pull request by Rmannn**
See #2326

### CODE REVIEW

**Comment by morenoh149** [comment]
`Uncaught MongoError: ns not found` are we seeing this elsewhere @webteckie

**Comment by JedWatson** [comment]
Good catch + fix @Rmannn, thanks!

Not sure what's up with our tests, going to run them locally...

**Comment by webteckie** [comment]
@JedWatson  I just fixed the travis issue.  It's a bit crazy...the test have been running fine for weeks and all of a sudden they fail.  There was a piece of logic I had added to one of the tests to fix some related issues a few weeks go...now that same logic had to be removed to make the tests pass again...weird...if the pattern continues, I'm expecting a few weeks from now we'll need to add the logic back again to fix them again :-)

**Comment by webteckie** [comment]
@Rmannn thanks for adding the e2e test...hopefully there's more of that coming with all other PRs :-)

**Comment by Rmannn** [comment]
You're welcome guys, it's really cool to work with keystone. I also just discovered the e2e test. Very interesting.

**Comment by webteckie** [comment]
@Rmannn regarding e2e feel free to contribute more (see #2291)  Lots to do!

**Pull request merged**
