### PR TITLE
Better error messages when unique validation fails (mongodb)

### LINKED ISSUE #433: Surface isUnique constraint errors in Admin UI
Dependent on #431

When attempting to create an item which violates a `unique` constraint, the Admin UI does not surface any errors:

unique-no-error

Similarly for `update` mutations.

### PR DESCRIPTION
**Pull request by Vultraz**
Should close #433 since the error appears.

This utilizes [mongoose-unique-validator](https://www.npmjs.com/package/mongoose-unique-validator) as a global schema plugin. Test done with a unique URL field.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by MadeByMike** [comment]
Thanks Charles you're on fire! This is good but won't close #433 as I believe that's more about having a visual indication in the UI.

**Comment by MadeByMike** [comment]
Looks like this breaks one of our CI test :(

**Comment by Vultraz** [comment]
Ok, now a linter task is failing? Wat

**Comment by Vultraz** [comment]
@MadeByMike Fixed (besides the unrelated random failure)! Also fixed the deprecation warning about `testResultsProcessor` at the end of the tests.

**Pull request merged**
