### PR TITLE
Adding req to singin hook

### PR DESCRIPTION
**Pull request by OskarKlintrot**
## Description of changes
I missed this place in PR #3950, sorry. 

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
I also noticed an unrelated issue here (I think). This hook is located *before* the signin process whilst the other hook is located *inside* the signin process. This creates an inconsistent behavior. Is this by design or should I open an issue?

**Comment by creynders** [comment]
Ow... there's 2 `session` files now? This seems pretty bad, it's not DRY and makes things error prone. I think it'll need it a refactor.

**Comment by OskarKlintrot** [comment]
If I understand it correct ([and the way I am using this `session.js`](https://github.com/Certaincy/intranet/blob/master/keystone/src/auth/api/signin.ts#L24)) is that one of them is for the keystone admin and the other one is to be used when you are opening up the api. Not very DRY, I agree.

**Comment by JedWatson** [comment]
Agreed with the DRY issue... It happened this way to avoid a breaking change in the API while updating the way the Admin UI signing works. Not ideal - we'll address that after 4.0 is released.

Thanks @OskarKlintrot!

**Pull request merged**
