### PR TITLE
fix regression with admin path and sortable

### PR DESCRIPTION
**Pull request by snowkeeper**

### CODE REVIEW

**Comment by ericelliott** [comment]
Is there a good way to test this regression?

**Comment by JedWatson** [comment]
Good question @ericelliott - might be something for integration / UI tests? testing drag and drop programatically sounds like black magic to me, the `react-dnd` repo might hold some clues though

**Comment by snowkeeper** [comment]
Once I realized I still had the hard code value I ran some greps like this to find others...
<kbd>grep --exclude-dir={node_modules} -rnw --include=*.js . -e "/keystone" >> ../grepList.txt</kbd>

**Comment by ericelliott** [comment]
> might be something for integration / UI tests?

Yeah, I've been intrigued by a new functional test library that we might be able to put to good use on UI tests. I'll experiment with it in the Universal Keystone Boilerplate and then we'll consider pulling a more polished functional test suite into the Keystone repo. =)

**Comment by morenoh149** [comment]
nightwatch vs the intern @.@

**Pull request merged**
