### PR TITLE
Fixing sortOrder init on item create

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
fix for #1007

### CODE REVIEW

**Comment by JedWatson** [comment]
I'm happy to go with this, @JohnnyEstilles. #634 will be a problem again, however I'm happy (for now) to live with that limitation. Maybe we can come up with a better way of fixing the original issue...

**Comment by JohnnyEstilles** [comment]
@JedWatson ... The problem is that #634 "apparently" solved the issue because it didn't save the `sortOrder` at all during the `pre save hook`. Can you explain the use-case that caused the issue with #634, so that I can try to come up with a more permanent solution?

**Comment by JedWatson** [comment]
Yes - #634 was bunk :(

The use-case is that if you do a selective load of the document from the database (e.g. `model.find().select('_id').exec(...)`) then `sortOrder` won't be a number, and it'll be defaulted, overwriting the actual value.

So this is an issue whenever you partially load a document that *has* a sortOrder, don't load `sortOrder` itself, update the document and write it back to the database.

Maybe we can use the `isNew` special mongoose functionality to fix this more reliably - or maybe we can detect whether a document has only been selectively retrieved and just doesn't have the `sortOrder` path populated.

**Comment by JohnnyEstilles** [comment]
`isNew` seems like it would do the trick ... I'll do some testing ...

**Pull request merged**
