### PR TITLE
Added helmet for security

### PR DESCRIPTION
**Pull request by VinayaSathyanarayana**
## Description of changes
Added helmet for enhanced security
var helmet = require('helmet');
var app = express();
app.use(helmet());

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by VinayaSathyanarayana** [comment]
@JedWatson - Please consider this PR

**Comment by mxstbr** [comment]
@josephg you might have a better idea if we want this?

**Comment by josephg** [comment]
Err, this does a lot of things we don't want. For example, enabling HSTS means the entire site will *require* https, and stop loading via straight HTTP. We don't want to just do that on behalf of users. (And yes, that will happen even if only the admin site is served with HSTS cookies).

**Comment by josephg** [comment]
`HPKP` makes it difficult / impossible to rotate SSL keys unless you set up your SSL keys in a particular way. `nocache` is ... probably good for most routes in the admin UI, but we want the admin JS and some of the static assets to be cached. I think the other stuff might be ok, but as much as I'd like to we can't accept this PR as-is. Not without a lot of consultation with users.

There's a reason browsers can't silently make these behaviours the default for existing sites.

**Comment by mxstbr** [comment]
Alright, I'll close this for now – let's discuss in an issue!

**Pull request closed without merging**
