### PR TITLE
Markdown cloudinary integration

### PR DESCRIPTION
**Pull request by cadwmaster**

### CODE REVIEW

**Comment by morenoh149** [comment]
@cadwmaster wow good job. What does this do?

**Comment by JedWatson** [comment]
Nice! Could you resubmit without the rebuilt app.js though? We're going to get conflicts on that.

If you can remove that from the PR I'll merge this and rebuild it with the other changes in master.

Cheers!

**Comment by cadwmaster** [comment]
Ok, now the app.js file isn't there.

Cheers

**Comment by JedWatson** [comment]
@cadwmaster git now things you're _deleting_ the `app.js` file as part of your commit, which you're not. You need to revert changes on it or I can't merge this due to conflicts :(

**Pull request closed without merging**
