### PR TITLE
Added branding/custom logo to Signout page of app-admin-ui

### PR DESCRIPTION
**Pull request by nyinyinyanlin**
Changes from @Vultraz PR #2474 has left to add custom branding logo to signout page. Made a minor change on signout page similar to signin page.

### CODE REVIEW

**Comment by Vultraz** [comment]
Ah, I didn't add the change to the signout page since I have an open PR (#2471) that redesigns it and removes the logo. Just waiting for it to get approved.

**Comment by nyinyinyanlin** [comment]
@Vultraz I didn't aware your separate PR. I will close this PR then. Thank you!

**Comment by nyinyinyanlin** [comment]
@Vultraz can you tell me how do I push my local changes to Heroku production server? Until your PR's been merged, I need to show branding logo on signout page for my project. Heroku fetches packages by reading package.json or yarn.lock as I understand. Any way to have it use my locally changed package? Thank you!

**Comment by Vultraz** [comment]
Sorry, I don't know anything about Heroku 😬 But hopefully my PR will be merged soon.

**Comment by Vultraz** [comment]
#2471 was just merged. It will be in the next release.

**Comment by nyinyinyanlin** [comment]
@Vultraz Thank you for your great work. How do I pull new changes? `yarn upgrade`?

**Comment by Vultraz** [comment]
Yes, but after the release actually ships. Wait for #2788 to be merged.

**Pull request closed without merging**
