### PR TITLE
#3011 | Fix Date format option bug

### PR DESCRIPTION
**Pull request by autoboxer**
## Description of changes

- Update the Date field, type definition, and DateInput component to display the selected format for any date selected.
- Update the placeholder for Date fields to display 'e.g.' before a formatted version of today's date.
- Update the Date field to not show placeholder text when format is set to false.

## Related issues

#3011

## Testing

No unit tests were written as the change is on the v0.3.x branch.

### CODE REVIEW

**Comment by JedWatson** [comment]
Looks good to me, @autoboxer - thanks!

**Comment by davideberlein** [comment]
@JedWatson This is a major issue that I also stumbled over in 0.3.21. Date input is totally broken as soon as you specify a date format different from the default. 
Can't we have a 0.3.22 release for this please??

**Comment by autoboxer** [comment]
Sadly I'm not sure how actively issues are being monitored and the repo is being updated.  I've tried reaching out to the team many times over the last year to help with issues, have pull requests merged, and get back on the team Slack channel, but have gotten no response.  I believe @JedWatson is understandably much more hands off as he had a child recently, and the rest of the core contributors don't seem to be paying attention.

That being said, you can reference this commit fairly safely as there doesn't seem to be any activity on the 0.3.x branch these days by changing your keystone reference in *package.json* to read:

`"keystone": "https://github.com/keystonejs/keystone.git#c38b366c7b1bf01448c8ece7c36e1bb6eb195186",`

**Comment by Noviny** [comment]
Just to clarify a point @davibe, and @autoboxer we are not planning to cut any more releases of the v0.3 branch. I'd recommend upgrading to the v4 beta, of which there is an upgrade guide here: http://keystonejs.netlify.com/guides/v-0-3-to-v-4-0-upgrade-guide

**Comment by davideberlein** [comment]
@Noviny I understand that you don't want to further develop 0.3 and back-port bugfixes done for v4. However this is a major bug in a released version in 0.3.21 which IS actually fixed on the 0.3 branch!
Why the heck not do a 0.3.22 release to address this and avoid others that are on 0.3.x to run into the same problem? This does not make any sense to me.
Not every project has the time and resources for a major version migration...

**Comment by Noviny** [comment]
@davideberlein That's fair. Going talk with others on Monday to see if we can do one final release of 0.3 for those who are still using it, alongside cutting a new beta (as master has moved on some from the last one, mostly with incremental improvements).

We'd need to do both at once, to keep the most recent version accurate.

Can't guarantee we will do this, but will make sure we have the conversation.

**Comment by davideberlein** [comment]
thanks @Noviny !

**Comment by autoboxer** [comment]
I chose Keystone almost 4 years ago for a massive rebuild of the entire infrastructure at a local adoption agency I elected to help them build since they couldn't afford the development costs.  I've taken a look at v4, and with our deadline only a few months away, I don't have the luxury or upgrading since some of the changes made on 0.3x were never ported up.  In addition, some basic things like Cloudinary Image fields don't operate correctly.  I've attempted to talk to the development team literally for a year about this and regain access to the Slack channel, and no one over there being pestered by myself and a friend of mine has helped or reached out.  I've actively contributed in the past, and would happily do so in the future, but I have to say I share the concern above that new fixes aren't being added.  The current version (v4) doesn't seem to be finished, so to cut off releases for a working branch that is actively used seems irresponsible.  I understand the time cost of maintaining free software for others to use, and I have a high level of respect for those that do it, so please don't misconstrue my message as rude, it was only meant to be frank.

**Comment by Noviny** [comment]
@davibe Just checking back in after talking to others. We are likely going to release a definitive final 0.3 release for those who need it, and announce that we are officially not supporting it. I'll check back on here once I've got that done.

**Comment by autoboxer** [comment]
Thanks for taking action @Noviny, it's much appreciated.

**Comment by davideberlein** [comment]
@Noviny any eta on 0.3.22?

**Comment by Noviny** [comment]
@davideberlein Aiming for by Friday.

**Comment by davideberlein** [comment]
great!

**Comment by davideberlein** [comment]
@Noviny Any updates on the release date?

**Comment by davideberlein** [comment]
@Noviny @JedWatson Is there something I can do to make this release happen?
I am still waiting for it...

**Pull request merged**
