### PR TITLE
Allow whitelisting lists for anonymous access

### PR DESCRIPTION
**Pull request by wmertens**
Thoughts? Real quick hack without doc change, I'd be happy to add docs if you like this.

Basically I'm serving a single page app with Keystone and I need access to some lists without users logging in.

### CODE REVIEW

**Comment by creynders** [comment]
Hi Wout, nice to see you here :) It's been a loooooong time!
I'm :+1: for the idea, however not sure about the name `anon api`. Also, there's some code style problems. You can run `npm lint` to check whether your code changes pass the code style specs of keystone.

**Comment by wmertens** [comment]
Hi Camille, the world is small :)

Any other names that would be more appropriate? `open models`? `world readable`?

Another thing I don't really like about this code is that it builds a regex on every invocation but I don't see a way to initialize one. I suppose I could store the regex in scope and lazily create it... Any guarantees about the keystone configuration remaining static during the run?

**Comment by wmertens** [comment]
Renamed to `world readable`, thoughts?

* In the current implementation the names can be regexes, that's ok right?
* I couldn't find any tests to amend?

**Comment by wmertens** [comment]
@creynders ping?

On Wed, Sep 9, 2015, 14:58 creynders <notifications@github.com> wrote:

> Hi Wout, nice to see you here :) It's been a loooooong time!
> I'm [image: :+1:] for the idea, however not sure about the name anon api.
> Also, there's some code style problems. You can run npm lint to check
> whether your code changes pass the code style specs of keystone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/pull/1664#issuecomment-138901778>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by wmertens** [comment]
@creynders just pointing out that the lint errors are not from my code :)

**Comment by morenoh149** [comment]
@wmertens mind documenting it as well at https://github.com/keystonejs/keystonejs-site code looks fine to me

**Comment by creynders** [comment]
@wmertens sorry for the long wait. Yes, you're quite right, I hadn't noticed travis failed on totally unrelated code. 
I'm no fan of "world readable" either, IMO it's all too opaque. We should somehow communicate it whitelists anonymous access through the API to specific lists. How 'bout "api whitelist"? or "api anon access"? @JedWatson any thoughts?

**Comment by wmertens** [comment]
I like "api whitelist", it says it all

On Fri, Sep 18, 2015 at 10:18 AM creynders <notifications@github.com> wrote:

> @wmertens <https://github.com/wmertens> sorry for the long wait. Yes,
> you're quite right, I hadn't noticed travis failed on totally unrelated
> code.
> I'm no fan of "world readable" either, IMO it's all too opaque. We should
> somehow communicate it whitelists anonymous access through the API to
> specific lists. How 'bout "api whitelist"? or "api anon access"?
> @JedWatson <https://github.com/JedWatson> any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/pull/1664#issuecomment-141378700>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by creynders** [comment]
@wmertens could you update your PR to use `api whitelist`? And rebase on master?

**Comment by wmertens** [comment]
@creynders @morenoh149 I changed the setting name, and I memoized the regexes.

I also make it return a 403 instead of a redirect for disallowed API accesses, to be nicer to ajax clients.

**Comment by creynders** [comment]
LGTM!

**Comment by wmertens** [comment]
Anything still missing for getting this merged? Docs are there as well...

**Comment by webteckie** [comment]
@wmertens I'm curious, couldn't the same thing be accomplished via CORS, which KeystoneJS already supports?

**Comment by wmertens** [comment]
No, CORS is for allowing access to the data from other sites than your own.

This PR is for allowing access to the data without having to authenticate.

On Sat, Oct 3, 2015, 16:51 Carlos Colon <notifications@github.com> wrote:

> @wmertens <https://github.com/wmertens> I'm curious, couldn't the same
> thing be accomplished via CORS, which KeystoneJS already supports?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/pull/1664#issuecomment-145254349>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by JedWatson** [comment]
@wmertens sorry for the delayed response & merge. I've been trying to work out how this fits in with my broader plans to expose API endpoints from the new Admin UI, to make sure it doesn't create a feature we have to roll back from. Going to spend quite a bit of time on the API in the next day or so, and won't leave this hanging much longer.

The PR itself is great, thanks for getting in and making it happen :+1:

**Comment by wmertens** [comment]
Since we're on the subject of API expansion, I wonder if it would be a good
idea to expose calculated views as endpoints, for example the list of blog
posts sorted by publication date, but only the ones that have publication
date < now and state "published".

Right now, to do that, you have to write a custom route, correct? But such
a view really only needs to know the endpoint name and the mongoose query
configuration…

On Mon, Oct 5, 2015 at 7:01 AM Jed Watson <notifications@github.com> wrote:

> @wmertens <https://github.com/wmertens> sorry for the delayed response &
> merge. I've been trying to work out how this fits in with my broader plans
> to expose API endpoints from the new Admin UI, to make sure it doesn't
> create a feature we have to roll back from. Going to spend quite a bit of
> time on the API in the next day or so, and won't leave this hanging much
> longer.
>
> The PR itself is great, thanks for getting in and making it happen [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/pull/1664#issuecomment-145430659>.
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by JedWatson** [comment]
I'm basically thinking of making the exposition of API endpoints explicit, but the configuration _really_ simple.

So something like this (_really, really draft_)

```
app.get('/api/posts/:page', Keystone.list('Post').getAPI({
  sort: '-createdAt',
  filters: { published: true },
  populate: 'author',
  pageSize: 10
});
```

You could extend it easily by adding custom `transform` methods, field white/black lists, and configure the rules for the endpoints separately (e.g. with the `List` if you wanted) so they're encapsulated, etc.

This lines up specifically with the new work being done for the Admin UI API; see https://github.com/keystonejs/keystone/blob/master/admin/api/list/get.js

It's also laying the groundwork for `POST` / etc. API generation to replace the old `UpdateHandler` concept.

Then we can have simpler, higher-level flags that expose default API endpoints for lists, as in this PR, if they're valuable.

**Comment by JedWatson** [comment]
Extending on that idea you could also provide a function to `filters` that would be able to parse supported filters for custom logic to build up the query; or, as in the example above, you could support filters that are added (not overriding) the predefined ones.

**Comment by wmertens** [comment]
Nice!

How about letting that endpoint factory also handle authentication
```
app.get('/api/posts/:page', Keystone.list('Post').getAPI({
  sort: '-createdAt',
  filters: { state: 'published', publishedAt: { $lte: Date.now() } },
  populate: 'author',
  open: true,
  pageSize: 10
});
```
So you can define the authorization per view.

This would indeed be a much nicer and explicit API than the hackish one in this PR.

**Comment by JedWatson** [comment]
@wmertens I'm thinking authentication would be handled by the express middleware (which could also be encapsulated), e.g.

```
// open API
app.get('/api/users/:page', Keystone.list('User').getAPI({
  // ...
  exclude: 'isAdmin, password, mySecretField'
}));

// private API
app.get('/api/admin/users/:page', middleware.restrictToAdmins, Keystone.list('User').getAPI({
  // ...
  exclude: 'password'
}));
```

**Comment by creynders** [comment]
@JedWatson I've been working on a new version of `restful-keystone` with a new fluent API for setting everything up, i.e. I've been thinking about these things a lot. Do you have a moment later on today to exchange some ideas on slack? There's a number of things I've encountered when creating restful, which are easily overlooked and would be good to get right in Keystone when creating `getAPI`.
I should have some time in 3 hours.

**Comment by JedWatson** [comment]
@creynders nice, would love to chat. I'm about to head out for dinner but I'll be around in about 4 hours? I'll ping you then. I've also created a placeholder in #1705 (for updating) and a more fully thought-out #1585 (for get) that you're welcome to put some notes on if you like!

**Comment by LorbusChris** [comment]
Oh great, been looking this! Thanks, @wmertens! :)

Just one thing that was probably not even possible last year, but would you mind updating the PR so that it supports for custom admin paths?

@JedWatson any chance this will get merged in the not-too-distant future?

**Comment by wmertens** [comment]
@LorbusChris actually, this will not get merged, since it is not a very clean approach. I should probably close this, right @JedWatson ?

**Comment by LorbusChris** [comment]
@wmertens Thanks for the heads up! 

Are there any other known workarounds for the time being?

**Comment by JedWatson** [comment]
@wmertens yep 🙂 

@LorbusChris going to revisit the concept of exposing an API automatically from Keystone in the new year, I'll ping you when we get a draft in place.

**Pull request closed without merging**
