### PR TITLE
Ensure select uses string as a default datatype

### PR DESCRIPTION
**Pull request by timleslie**
This will minimise the impact of the change made in #5217.

### CODE REVIEW

**Review by JedWatson — CHANGES_REQUESTED** [review]
Should update the changelog from #5217 to be a minor now, right?

**Comment by timleslie** [comment]
> Should update the changelog from #5217 to be a minor now, right?

Perhaps? Everything is getting majored next release anyway.

**Comment by JedWatson** [comment]
I'd also update the change entry

> Fixed the `select` field type to always use the correct underlying types.

that's really not a good description, it's something more like

**Select now uses the correct underlying type, allowing use of `Enum` and `Integer`  types again**

**Review by JedWatson — APPROVED** [review]

**Comment by JedWatson** [comment]
Much better, thanks 👍

**Pull request merged**
