### PR TITLE
Version Packages (CKA)

### PR DESCRIPTION
**Pull request by dcousens**
Follow up to https://github.com/keystonejs/keystone/pull/9312

This will bundled under yesterdays release for brevity.

### CODE REVIEW

**Comment by sarzen** [comment]
Still the same kind of error, despite the update create-keystone-app@10.0.2 , which is clearly neglected by the main installation script.   Very frustrating... 👎 

image

**Comment by dcousens** [comment]
@sarzen how did you end up with a post-install https://github.com/keystonejs/keystone/blob/main/packages/create/starter/package.json?

**Comment by sarzen** [comment]
Hi @dcousens , now I am far away from the machine where I've got the error, so I can't check the details.
But I've just tried to redo all the installation steps on a new machine, and it succeeded!

I suppose my problem on the first machine was due to an older create-keystone-app module version, which was kept in modules cache at %USERPROFILE%\AppData\Local\npm-cache\_npx\ etc.

I could confirm my hypotesis within a few day.
Thank you, for now.

**Comment by dcousens** [comment]
Thanks for confirming that @sarzen :blue_heart:

**Pull request merged**
