### PR TITLE
Get the e2e tests passing again

### PR DESCRIPTION
**Pull request by jstockwin**
## Description of changes

As requested, got the e2e tests working again.

- Cherry-picked some testing commits from master.
- Added a few `data-e2e-...` and `data-button-type` attributes to make things identifiable from the e2e side of things.
- Fixed the `htmlFor` not working in some places
- Updated `keystone-nightwatch-e2e` to new version with corresponding updates.

Tests are now passing: https://travis-ci.org/jstockwin/keystone/builds/172922170

## Related issues (if any)
Testing is failing.

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by jstockwin** [comment]
cc @JedWatson and @jossmac

**Comment by jossmac** [comment]
Awesome stuff @jstockwin! Thank you for taking the time to do this

**Comment by jstockwin** [comment]
No problem, we're keen to keep e2e working, but it shouldn't be delaying work being merged. If it's every an issue just shout and I'll take a look when I can!

**Comment by jstockwin** [comment]
@jed / @joss I've updated this to resolve conflicts. The merge seemed to break a path to elemental, which I've fixed in an additional commit (please sanity check this change).

The PR build given here won't actually run e2e since this PR is coming from a fork, but I'm running Travis myself on my fork, and that'll run everything. Therefore, wait until [this build](https://travis-ci.org/jstockwin/keystone/builds/173896174) has passed before merging.

**Comment by jed** [comment]
great, @jstockwin. thanks for this!

**Comment by jstockwin** [comment]
And something broke, so one more build. Instead of the above link, please wait until [this new build](https://travis-ci.org/jstockwin/keystone/builds/173898216) has passed before merging.

**Comment by jstockwin** [comment]
My bad, sorry @jed. Hope all is well. 

@JedWatson please see the above.

**Comment by jstockwin** [comment]
Likewise, @jossmac.... You guys really need to have your slack names the same as your github usernames!

**Comment by jstockwin** [comment]
@JedWatson / @jossmac This is good to merge ([passing build](https://travis-ci.org/jstockwin/keystone/builds/173898216)).

**Comment by jossmac** [comment]
@jstockwin just updated Keystone Slack team username 😉 

@JedWatson LGTM, happy to merge if you are

**Comment by JedWatson** [comment]
🎉

**Pull request merged**
