### PR TITLE
Fix all the redux bugs

### LINKED ISSUE #3284: [0.4] It is possible to create an item in nocreate list
I tried to create an "Item" field instead of classic List according to https://github.com/keystonejs/keystone/issues/1522 (the route trick mentioned [here](https://gist.github.com/jeffreypriebe/f093c81c83d7ac5166b3) is quite outdated).

Anyway I keep my List nocreate and nodelete:
```javascript
var homepage = new keystone.List('Homepage', {
    nocreate: true,
    nodelete: true,
    ...
})
```

but it is possible to create a new item in this list through admin homepage.

Keystone - nocreate

### LINKED ISSUE #3357: Removing ?search for URL in Lists doesn't clear the search
### Steps to reproduce the behavior

Go to the list view, enter some search text. Click the navigation item for the same list, which will reset the URL and remove the `?search=text`.

### Expected behaviour

The search is reset, and all results are displayed.

### Actual behaviour

Nothing happens.

### LINKED ISSUE #3369: Navigating back to list sometimes hangs
### Steps to reproduce the behavior
1. `node test/e2e/server.js --notest`
1. go to any List, create an item
1. click on the back to list link

### Expected behavior
* Back at list

### Actual behavior
* Spinner never stops

Redux actions:
image
(the export button didn't work :( )

### PR DESCRIPTION
**Pull request by mxstbr**
Fixes #3369 
Fixes #3357 
Fixes #3284 
Fixes pagination bug where the page wasn't highlighted when directly navigating to `list?page=4`
General UI improvements

### CODE REVIEW

**Comment by mxstbr** [comment]
Only CI failures unrelated to this PR! (cc @jstockwin @webteckie)

Good to merge :shipit:

**Comment by jstockwin** [comment]
@mxstbr Not sure why this is failing... master is currently green. Unless this is pulled from an old version of master, in which case cherry-picking the following commit might fix. 
https://github.com/keystonejs/keystone/commit/4c7c6c5a676c4c2d9a68f1078f941020fcdc307b

**Comment by mxstbr** [comment]
Need to resolve conflicts anyway, will merge master in!

**Comment by mxstbr** [comment]
**Test failures are, in fact, related to this PR!**

We missed the usecase of clicking on the secondary nav list item from the ItemView @gwyneplaine, which now doesn't work anymore! Will fix tomorrow.

**Comment by mxstbr** [comment]
Thanks to @jstockwin's help this is now finally **READY TO MERGE**! :shipit: (this time for real)

**Pull request merged**
