### PR TITLE
[WIP] Update API docs

### PR DESCRIPTION
**Pull request by timleslie**

### CODE REVIEW

**Comment by gautamsi** [comment]
Can you also fix the layout, it does not look good on mobile

**Comment by timleslie** [comment]
Thanks for the heads up, will look into it.

**Review by JedWatson — APPROVED** [review]
Approving and merging so I can merge it into my docs update, the new WIP content is as good as the current WIP content 😅

**Comment by JedWatson** [comment]
@gautamsi I'm working on the design over in #4769, I haven't gotten to responsive nav yet but it should already be a lot better on mobile

**Pull request merged**
