### PR TITLE
Review eslint

### PR DESCRIPTION
**Pull request by morenoh149**
* remove nonexistant gulp task from package.json
* change various eslint rules
* enable recommended ruleset

### CODE REVIEW

**Comment by morenoh149** [comment]
@JedWatson I removed all of the unused rules and enabled the recommended ruleset. I feel like this is a good approach. As violations are fixed you can learn more about each rule and decide if any of them should be changed.

**Comment by ericelliott** [comment]
:+1:

**Comment by ericelliott** [comment]
I like the rules, but definitely feel that the errors need to be addressed before merging this change. Don't break the CI checks. =)

**Comment by JedWatson** [comment]
Thanks for the start @morenoh149. I'll start reviewing the errors this weekend. Agreed @ericelliott we shouldn't merge this until the tests pass.

**Pull request closed without merging**
