### PR TITLE
Adding Keystone "frame guard" option

### PR DESCRIPTION
**Pull request by JohnnyEstilles**
Added new Keystone `frame guard` option, along with tests and docs.

Intended as a fix for #1086.

Needs docs in `ZH` and `ES`. Issue should be created if merged.

### CODE REVIEW

**Comment by JohnnyEstilles** [comment]
@JedWatson, if you want this for the `0.2.x` just let me know and I'll submit another PR.

**Comment by JedWatson** [comment]
:+1: nice work @JohnnyEstilles, thanks!

**Comment by JohnnyEstilles** [comment]
@JedWatson, should I submit a PR for the `0.2.x` branch as well?

**Comment by JedWatson** [comment]
@JohnnyEstilles yes please, I'll do a maintenance release of that as well.

**Comment by narendrabhati** [comment]
Hey guyzz kindly let me know whenever you release an update regarding this bug in your announcement so i can request for CVE ID from CVE Mitre

**Pull request merged**
