### PR TITLE
Added `fields` list to ListSchema

### LINKED ISSUE #1281: Add where clause to Field Meta Queries
See also _List_ Meta Query where clause: #1279 

For example, the query in #1280 can become:

```javascript
keystone.createList('Post', {
  fields: {
    title: { type: Text },
    status: {
      type: Select,
      defaultValue: 'draft',
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Published', value: 'published' }
      ],
    },
  },
});
```

```graphql
query {
  _ksListsMeta {
    name
    schema {
      fields(where: { name: "status" }) {
        name
        type
        ...on FieldTypeSelect {
          options {
            label
            value
          }
        }
      }
    }
  }
}
```

Which returns only the `status` field:

```javascript
{
  data: {
    _ksListsMeta: [{
      name: "Post"
      schema: {
        fields: [{
          name: "status",
          type: "Select",
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Published', value: 'published' }
          ],
        }]
      },
    }]
  }
}
```

### PR DESCRIPTION
**Pull request by Vultraz**
@jesstelford 

Resolves #1281
Partially implements #1280 (only includes `name` and `type` keys right now)

Example:
```graphql
query {
  _ksListsMeta(where: { key: "User" }) {
    name
    schema {
      fields(where: { type: "Text" }) {
        name
        type
      }
    }
  }
}
```

Produces:
```js
{
  "data": {
    "_ksListsMeta": [
      {
        "name": "User",
        "schema": {
          "fields": [
            {
              "name": "name",
              "type": "Text"
            },
            {
              "name": "email",
              "type": "Text"
            }
          ]
        }
      }
    ]
  }
```

### CODE REVIEW

**Comment by Vultraz** [comment]
@jesstelford done 👍

**Comment by JedWatson** [comment]
🎉 this is fantastic! Thanks @Vultraz

I'd love to see other meta available as well - given config is field-dependent, maybe it makes sense to include a `config` key which is of JSON type and could contain additional properties?

For what I'm aware of, it makes sense to generally include the same set of properties that `getAdminMeta` includes, except all the standard properties that the base `Implementation` returns could be hoisted up as actual GraphQL fields, where extensions (like `options` for select) could be in the object that the `config` object returns.

**Comment by Vultraz** [comment]
@JedWatson added a `config` key ^ Example in use:
```js
      {
        "name": "FileTest",
        "schema": {
          "fields": [
            {
              "name": "name",
              "type": "Text",
              "config": {}
            },
            {
              "name": "file",
              "type": "File",
              "config": {
                "adapter": {
                  "src": "C:\\Users\\exodi\\Documents\\keystone-5\\demo-projects\\todo\\files",
                  "path": "/files"
                }
              }
            }
          ]
        }
      },
      {
        "name": "SelectTest",
        "schema": {
          "fields": [
            {
              "name": "options",
              "type": "Select",
              "config": {
                "options": [
                  "a",
                  "b",
                  "c",
                  "d",
                  "e",
                  "f",
                  "g",
                  "h",
                  "i",
                  "j",
                  "k",
                  "l",
                  "m",
                  "n",
                  "o"
                ]
              }
            }
          ]
        }
      },
```

Though, I'm not sure if having the file adapter src path exposed is good? 🤔

**Comment by JedWatson** [comment]
> I'm not sure if having the file adapter src path exposed is good?

Yeah, you'll really want to use the `getAdminMeta` function rather than passing raw `config` - anything in there has already been cleaned and safe for sharing publicly (it's awkward naming and I think we'll address that in the near future but this is the field config that's serialised for front-end use in the Admin UI)

**Comment by jesstelford** [comment]
Agreed we shouldn't be exposing the source directory or files.

@jedwatson the original intent in https://github.com/keystonejs/keystone/issues/1280 (and discussed in https://github.com/keystonejs/keystone/issues/354) is as you say; to provide enough information for the admin UI to function.

I'm not sure that exposing the entire config option is quite the right solution as it's a different concern. I think the exposed data should definitely be _derived_ from the config, but it might differ slightly (such as not exposing the source directories) 

Can I propose that we remove it from this PR so it can get merged without contention, then we can figure out (maybe in #354) how exactly we want to expose the rest of the info?

@Vultraz thanks for adding the test 👍

**Comment by Vultraz** [comment]
Ok, reverted the `config` field for now.

**Comment by jesstelford** [comment]
Sorry for the churn! Thanks for getting stuck into it super quick 🎉

**Comment by jesstelford** [comment]
@jedwatson are you ok if we merge this as-is then add more info in a further PR?

**Comment by JedWatson** [comment]
Yep! Let’s do it.

Thanks again @Vultraz

**Pull request merged**
