### PR TITLE
Fetch example projects from GitHub in create-keystone-app

### PR DESCRIPTION
**Pull request by mitchellhamilton**
If you want to test this locally, apply this diff and run `node /the/path/to/packages/create-keystone-app/bin/cli.js` from where ever you want to try it from:
```diff
diff --git a/packages/create-keystone-app/lib/github-api.js b/packages/create-keystone-app/lib/github-api.js
index 0aa16fb98..e94f0059f 100644
--- a/packages/create-keystone-app/lib/github-api.js
+++ b/packages/create-keystone-app/lib/github-api.js
@@ -11,7 +11,9 @@ let cachedLatestVersionCommit;
 const getLatestVersionCommit = async () => {
   if (cachedLatestVersionCommit === undefined) {
     let commits = await got
-      .get('https://api.github.com/repos/keystonejs/keystone/commits?path=.github/release-count')
+      .get(
+        'https://api.github.com/repos/keystonejs/keystone/commits?path=.github/release-count&sha=create-keystone-app-from-github'
+      )
       .json();
     if (!commits.length) {
       throw new Error(
```

### CODE REVIEW

**Comment by gautamsi** [comment]
finally we are going in right direction, 

should this also be simplified to move examples from `examples` folder in root rather than inside the `create-keystone-app` package?

**Comment by JedWatson** [comment]
RE: Where to put the files, I don't think they should live _inside_ the generator package, but should probably be separate from the examples. That's a whole other conversation, but I'd like us to learn from how [Next does examples](https://github.com/vercel/next.js/tree/canary/examples/) on one hand, and separate the templates you can start a project from.

**Comment by mitchellhamilton** [comment]
> should this also be simplified to move examples from examples folder in root rather than inside the create-keystone-app package?

Possibly, that can happen in the future though. This PR is intended make create-keystone-app work reliably/solve issues like #3346.

**Comment by gautamsi** [comment]
I was trying to go the direction NextJs has without naming :)

**Pull request merged**
