### PR TITLE
Update less-middleware invocation as to be inline with version 2.X

### PR DESCRIPTION
**Pull request by francesconero**
https://github.com/emberfeather/less.js-middleware/commit/2fa4ce8106178c2ee427b7d68f258df42df35e66

### CODE REVIEW

**Comment by JedWatson** [comment]
This is going to be a breaking change... @francesconero is it already broken and I missed it? Or is this forward-looking?

**Comment by francesconero** [comment]
It's currently broken as far as I can tell, as the required dependency is currently 2.0.1 in the package.json. So if you don't want a breaking change we should at least downgrade the dependency?

**Comment by JedWatson** [comment]
@francesconero looks like it's been 2.x since Feb, I missed that change when it was upgraded. I'll just push it through and add some warnings in for the depurated options... the lack of issues reported means it probably hasn't been a broad problem in the wild.

**Comment by JedWatson** [comment]
Thanks for the PR :)

**Comment by francesconero** [comment]
Thanks for Keystone! :P

**Pull request merged**
