### PR TITLE
Timezone fix

### LINKED ISSUE #1345: DateTime field type timezone bug
Hi. We've discovered a bug when using a DateTime field type. It occurs when Keystone admin UI is accessed by a client from a timezone different to the one on the server. Say the client machine is 2h ahead of server (EET), and the server itself is in UTC. Steps to reproduce:

1. Fill out a DateTime input with any valid value.
2. Save the document.
3. Edit the document - you'll see previously saved value change by timezone delta.

This is a presentation thing - the value in the database, and the value returned to Keystone UI view is correct - but it is then rendered in user's timezone. When you hit "save" - the value rendered (e.g. 2 hours ahead) gets saved down to the database as a new UTC time.

Here's the model we used:

```
var Banner = new keystone.List('Banner', {
  map: { name: 'imageTitle' },
  autokey: { from: 'imageTitle', path: 'key', unique: true },
  sortable: true
});

Banner.add({
  imageTitle:           { type: Types.Text, label: 'Title' },
  alt:                  { type: Types.Text ,  label: 'Alternative Text'},
  filename:             { type: Types.LocalFile, dest: 'public/images/uploads' },
  inApp:                { type: Types.Boolean, default: true },
  targetUri:            { type: Types.Text },
  validityPeriodStart:  { type: Types.Datetime, required: true, initial: true },
  validityPeriodEnd:    { type: Types.Datetime, required: true, initial: true },
  disabled:             { type: Types.Boolean, default: false , label: 'Inactive'},
  uriSmall:             { type: Types.Url, hidden: true },
  widthSmall:           { type: Types.Number, hidden: true },
  heightSmall:          { type: Types.Number, hidden: true },
  uriMedium:            { type: Types.Url, hidden: true },
  widthMedium:          { type: Types.Number, hidden: true },
  heightMedium:         { type: Types.Number, hidden: true },
  categoryId:           { type: Types.Relationship, ref: 'sportCategory' },
  categoryName:         { type: Types.Text, default: 'default', hidden: true },
  brand:                { type: Types.Text, default: 'bma', hidden: true },
  lang:                 { type: Types.Text, default: 'en', hidden: true }
});
```

### PR DESCRIPTION
**Pull request by lojack**
This fixes #1345, and adds timezone support. Default timezone is set to UTC, and this adds a new keystone option, 'timezone'.

Additionally this fixes an edge case of #1038 that wasn't solved by e7a005866be458086a539d6855835a3523a68db9. If a content editors local machine was in a different timezone as the servers such that the dates don't line up, selecting "Today" would enter an infinite loop.

### CODE REVIEW

**Comment by ttsirkia** [comment]
How does this behave if the server's timezone is not UTC and no timezone is defined in Keystone? For example, my server is in UTC+2 and Keystone/Mongoose/Mongo saves everything as UTC and converts them back to local time based on server's timezone when reading data back from database.

**Comment by ttsirkia** [comment]
Or maybe better question is, that is the new `timezone` option required in order to prevent any unwanted timezone changes?

**Comment by lojack** [comment]
Right now, if timezone is not set in the config then it defaults to UTC. It will (and should) always save to the database in UTC. I'm open to setting this to fall back to the system timezone.

There is one potential edge case that probably won't outweigh breaking backwards compatibility. Potentially, someone could be using a multi-host instance with servers in geographically separate locations. With multiple timezones being used, this could result in wonky behavior.

Even if we allow using system timezone as a fallback, I think explicitly setting the timezone in keystone's config should be the recommended approach.

**Comment by ttsirkia** [comment]
In my opinion server's timezone would be better default choice if the timezone setting is not set. Of course, for new installations with yo, there should be a default setting for this. In a same way as Django has for empty projects.

**Comment by creynders** [comment]
Is this still relevant?

**Comment by lojack** [comment]
I'll retest this against master when I get a chance to verify if its an issue that's still present.

**Comment by temojin** [comment]
any idea when this will be merged? we're on 0.3.16

**Comment by ericelliott** [comment]
I haven't looked at this or the problem in depth, but in general:

Servers should always be timezone-agnostic. Because servers may be distributed across a variety of different timezones, deciding anything based on the server timezone is a recipe for bugs and inconsistent behaviors.

All dates should be saved in UTC, and *only sometimes* adjusted for the local user's timezone, depending on what the date is used for. For example, events that are happening in a particular location should always be displayed in that particular location's timezone, regardless of where the local user is located, and regardless of where the server is located.

Trying to apply the same timezone logic to every date is a bad idea. =)

**Comment by riyadhalnur** [comment]
I agree with @ericelliott. Servers should be timezone agnostic. The time should be localised for the user, after reading back the date/time from the DB, when displaying it on a page.

**Comment by morenoh149** [comment]
@lojack mind rebasing this on master? sorry for the lag but this seems to still be a present bug

**Comment by JedWatson** [comment]
Thanks for the effort here @lojack 

I'm going to close this specific PR but we're going to do a final check on timezone handling for the 4.0 release, to make sure the issue here is resolved.

**Comment by pourmesomecode** [comment]
@lojack thanks for the `timezone` fix, however, nowhere does it state/cover this in the docs. Am I missing something? http://keystonejs.com/docs/database/#fieldtypes-datetime

**Pull request closed without merging**
