### PR TITLE
Updating yarn.lock to align with package.json

### PR DESCRIPTION
**Pull request by molomby**
Running `yarn install` on a clean branch causes these changes to `yarn.lock`. I believe this means the `package.json` has been tweaked manually..?

### CODE REVIEW

**Comment by Vultraz** [comment]
I often edit package.json files and run `yarn` afterwards... is that not the correct procedure? 😬

**Comment by molomby** [comment]
@Vultraz Editing `package.json` manually is fine, so long as you run `yarn` afterward and also commit any changes made to the `yarn.lock` file.

**Comment by Vultraz** [comment]
That I do do. 👍

**Comment by MadeByMike** [comment]
I have no idea how lock files work but this looks fine to me :)

**Pull request merged**
