### PR TITLE
Allow negative number in NumberField

### PR DESCRIPTION
**Pull request by lojack**

### CODE REVIEW

**Comment by morenoh149** [comment]
could you briefly elaborate on what was wrong on the front end. And what the new regex does?

**Comment by lojack** [comment]
Prior to this change, any time you typed a character into the number field the regex would strip any characters that aren't `0-9` or a '.'. This means any time you typed a '-' it would be removed. This change simply includes a '-' in the regex so it can be typed into the field.

Essentially, there's sanitation occurring on the frontend with this regex, and validation occurring on the backend (that's being tested). A case can probably be made to remove this sanitation all together, but I do see the value.

**Comment by creynders** [comment]
Could this get merged? Travis is failing because of totally unrelated code.
Ping: @JedWatson @jossmac

**Comment by JedWatson** [comment]
Great! thanks @lojack, and @creynders for the review!

**Pull request merged**
