### PR TITLE
mailgun support

### PR DESCRIPTION
**Pull request by w01fgang**
Another one for v3.0.x
addition to #250 
This PR adds support for Mailgun, alternative for Mandrill, with 10 000 free emails monthly and 5 domains for free.
Also css styles will be inlined as on Mandrill.
This is not Nodemailer, but it is the fastest solution for migrate from Mandrill.

Usage:
keystone.set('email transport', 'mailgun');
keystone.set('mailgun api key', 'key-xxxxxxxxxxx');
keystone.set('mailgun domain', 'example.com');

If these params didn't configure the Mandrill will used.

And another: I have changed selecting of the email template engine from global config, I think it's more understandable and not hardcoded as it was.

### CODE REVIEW

**Comment by mxstbr** [comment]
This LGTM, except that CI fails on node 0.12. I'm not sure if that's directly related to this PR, but I'd like to cut a 0.3.19 release with mailgun support asap! @JedWatson any input here?

**Comment by morenoh149** [comment]
looks like if you bump react up to v15 it should pass https://travis-ci.org/keystonejs/keystone/jobs/127543250#L325 alternatively using node v5 should trigger npm v3 on travis which would allow the build to continue https://nodejs.org/en/blog/release/v5.0.0/

**Comment by w01fgang** [comment]
strange because the test passed in my repository https://travis-ci.org/w01fgang/keystone/builds/127542617

**Comment by JedWatson** [comment]
@mxstbr that looks like a peer dependency issue, because of the React v15 update. Happy to merge. Thanks @w01fgang!

**Pull request merged**
