### PR TITLE
Add novalidate to all forms and HTML5 type attribute to some input fields

### PR DESCRIPTION
**Pull request by pll33**
Addresses #2535 by adding a type attribute to email, number, and url input fields. Also adds a novalidate attribute to all forms

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @pll33!

@mxstbr any issues if we merge this in? looks good to me but I don't want to introduce conflicts with the branch you're working in

**Comment by mxstbr** [comment]
Yeah, all the forms are changed so that'd be conflict... Great work @pll33!

**Comment by webteckie** [comment]
So is the suggestion here to wait for @mxstbr to merge his branch and then for @pll33 to rebase his PR onto master?

**Comment by mxstbr** [comment]
It's probably easier for me to rebase, so maybe we just merge this and I rebase my PR?

**Comment by JedWatson** [comment]
Sounds good to me 👍

**Pull request merged**
