### PR TITLE
Repair Cloudinary Select and extend upload functionality

### PR DESCRIPTION
**Pull request by chasms**
## Description of changes

* Restored select functionality of CloudinaryImageType input field https://github.com/keystonejs/keystone/issues/4099

* Restored `selectPrefix` option functionality of CloudinaryImageType schema type so that select options are scoped to the correct path in Cloudinary

* Added support for additional filetypes in Cloudinary, including video

* Updated behavior of CloudinaryImageType with `filenameAsPublicID` option to use the filename and to throw a semantic error when filename already exists as related to discussion here: https://github.com/keystonejs/keystone/pull/925

* Set default behavior of CloudinaryImageType to use the Cloudinary `use_filename: true` convention - by which the publicID is set to the filename + a short uniqueID on upload to prevent collision - and use retry for `whenExists`

* Fixed issue where CloudinaryImageType's getExists was checking filename without first sanitizing and removing extension, causing false negatives

* Added new `uploadOptions` for Cloudinary so that upload presets, eager transformations, and other cloudinary upload options can be set per field on the schema all in an object that is passed to the upload request (so that all options are accommodated):
https://github.com/keystonejs/keystone/issues/832,
https://github.com/keystonejs/keystone/issues/4459, https://github.com/keystonejs/keystone/issues/2360, https://github.com/keystonejs/keystone/issues/2260,
https://cloudinary.com/blog/centralized_control_for_image_upload_image_size_format_thumbnail_generation_tagging_and_more

* Added detail error messages for "Field Error" errors in `EditForm` `AlertMessages`, e.g. from Cloudinary upload responses when `whenExists: 'error'`:
https://github.com/keystonejs/keystone-storage-adapter-s3/issues/9

* Added detail error messages for custom `pre('save'` and `pre('validate'` hooks by adding `error.detail` into the `res.apiError` call of the `Update` route:
https://github.com/keystonejs/keystone/issues/3348
Inside of the hooks, errors should be compiled like this to activate this functionality:
```
Post.schema.pre('validate', async function (next) {
    const error = []

    // on validations, push into the errors array
    // with an object with 'fieldLabel' and 'message' fields
    if (!this.title) {
        errors.push({ fieldLabel: 'title', message: 'No title set' });
    }

    // at end of validation, call next
    // with the compiled errors as the detail
    if (errors.length) {
        const error = new Error('field errors');
        error.detail = errors;
        next(error);
    } else {
        next();
    }
});
```

* Added defensive code to prevent breaking UI when cloudinaryImageSummary attempts to render empty image in table cell

* Added textArea character counts on UI per spec in #126

## Related issues (if any)

* Clean up old `getRequestHandler` methods https://github.com/keystonejs/keystone/issues/3433
* Add option to display character count under Text fields #140

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by stennie** [comment]
@roycyang Keystone contributors are currently working on #4643 (unblocking tests) before merging any PRs. The task there is to ensure that the test suite is passing so we have some measure of confidence to make further code changes and remove the beta label from Keystone 4.0.0. There are only a few more tests to resolve in the e2e (end-to-end) test suite.

Concurrent with that activity, we are reviewing open issues to identify any critical issues that should be addressed for a Keystone 4.0.0 GA release. Active issues will be tagged for the [4.0.0 milestone](https://github.com/keystonejs/keystone/milestone/5).

After the 4.0.0 GA release, we'll then look into reviewing the PR backlog for subsequent releases. At first glance it looks like this PR touches a lot of files and includes some old commits that have already been merged (perhaps a fork that wasn't rebased against current master)? It also appears to be an enchancement of current functionality so I expect we would defer to post-4.0.0 review unless there is consensus that merging this PR is critical. We don't want to add further risk/delay to a 4.0.0 release.

That said, we're looking for feedback and help! Please join us on the [KeystoneJS Community Slack](https://launchpass.com/keystonejs) to discuss.

Regards,
Stennie

**Comment by chasms** [comment]
@stennie Thanks for the update! That makes a lot of sense for the pipeline moving forward towards the 4.0 release, and definitely understand wanting to get the CI back up and running.

This PR does include a few things that are enhancements, but all enhancements stem from and build upon some bugs in the admin UI and the underlying code that have caused serious issues for me when using keystoneJS as a dependency:
* Flash messages in admin UI list view are broken in 4.x-beta
* Cloudinary select dropdown field is broken/non-existent while schema option for `select` is in the docs
* Cloudinary `select-prefix` setting is broken/non-existent while schema option is in the docs
* Maintenance of a filenaming system for upload (in 4.x-beta all files are saved to base64 with a long uid and then uploaded with that uid as the name instead of the original filename)
* UI breaks in table view when attempting to render a document that has an empty Cloudinary image when the field for that image is set as a column in the table
* TextArea validates by min and max but doesn't show character count or surface useful validation error messages (one of the two is sufficient for decent UX, I implemented the first per #126 and used the fix for field error alert messages to allow surfacing of a custom error message in a pre save or pre validate hook)

All of the above issues are remedied, and I believe the work for the CloudinaryImage Field and Type could be carried over to the CloudinaryImages Field and Type as well.

This PR could definitely use a rebase (it's ~5 commits behind), but I couldn't find any commits that overlapped with commits in master. All of the commits herein were authored either by myself, @chenghw, or @danielmahon, and I don't see any attribution for the three of us in the [Contributors portion of the Insights section](https://github.com/keystonejs/keystone/graphs/contributors). Maybe there's something I overlooked? I originally started this PR by rebasing some of @danielmahon's work onto the latest master with some of my own work earlier this year. His work was a year or so old, but had some fixes that made for a good starting point for my continued development.

Hopefully this explanation helps! Let me know if there's anything I can do to expedite the process, make this easier on you guys, or clean up the code so that it is suitable for inclusion into master!

Cheers 🍻
Charles

**Comment by stennie** [comment]
>  Hopefully this explanation helps! Let me know if there's anything I can do to expedite the process, make this easier on you guys, or clean up the code so that it is suitable for inclusion into master!

@chasms Thanks for summarizing what is currently included in the PR. I thought some of the early commits may have been merged but only had a quick look (they haven't).

To make changes easier to review and merge, it would be excellent if you could:

- Create new issues for distinct features/changes (eg. "Flash messages in admin UI list view, "Maintenance of file naming system for upload", "TextArea validation for min/max", ...)
- Add test cases
- Add/update documentation

I appreciate these changes have accumulated over a long period of time, but smaller (and focused) PRs with tests & documentation will make the review process more manageable and also be more obvious for anyone trying to relate PRs to the issue addressed.

Given the age of some of the commits it may also be somewhat reassuring to know if these changes are being used in your production Keystone applications, but tests & documentation would be ideal.

Regards,
Stennie

**Comment by stennie** [comment]
Superseded by PR#4774

**Pull request closed without merging**
