### PR TITLE
[WIP] run tests against FF

### PR DESCRIPTION
**Pull request by individual-it**

### CODE REVIEW

**Comment by MadeByMike** [comment]
This seems reasonable. Could you do me a favour and explain what the result of `cypress/browsers:node12.13.0-chrome80-ff74` is compared with our current. 

I assume this locks tests to Chrome version 80 and Firefox 74 with Node version 12.13.0? We'd have to update these manually to test newer versions? I'm not necessarily against that, picking a stable version to test against is good. We don't want tests failing because of a browser release.

The version doesn't seem to indicate anything about Edge? This is mentioned in the issue you referenced but do we need it since it's now Chromium as well?

This makes Firefox the default for `cypress:run:cmd` was this a deliberate choice and is there any benefit?

Finally what's the impact on CI time?

Once I've got a clear picture of the above I'm keen to make these changes.

**Comment by individual-it** [comment]
@MadeByMike this was just the first try, to see if CI runs with firefox and the selected docker image.
I'm planing to add more commands, so that the tests can run with chrome and firefox (I didn't find an Edge image yet, but I haven't looked to hard)
The main issue is that CI does not pick up this PR for some reason. Do you have any idea why?
After I can prove that circle CI runs fine with firefox I can add the other browsers and also answer the question about the time consumption

**Comment by MadeByMike** [comment]
Ideally we'd run both, but a lot of our cypress tests are actually testing API functionality which often means if it works in a browser we have successfully done end-to-end testing of the API. There are some parts of the Admin-UI. that we would want to test cross browser but at the moment we could end up doubling CI time.

@timleslie is working on splitting out some of the API tests. Now that I have pinged him, he might take a look at this and incorporate it into his overall plan for CI.

Don't worry about looking for an Edge image, I think this such a small % of users and for the small amount of front-end code we have, I'm happy to consider it tested under Chromium for now. 

I think Chrome should stay default and we should consider adding FF to some tests as well as updating our images.

**Comment by individual-it** [comment]
I've updated the branch once more, hoping CI will pick up

**Comment by individual-it** [comment]
@MadeByMike can you help me to get CI picking up this PR?

**Comment by gautamsi** [comment]
rebase and force push will get you CI going. 
You can also have your account in CircleCI and then configure your fork for running open source build. this will let you rerun the tests

**Comment by individual-it** [comment]
finally found time to come back to this.
I've ran the tests in my fork and most seems to pass on FF 74, but not all
https://app.circleci.com/pipelines/github/individual-it/keystone/3/workflows/4d897561-924d-4e8b-842c-9d311ed5ccee/jobs/13/parallel-runs/0/steps/0-105

**Comment by individual-it** [comment]
wow, now circleci picked up here also, looks like only the upload test fails

**Comment by MadeByMike** [comment]
This has been open a long time... not sure we really need to run CI against FF as most of the code runs in Node. 

Re-open if you think this is worth progressing.

**Pull request closed without merging**
