### PR TITLE
Fix jshints

### PR DESCRIPTION
**Pull request by morenoh149**
Fixed most jsxhint warnings. Added 'Keystone' to jshintrc globals list. Added bootstrap-markdown.js and bootstrap-colorpicker.js to jshintignore list. Changed extensions of most fieldtypes from .js to .jsx.

### CODE REVIEW

**Comment by sebmck** [comment]
-1 to renaming `.js` to `.jsx`. See Jed's view on it [here](https://github.com/JedWatson/react-select/issues/26#issuecomment-68622178).

**Comment by JedWatson** [comment]
@morenoh149 you may want to read my comments on this issue regarding using `.jsx` as the extension for field types: JedWatson/react-select#26

Could you roll that back for now and I'll merge the other changes?

**Comment by morenoh149** [comment]
sure thing

**Comment by JedWatson** [comment]
Cheers @morenoh149

**Pull request merged**
