### PR TITLE
Upgrade to Babel 7

### PR DESCRIPTION
**Pull request by ashmore11**
## Description of changes

Upgrade repo to use latest babel 7 release

## Testing

All tested passed as they did in the main repo.

## Notes

This update is mainly to comply with the react boilerplate repo which has become popular among react developers. As discussed with Stennie in the Slack group I have created a PR for this.

### CODE REVIEW

**Comment by laurenskling** [comment]
Any plans for this?

**Comment by dominikwilkowski** [comment]
Hey @laurenskling and @ashmore11 

There are no plans to update to new babel versions. We are working on keystone 5 and that will fix this and changes like that in keystone 4 bares too much risk right now. Thank you for the PR though.

**Comment by laurenskling** [comment]
The reason to want to upgrade: babel 6 and 7 (and it's sub tools) do not match. Keystone uses babel 6 tools, which means you cannot install babel 7 tools in the same repo that is using keystone.

You speak of work on keystone 5? I can see no commits to support that. Where is work on keystone 5 being done?

**Comment by dominikwilkowski** [comment]
Yeah I get that requirement. We are working out how and who will maintain keystone 4 while K5 is being worked on. K5 commits are currently closed source to get a good MVP up and running before opening it up to the community. I'm hoping this happens very soon.

**Comment by laurenskling** [comment]
Great to hear there is work being done on Keystone. It has shown many a times in the past many, theres a large group of people who love this project and want to contribute. 

Are there any public announcements on Keystone5? It's the first time I hear about it. What will be worked on?

**Comment by dominikwilkowski** [comment]
Not yet unfortunately as we have been a bit overwhelmed with other work. I will keep nudging to get us into the right track again.

**Comment by EuroWhisper** [comment]
> The reason to want to upgrade: babel 6 and 7 (and it's sub tools) do not match. Keystone uses babel 6 tools, which means you cannot install babel 7 tools in the same repo that is using keystone.

I just got hit with this problem myself (using Webpack, React and Keystone in the same repo) and fixed it by deleting the presets object from .babelrc, then going into my Webpack config file and adding the Babel v7 presets to the options object for my .jsx rule. This resulted in Keystone using the v6 version of Babel that it requires and Webpack using the v7 version of Babel for bundling my React code.

I guess this may not work for everything, but hopefully this can help at least some people out while we wait for KeystoneJS v5. :)

**Comment by laurenskling** [comment]
I did a similar thing, having Babel 6 for backend code and Babel 7 for frontend code. But having all these double dependencies and possible different handling of the code doesn't feel stable.

**Comment by EuroWhisper** [comment]
I hear you, it's certainly not the most ideal circumstance having to install two versions of Babel. But still, at least it's something to get by on until Keystone v5 is released sometime in the future. :)

**Comment by JedWatson** [comment]
I had a look at this and it seems to work just fine, I'm working on a new release with @autoboxer now and we're going to merge this in and try and get it released with 4.1

Thanks for the PR @ashmore11

**Pull request merged**
