### PR TITLE
Add support for admin UI custom styling.

### PR DESCRIPTION
**Pull request by webteckie**
Keystone apps can now custom style the admin UI.

**Usage**
At the application root directory, add a directory that will maintain the custom admin UI styles as well as a less file containing the desired custom styling.  Keystone defaults the directory and file to `customStyles/index.less`.  If you use a different directory or file name then you need to tell keystone about the path by configuring the it as follows:
```
keystone.init({
...
    'adminui custom styles': 'myOwnCustomStylesDir/myOwnCustomStylesFile'
...
})
```

The less file can contain any less processing you want applied to the admin UI.  For example,
`index.less:`
```
nav.primary-navbar {
  background-color: red;
}
```

Happy Styling :-)

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, thanks very much!

**Comment by JedWatson** [comment]
I really want to have a **big red warning** if people actually use this, for now.

I've specifically not added it myself because we have plans to totally rip apart the current CSS structure of the Admin UI, which previously would not have been a breaking change, but now will be.

So just a heads up!

**Comment by wmertens** [comment]
Question: does this allow fully overriding everything, including variables?  Or should the inclusion be after the load of the variables?

**Comment by webteckie** [comment]
@wmertens hmm...that probably does not work as  your custom styles are imported last during the less processing.  Perhaps we need to enhance this to have a pre/post import setting that dictates whether to import the custom style before or aftet the standard set.  @JedWatson @mxstbr what are your thoughts on this?  Of course, I'm assuming that there's not any hoisting of variables here.  If there is then it should work as-is but that will need to be tested.

**Comment by mxstbr** [comment]
I'm pretty sure there's no hoisting going on. Maybe make it possible to optionally supply an object like so:

```
'adminui custom styles': {
    pre: 'somefile.less',
    post:' someotherfile.less',
}
```

**Comment by webteckie** [comment]
Yeah, that's what I was thinking.   Or we can use before/after as the properties...whatever :-)

**Comment by webteckie** [comment]
Actually, that will not override variables as the standard set will override whatever the pre less file does :-)  So I guess I'm not sure how to solve this problem!

**Comment by mxstbr** [comment]
Import the `pre` file after all variables, but before all code that depends on said variables maybe?

I dislike both `pre`/`post` and `before`/`after`, neither of them signify what they do very well. What about calling them `variables` and `override` files, that makes it very clear what they are for and what they do?

**Comment by webteckie** [comment]
Yeah, didn't check the code before making my comment :-)  Should be fine.  What if we call the config something like:
```
adminui custom: {
    variables: xxx,
    styles: yyy,
    whatever: zzz
}
```

**Comment by mxstbr** [comment]
Yeah that's pretty nice!

**Comment by webteckie** [comment]
@mxstbr should suffix with Path...as in:
```
adminui custom: {
    variablesPath: xxx,
    stylesPath: yyy,
    whatever: zzz
}
```

**Comment by webteckie** [comment]
Done!  See #2525

**Comment by JedWatson** [comment]
Ummm

Unless I'm mistaken, variables are resolved **first** in LESS, before the CSS is generated.

So as long as the variables are set by the custom script (which is included _last_) they'll override the previous defaults set by Keystone itself.

We shouldn't need to include two files.

Unless someone has an experiment that proves otherwise?

**Comment by webteckie** [comment]
@JedWatson according to http://stackoverflow.com/questions/15383869/overriding-bootstrap-less-variables-after-import the way you describe it is not the actual behavior.  It seems that custom variables need to be correctly co-located to have the intended effect.  When I get a chance I will test trying to override variables using the previous implementation.

**Comment by creynders** [comment]
@webteckie AFAIK @JedWatson is right. The variables are resolved _before_ the actual css is written. (Obviously if your less compilation is split up into several steps, it'll be resolved _per_ step)

E.g.:

```
//file: A.less
@foo: #00ff00;
```
```
//file: B.less
@import "A.less";
body{
	color: @foo;
}
```
```
//file: custom.less
@import "A.less";
@import "B.less";

@foo: #ff0000;
```

Will result in
```css
body {
  color: #ff0000;
}
```

And _not_ `color: #00ff00`. The SO answer is for less php, might be different there.

**Comment by creynders** [comment]
I can confirm this is the case. I just dumped the above into files and ran `lessc` on them (the same version as used by KS) and it does in fact result in using the overridden `@foo`.

**Comment by webteckie** [comment]
Ok if that's the case then PR #2525 can be closed and will remain as implemented here:-)

**Comment by wmertens** [comment]
Hooray for hoisting :-)

On Sun, Mar 27, 2016, 5:02 PM Carlos Colon <notifications@github.com> wrote:

> Ok if that's the case then PR #2525
> <https://github.com/keystonejs/keystone/pull/2525> can be closed and will
> remain as implemented here:-)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/keystonejs/keystone/pull/2462#issuecomment-202081545>
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by gemscng** [comment]
Hi Max. After login. The home page cannot be load. 
screen shot 2016-04-20 at 11 23 32 am

**Comment by gemscng** [comment]
OK. I fixed by rebuilding packages.js by following command. 
NODE_ENV=production gulp build-packages

**Comment by SHBelsky** [comment]
Had previously pointed something out that was incorrect, sorry for double email. One thing not mentioned in this PR is that the setting expects a `.less` file to function properly; anything else will result in an error. So just a heads up.

**Pull request merged**
