### PR TITLE
Fix incorrect behavior with default values

### LINKED ISSUE #4737: Boolean default:true value not working in v4.0.0
### Expected behavior

Add a checkbox which is checked by default. Clicking on it should uncheck the box.

### Actual/Current behavior

Clicking on the checked by default box does not uncheck it.

### Steps to reproduce the actual/current behavior

Add a model with a *Boolean* field with default value set to `true`:
```
import keystone from 'keystone';
const Types = keystone.Field.Types;
const Page = new keystone.List('Page');

Page.add({
	show  : { type: Types.Boolean, label: 'Show this page?', default: true, initial: true }
});
Page.register();
```
Try and uncheck the checkbox.

### Environment

| Software         | Version
| ---------------- | -------
| Keystone         | 4.0.0
| Node.js          | 9.3.0
| Browser          | Chrome 67

### PR DESCRIPTION
**Pull request by ttsirkia**
Fixes #4737

### CODE REVIEW

**Comment by ttsirkia** [comment]
The main issue is that the default value should be used only if the current value is not defined at all.

**Comment by laurenskling** [comment]
@JedWatson how would we write a test for this?

**Comment by chrisschaub** [comment]
Is this really a problem with this pull request, or with the build to test path? This code needs to make it into the next release, it's a breaking core feature.

**Comment by JedWatson** [comment]
Going to merge this so we can get it released.

I've had a look at why this isn't covered in the tests, and we don't actually have a field config set up in the test schema that triggers this condition; so I'll add a TODO for it

Thanks @ttsirkia

**Comment by chrisschaub** [comment]
Thanks!

**Pull request merged**
