### PR TITLE
refactor(Types.Code):  to Types.CodeMirror

### PR DESCRIPTION
**Pull request by webteckie**
This is to make it easier to add support for the many other features CodeMirror supports.

### CODE REVIEW

**Comment by webteckie** [comment]
Oops...will take care of this when I'm back at my desk.

**Comment by JedWatson** [comment]
@webteckie sorry for the delay reviewing this - it's a breaking change to actually _remove_ the code field, as you have in this PR, and given that field type has no function _other_ than to a `String` as code and render the CodeMirror editor I'm not sure the change in name is necessary (?)

I think we're better off adding the features you're suggesting in #1979 directly into the `Code` field type itself for now. Open to other suggestions though.

**Comment by webteckie** [comment]
@JedWatson yes, it is a breaking change...a good opportunity since there would be other breaking changes in 0.4 :-)  Anyways, the reasoning for this was that code to me seems to imply an action instead of the subject (CodeMirror).  It is not immediately clear without reading the docs or opening the field field that it is a CodeMirror field.  This would also make it clearer if we decide to support other code editors like Types.Ace, etc.  The other thing is that it makes the config a bit more sensible.  For example, currently I need to do:
```
    content: {
        type: Types.Code,
        codemirror: {
             <options>
        }
```

With the refactor I can do the following, which to me is a bit more clear as well:
```
    content: {
        type: Types.CodeMirror,
        config: {
             <options>
        }
```

Thus, this refactor is more for clarity and less confusion should we decide to support other code editors.

**Comment by webteckie** [comment]
Temporarily closing this to resolve conflicts and move to its own branch so I can do other PRs.

**Pull request closed without merging**
