### PR TITLE
[Nested Lists] formatting

### PR DESCRIPTION
**Pull request by brianjd**
## Description of changes
Rebase + Expanded on @jeremyzahner nested list layout adjustments.  Added indentation and box-shadow. 

## Related issues (if any)
#3282

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
I'm not a team member so my opinion doesn't really matter, but this PR as it stands cannot really be reviewed as it changes almost 700 files. I suggest to rebase your work so that it only includes the changes you have introduced since last commit on master.

**Comment by jstockwin** [comment]
Agreed - there is no way to decipher what this PR changed and so it's impossible to review. @brianjd could you try and fix that? Maybe rebase onto master rather than merging?

**Comment by jeremyzahner** [comment]
@jstockwin @AurelioDeRosa This is because it was rebased. The target branch would need to be reset once again so this PR does only reflect the latest changes. CC: @brianjd

**Comment by jeremyzahner** [comment]
@jstockwin It would probably be for the best to leave the rebasing in the future to @wmertens directly on the feature branch.

**Comment by JedWatson** [comment]
Thanks @brianjd - the screenshot you added to #3282 looks good.

I'll merge changes from master into the target branch, hopefully that will simplify things...

**Comment by JedWatson** [comment]
OK, I may have just made things worse - there are conflicts now 😕 

@brianjd would you mind pulling into your branch from the `keystonejs:nested-lists` branch? hopefully that will clear things up.

**Comment by brianjd** [comment]
Sorry, went down the rabbit hole on some other work.  Have a peek now.

**Comment by JedWatson** [comment]
Ha, right. That's so much easier to review :)

How do you feel about using Aphrodite to apply the styles? we're trying to move away from the less stylesheets entirely.

**Comment by brianjd** [comment]
@JedWatson Done.

**Comment by JedWatson** [comment]
Great, thanks @brianjd!

**Pull request merged**
