### PR TITLE
Website: made header and sidebar sticky

### LINKED ISSUE #1007: [Docs] Make header sticky
sticky-header

When combined with #1005 & #1006, this will ensure critical information + the search bar is stuck to the screen at all times.

This should work for both desktop + mobile.

### PR DESCRIPTION
**Pull request by Vultraz**
Resolves #1007.

### CODE REVIEW

**Comment by jesstelford** [comment]
It'd be great to get a recording of this in action for both desktop and mobile

**Comment by Vultraz** [comment]
Mobile: https://share.icloud.com/photos/0TexepdTB5psQOk7xGNrMM-0Q

And on the desktop it looks just like in your render.

**Comment by MadeByMike** [comment]
@jesstelford we have preview deploys ;) https://deploy-preview-2452--v5keystonejs.netlify.com/quick-start/

**Comment by MadeByMike** [comment]
It looks like this has created a UI issue. There is no point in having a sticky menu if the it looks like the menu broken when you are further down the page.

capt

**Comment by Vultraz** [comment]
Oh. Ok, that is not good. 🤔

**Comment by Vultraz** [comment]
@MadeByMike implemented your suggestion

**Comment by Vultraz** [comment]
@MadeByMike @jesstelford is this good to go?

**Comment by Vultraz** [comment]
#2597 seems to supersede this so I'm closing this.

**Pull request closed without merging**
