### PR TITLE
Add custom `token` support for morgan log middleware

### PR DESCRIPTION
**Pull request by wangshijun**
## Description of changes

Add custom `token` support for morgan log middleware, user can customize `morgan` token by passing `logger options` as following:

```
keystone.set({
    tokens: {
        date: function () { return new Date().toString(); },
    },
});
```

## Related issues

The issue is not submmited on github repo, described as flollowing:

I am from China( timezone UTC+8), when keystone is used in production cms, the access log produced by `morgan` in keystone server contains only ISO time, makes it not that straight forward to scan logs, currently there is noway to customize this through `logger options`，so I made this PR.

## Testing

Pass

### CODE REVIEW

**Comment by JedWatson** [comment]
This looks good @wangshijun! Thanks for the PR.

After reviewing the code, please note the example above isn't correct; it should be

```
keystone.set({
    'logger options': {
        tokens: {
            date: function () { return new Date().toString(); },
        },
    },
});
```

Aside from that, good to merge!

**Comment by wangshijun** [comment]
Ha, thanks for the correction! I am wondering how can documentation site be updated with this PR, I have looked at the contribution guide for how to update docs, but no luck.

**Comment by mxstbr** [comment]
@wangshijun the docs are in https://github.com/keystonejs/keystonejs-site, you could submit a PR there! :+1:

**Comment by playwolf719** [comment]
@wangshijun 给大神赞一个！

**Comment by playwolf719** [comment]
@JedWatson Your way of  setting the token not work for me

**Comment by playwolf719** [comment]
@wangshijun 话说，请问应该怎么改，我这边修改不生效

**Comment by wangshijun** [comment]
@playwolf719 你使用的版本是？

**Pull request merged**
