### PR TITLE
Pagination Functional Tests

### PR DESCRIPTION
**Pull request by alsoicode**
## Pagination Functional Tests

- Added simple "Post" model with a multi-key, weighted index.
- Added tests and assertions for list.paginate to ensure no existing functionality has been affected by the addition of the `optionalExpression` and `countQuery` modifications.
- Added tests and assertions for a paginated result set that includes an `optionalExpression` that adds metadata to the result.

### CODE REVIEW

**Comment by alsoicode** [comment]
I'm assuming the tests failed the Travis build because MongoDB isn't available in that environment. Any suggestions as to how we can work around that?

When I'm working on Django projects that have database-related tests, I use SQLite. Is there a MongoDB equivalent?

**Comment by webteckie** [comment]
Maybe this helps:  https://docs.travis-ci.com/user/database-setup/#MongoDB

**Comment by webteckie** [comment]
Although the tests at https://github.com/keystonejs/keystone/blob/master/fields/types/relationship/test/server.js seem to require mongodb up already.  At least, in my environment, if mongo is not running the tests fail.

**Comment by alsoicode** [comment]
I think in the case with my tests, it might be a Mongo version issue, but I haven't quite nailed down the right config yet.

**Comment by alsoicode** [comment]
Finally getting somewhere. I updated the version of MongoDB to 3.0, and tests are passing for the 4.0 environment but failing for 0.12. That's a pretty old version... thoughts anyone?

**Comment by morenoh149** [comment]
afaik lots of things in keystone require a fairly recent version to run

**Comment by alsoicode** [comment]
Considering that 5.4.1 is the most recent at the time I'm writing this, 0.12 seems ancient :)

**Comment by ericelliott** [comment]
Are we supporting 0.12 for 0.4.x?

**Comment by JedWatson** [comment]
@ericelliott @alsoicode we _were_ planning to, but the longer it gets the less inclined I am to worry about it.

Our tests frequently fail with *false negatives* on 0.12, and I'm not set up to easily replicate them so it's adding an unfortunate amount of overhead at the moment. Not sure there's really a lot of value when there is so much to do for 0.4 tbh.

AFAIK there is _nothing intentional_ in 0.4 that would break with node 0.12 but it needs review.

I'm going to merge this in the meantime so it doesn't fall behind, and open a new issue about 0.12.

**Comment by JedWatson** [comment]
oh, and @alsoicode - thanks for these tests :grinning:

**Comment by alsoicode** [comment]
@JedWatson You're very welcome.

**Pull request merged**
