### PR TITLE
added currency as an option to money field

### PR DESCRIPTION
**Pull request by douglasf**
Fix for issue https://github.com/keystonejs/keystone/issues/474

### CODE REVIEW

**Comment by JedWatson** [comment]
Hey @douglasf, thanks for the addition, and sorry I haven't reviewed it yet. Currently working through the PR backlog.

Looks like a good change but do you mind explaining the change to your own fork of numeral.js? would be nice to stay on the official release so we can version correct / etc.

**Comment by douglasf** [comment]
No problem

It is just an additional language file in numeral.js for Swedish currency. You can ignore it :)

**Comment by JedWatson** [comment]
Would you mind rebasing your PR so I can merge it?

**Comment by douglasf** [comment]
I'm no where near where I want to be when it comes to git knowledge, did I solve anything by that revert? ;) I'm thinking that the package.json change was not wanted

**Comment by morenoh149** [comment]
@douglasf invest a couple of hours and do this https://github.com/jlord/git-it it seriously helped me more than everything else I tried learning git from

**Comment by JedWatson** [comment]
@douglasf you're looking for "rebase" - simply, pulling the latest changes from the "origin" repo (this one) into your own, so that changes are merged in. It then lets me simply pull the changes from your PR in without any further merging (or resolving conflicts, etc) required.

**Comment by douglasf** [comment]
Thanks @morenoh149 I will definitely have a look at that!

@JedWatson Ahh I get it now! But it did occur to me that it seems like I want to do the wrong thing with this PR, merging to keystonejs:master is not correct right? Should probably be keystonejs:0.2.x, I'm gonna clean this up and make a new PR if thats ok?

**Comment by JedWatson** [comment]
@douglasf we're now up to 0.3.3, I'd prefer not to release any further 0.2.x versions so it's fine to merge this into `master`.

**Comment by douglasf** [comment]
I'm sorry for about the trouble here, but I don't get how that would work. I am trying to merge from my 0.2.x branch to keystone:master, the folder structure have changed and lib/fieldTypes/money.js does not even exist in master. The rebase would be hell, no?

**Comment by JedWatson** [comment]
Oh I see. Right. Yes it would.

No worries, I'll manually merge your changes in.

**Pull request closed without merging**
