### PR TITLE
header dependsOn

### PR DESCRIPTION
**Pull request by snowkeeper**
Fix for #970

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @snowkeeper

**Comment by webteckie** [comment]
@snowkeeper fyi, I tried the latest master yesterday and this is still not working for me.  Did you try it and it worked fine for you?

**Comment by snowkeeper** [comment]
@webteckie your right,  it wasn't working.  I had to run the build script.  I am so used to ignoring `public/build/js/app.js` in git that it didn't even cross my mind to include the updated copy.

Just to clarify @JedWatson , do you want the fresh app.js file when appropriate.

**Comment by JedWatson** [comment]
Sorry - I should have done that after merging the PR. It's updated now.

I'll continue to build app.js after changes or PRs so we don't get conflicts, and hopefully replace it with the new build process in a day or so.

**Pull request merged**
