### PR TITLE
Docs: Sticky Layout

### LINKED ISSUE #1007: [Docs] Make header sticky
sticky-header

When combined with #1005 & #1006, this will ensure critical information + the search bar is stuck to the screen at all times.

This should work for both desktop + mobile.

### PR DESCRIPTION
**Pull request by jossmac**
Update documentation website layout:
- make the most of Algolia search bar
- make the most of larger devices
- introduce table of contents for each page

image

Replaces #2452

Resolves #1007

### CODE REVIEW

**Comment by Vultraz** [comment]
Does this mean #2452 is superseded?

**Comment by jesstelford** [comment]
Does this overlap with https://github.com/keystonejs/keystone/pull/2452?

**Comment by jossmac** [comment]
Never mind, happy to close if it's already been done.

**Comment by jossmac** [comment]
@jesstelford yes, didn't realise #2452 existed

**Comment by jesstelford** [comment]
Can we merge them both together, or does it make sense to pick one or the other?

**Comment by jossmac** [comment]
There's a bit more to this than sticky header:
- align the search bar with content column
- introduce heading-based page nav
- drawer-style navigation on small device
- optimised columns for larger devices

I was really just curious if anyone was interested. I'd prefer to redo the website implementation; it's really hard to work with. Might best to just merge the other for now.

**Comment by Vultraz** [comment]
I'm happy to close my PR. It's very simplistic, and this one does a lot more.

**Comment by jordanoverbye** [comment]
This is looking really good so far 👍

**Pull request merged**
