### PR TITLE
Upgrade all Babel deps to the same version (7.7.4)

### PR DESCRIPTION
**Pull request by Vultraz**
Housekeeping, keeps everything consistent.

### CODE REVIEW

**Comment by Vultraz** [comment]
Tests are just complaining about #2021.

**Comment by timleslie** [comment]
@mitchellhamilton Could you give this a review? @Vultraz could you help sort out the merge conflicts? Thanks!

**Comment by Vultraz** [comment]
@timleslie done 👍

**Comment by Vultraz** [comment]
@mitchellhamilton done

**Comment by Vultraz** [comment]
Reeeeebbbbbaaaasseeeeee

**Pull request merged**
