### PR TITLE
updated mongoose to version 4, fix #1752

### LINKED ISSUE #1752: 0.3 Error: Cannot find module '../build/Release/bson'
```bash
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

node: 4.2.1
npm: 2.14.7
keystone: 0.3.15

### PR DESCRIPTION
**Pull request by mahnunchik**
all tests passed.

### CODE REVIEW

**Comment by nikashitsa** [comment]
:+1:

**Comment by morenoh149** [comment]
I think we get mongoose 4 in the 0.4.x version of keystone. See https://github.com/keystonejs/keystone/issues/1612  Ref https://github.com/keystonejs/keystone/issues/1315

**Comment by mahnunchik** [comment]
If mongoose 4 does not contain breaking changes related to keystone then why not to upgrade dependency in 0.3 branch while 0.4 branch is not so stable?

**Comment by morenoh149** [comment]
we can definitely do that as well.

**Comment by JedWatson** [comment]
I'm really mixed on this because while mongoose 4.x doesn't break _keystone_, it could quite easily break projects _build on_ keystone which is the point of more than a patch version bump. So merging this would definitely break sermver.

Having said that not releasing 0.4 is really holding us back and there's still work to do :disappointed:

**Comment by creynders** [comment]
As I wrote in #1315 

>master is on v4 already and if you're still running KS v0.3, just add mongoose v4 as a dependency in your project and hook it up with keystone.init or keystone.set('mongoose', require('mongoose'))

Closing this, since it's landed for v0.4 and I don't think it's worth the hassle for v0.3

**Pull request closed without merging**
