### PR TITLE
Bugfix/3786 inline relationship field

### PR DESCRIPTION
**Pull request by pavethiran**
## Description of changes
Fixed styling for SelectField

## Related issues (if any)
#3786 

## Testing

- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by bassjacob** [comment]
Hi @pavethiran,

Was this not already fixed in https://github.com/keystonejs/keystone/pull/3789 ?

**Comment by pavethiran** [comment]
As mentioned in #3786 there were issue in the display of the select field, which i fixed with this PR. I set a minimum width of 100px to the field itself and the drop down.

**Comment by bassjacob** [comment]
On the test project with just the current master branch (without the extra styles from this PR) it seems like the width is fixed. Can you rebase your branch against keystonejs:master and verify whether the style changes are still necessary?

**Comment by pavethiran** [comment]
@bassjacob I think you're right 😄 Thanks for the info.

**Comment by bassjacob** [comment]
no worries :smile: should we close this for now then, and reopen it if it's still an issue?

**Comment by pavethiran** [comment]
Yeah, totally 👍

**Pull request closed without merging**
