### PR TITLE
Added the boilerplate for subscription support to the providers

### PR DESCRIPTION
**Pull request by Vultraz**
@timleslie 

Nothing functional. This just adds the boilterplate necessary to recognize subscription types in the Keystone schema and for generating custom subscriptions with `extendGraphQLSchema` (#2032).

### CODE REVIEW

**Comment by pahaz** [comment]
Is this going to be merged?

**Comment by Vultraz** [comment]
I wasn't able to actually get the network transport working when I was working on this. It adds the subscriptions to the schema, so they're recognized by the apollo server, but the pubsub side wasn't working. Unless this is enough to get a working implementation up and running?

**Comment by pahaz** [comment]
It's enough as a starting point for me. It's helping me don't hack the Keystone core for my tasks.

**Comment by MadeByMike** [comment]
@Vultraz this looks pretty good to me and it's something a number of people have requested. What's the next steps to get this working? 

@timleslie any reason not to merge this?

**Comment by Vultraz** [comment]
I believe the next step would be to get the websocket transport working. I couldn't figure it out exactly, and the Apollo docs are rather contradictory in places. I had also considered waiting for Apollo server v3 - which has better subscription support - but it's unclear when that will be released.

**Comment by MadeByMike** [comment]
Alright... next steps!

**Comment by fcpauldiaz** [comment]
does someone has a working example of subscriptions?

**Comment by faghani** [comment]
> 

https://github.com/keystonejs/keystone/tree/main/examples/extend-graphql-subscriptions

**Comment by faghani** [comment]
> 
hi guys, this example could help:
https://github.com/keystonejs/keystone/tree/main/examples/extend-graphql-subscriptions

**Pull request merged**
