### PR TITLE
Add Pull Request Template

### PR DESCRIPTION
**Pull request by jstockwin**
Please make sure the following is filled in before submitting your Pull Request - thanks!

## Description of changes

Added a Pull Request Template. 
Happy for suggestions if you'd rather this looked different.

## Related issues (if any)

None.

## Testing

- [X] Please confirm that you have successfully ran `npm run test-all`.

Notes:
- If you are developing in Windows you may run into linebreak linting issues. One possible workaround is to remove the "linebreak-style" rule in `node_modules/eslint-config-keystone/eslintrc.json`.

### CODE REVIEW

**Comment by mxstbr** [comment]
I think the `CONTRIBUTING.md` should be in the root folder, since it motivates people to help and should be as visible as possible.

I love the Pull Request template :+1:

**Comment by jstockwin** [comment]
Alright fair enough. If we are moving contributing, the link in the readme should be changed, but very happy to move it back. Just thought it made sense to have them all in one folder out of the way.

**Comment by jstockwin** [comment]
Also do we expect people to run `npm test-unit` before submitting PRs?

**Comment by mxstbr** [comment]
No, since the CI runs it anyway…

**Comment by jstockwin** [comment]
CI runs the `eslint` too though no? It's better that people still check these things first. It's annoying to have a PR fail because linting failed, and then have to wait for them to update, and it also makes the commit history messy.

**Comment by mxstbr** [comment]
Yeah that's true, lets put it in the template too!

**Comment by jstockwin** [comment]
Alright, have moved contributing back to root, and added unit tests to the template. Probably worth squashing this PR if/when it gets merged.

**Comment by webteckie** [comment]
I think we should change package.json's:
```
"test-all": "npm test && npm run test-e2e"
```

to

```
"test-all": "npm test && npm run test-e2e-bg"
```

and instruct devs to run that instead as `npm run test-all`.  And I would put some quick notes at the bottom of the template to capture possible workarounds for environment differences.  For example, you may want to put one like this (we can but this in contributing.md but may not be so obvious):

```
NOTES:
- if you are developing in windows and use git bash to do the pre-commit tests, you may run into linebreak linting issues; one possible workaround is to remove the "linebreak-style" rule in node_modules/eslint-config-keystone/eslintrc.json
```

**Comment by jstockwin** [comment]
@webteckie @mxstbr See latest commit. I've also update this PRs text for a preview.

**Comment by webteckie** [comment]
LGTM

**Comment by mxstbr** [comment]
:shipit: awesome @jstockwin!

**Pull request merged**
