### PR TITLE
added gulp build-scripts task to npm postinstall

### PR DESCRIPTION
**Pull request by lojack**
solution to #955. Related to #957.

### CODE REVIEW

**Comment by morenoh149** [comment]
to make this work the `chalk` module must be moved from `devdependencies` to regular `dependencies`

**Comment by morenoh149** [comment]
also need module `del` moved. Almost there! :)

**Comment by lojack** [comment]
I merged upstream and fixed the dependencies. I also think I figured out why I wasn't running into any of these issues with the devDependencies needing to be under dependencies in the first place.

**Comment by morenoh149** [comment]
@lojack I've abandoned the postinstall strategy. I built app.js locally again. And this time the bug didn't go away. I'm now focusing my efforts on narrowing the source of the bug.

Do you still think building app.js on each client is the solution? I don't think so anymore. Thanks for the effort though :) See latest comment on https://github.com/keystonejs/keystone/issues/1038 where I shared a link to a live keystone app that experiences the bug. Also app.js in not uglified so we can debug it more easily.

**Comment by lojack** [comment]
@morenoh149 I don't think this will solve #1038, but I do think it's probably still a good idea to build on postinstall so the minified app.js isn't included in the repo. It would help make commits cleaner, and prevent a lot of merge conflicts.

**Comment by creynders** [comment]
:+1: this really needs to be done. 

1. The git history is polluted with "Updating build" commits
1. When working on any feature which requires rebuilding the scripts you have to be very careful not to commit the scripts as well or massive merge conflict mayhem ensues
1. Adding this to postinstall will enable a very crude sanity check when travis rebuilds the scripts after each merge
1. Having build results in git repos is simply not maintainable

**Comment by morenoh149** [comment]
@creynders I agree the build itself shouldn't be under version control. @JedWatson has expressed the same.

However this pull request does not work in its current state. And the preferred strategy would be to rebuild the bundle based upon the fieldtypes the developer selects for his project. That's here https://github.com/keystonejs/keystone/issues/957 Closing this. Though thanks @lojack for the attempt :)

**Pull request closed without merging**
