### PR TITLE
Add Types.LocalImage based on LocalFile&CloudinaryImage

### PR DESCRIPTION
**Pull request by wuhaixing**
Since Image is so important in local files,so I think it should be a field alone.

### CODE REVIEW

**Comment by wuhaixing** [comment]
There a lot of things to do,but at the moment,we have a preview thumbnail in admin panel

    image: { 
        type: Types.LocalImage,
        label:'photo',
        dest: 'public/images/photos',
        hrefPrefix: '/images/photos/',
        allowedTypes:['image/jpeg','image/png'],
        format: function(item, file){
            return item.image.hrefPrefix + file.filename
        }
    }

**Comment by webteckie** [comment]
:+1:

**Comment by wuhaixing** [comment]
Actually I think there maybe should have a common Type/Field for Image,and different process handler such as Local,Cloudinary...from different providers,and user can choose them in config.I'd like to support LocalImageHandler with [easyimage](https://www.npmjs.com/package/easyimage) which built on top of ImageMagick.BTW,Do we really should put Type such as `LocalFile`,`AzureFile`,`S3File` in model instead of `File`? @JedWatson

**Comment by wuhaixing** [comment]
There is a branch [file-fields](https://github.com/keystonejs/keystone/tree/file-fields) for FileType

**Pull request closed without merging**
