### PR TITLE
Misc fixes and improvements

### PR DESCRIPTION
**Pull request by webteckie**
## Description of changes

This change takes care of some admin ui warnings as well as improvements to the e2e test environment and server.

## Related issues (if any)

N/A

## Testing

- [X] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by mxstbr** [comment]
Oh wow, this looks solid @webteckie! :fire:

**Comment by jstockwin** [comment]
@webteckie Something isn't quite right with the changes to server.js. The e2e tests pass, but then nothing happens for 10 minutes and so travis gives up. I guess some process isn't exiting properly somewhere? (See [here](https://travis-ci.org/keystonejs/keystone/jobs/135262845#L3602)). 

Otherwise, LGTM.

**Comment by webteckie** [comment]
Arrrgh...that last commit should do it :-)

**Comment by jstockwin** [comment]
:+1:

**Comment by mxstbr** [comment]
LGTM!

**Comment by JedWatson** [comment]
Nice one @webteckie!

**Pull request merged**
