### PR TITLE
fixed app hanging when date is selected

### PR DESCRIPTION
**Pull request by lojack**
fix for #1038

### CODE REVIEW

**Comment by morenoh149** [comment]
@lojack thanks for fixing up the code!

Don't we need the `isValid`,`setDate`, etc methods for other things though?

**Comment by JohnnyEstilles** [comment]
I'm still trying to replicate @morenoh149's issue on #1038, but unfortunately haven't been able to (still trying though). I would love to troubleshoot this, but I haven't encountered the issue at all, even under the circumstances described by @gregoj.

While I really appreciate @lojack taking a crack at this, I'd be careful merging this PR.

First, it doesn't really explain how the issue was reproduced and what problem was found. Second, it removes code that is required for specific use-cases and that have no apparent connection with the problem at hand.

Have any of the folks that are encountering this issue (@morenoh149, @webteckie, @gregoj) tested this fix?

**Comment by webteckie** [comment]
@JohnnyEstilles I have not verified the fix by @lojack  Does it correctly handle user-entered invalid dates?

**Comment by JohnnyEstilles** [comment]
@webteckie ... It does (to a certain extent). But what worries me more is that the current code does two things that this fix removes: (1) it makes sure that date is converted to/stored in ISO format (required by the server and allows us to handle timezone difference issues), and (2) it makes sure to state changes are pushed up to the `<EditForm />` component, which is serving as a sort of view-controller/single source of truth for that view's state. I assume this state will eventually be used to update the server, so keeping it consistently updated is important, regardless of how we currently send the data back to the server.

I tested the fix and I found several of issues. The first is that depending on the timezone difference between the client and the server, the date store may be displayed as "one day before" the date that is actually saved. There are other issues, but too many to enumerate here right now. There is no infinite loop problem in the fix, but bear in mind that I've never actually encountered the problem myself.

I understand the current code has a bug causing the infinite loop that is being reported. I just think we need to do a better job of troubleshooting and identifying the source of the bug.

**Comment by morenoh149** [comment]
@JohnnyEstilles indeed. Is there anyway to make keystone deliver an unminified app.js file? Currently I can' get very far debugging since the file is so hard to read. Chrome Prettifying the code doesn't stick around when I run the debugger as well. It'd be great to enable a project-wide `debug` mode.

**Comment by JohnnyEstilles** [comment]
@morenoh149, it looks to me like the build process automatically uglifies `app.js`. If you're using the gulp `watch-scripts` task, I suppose you can temporarily comment out lines that uglify `app.js` in the `rebundle()` function.

**Comment by JohnnyEstilles** [comment]
@morenoh149 ... I also added some background/comments in #1038 that might be of help to anyone troubleshooting this.

**Comment by morenoh149** [comment]
clicking okay from the wysiwyg source code editor modal also freezes the browser 
screenshot 2015-02-12 21 22 21

**Comment by lojack** [comment]
Sorry, was a little trigger happy with the PR. I'll take another look at this today, with the background given by @JohnnyEstilles in mind.

Does it make sense to look into implementing a Flux style pattern so we can avoid these recursive cascading updates in the future?

**Comment by JohnnyEstilles** [comment]
@lojack, you may want to hold off for a bit ... @JedWatson and I were discussing the possibility of replacing `pickaday` within the `Date` field component with a React date picker. I'm testing one right now with the [React Widgets Date & Time Picker](http://jquense.github.io/react-widgets/docs/#/datetime-picker).

@JedWatson, I'm going to submit a PR just so that you guys can test and tell me what you think. If you guys like it, the I will convert the `DateTime` field as will, and submit it along with unit tests (speaking of which, we need to discuss unit testing of React components).

**Comment by JohnnyEstilles** [comment]
The `Date` field using the React Widget Date & Time Picker is on the `feature/datefield-wip` branch on [my Keystone fork](https://github.com/JohnnyEstilles/keystone/tree/feature/datefield-wip). Please check it out and tell me what you think.

**Comment by morenoh149** [comment]
@JohnnyEstilles where in the codebase is the build process for app.js? I'm not using the generator of the gulp watch task. I have a custom gulp for my project.

**Comment by JohnnyEstilles** [comment]
@morenoh149, yes! You can use either the `build-scripts` or `watch-scripts` after you install the dependencies with `npm install`.

**Comment by morenoh149** [comment]
@JohnnyEstilles I just built app.js locally and both bugs (saving with the wysiwyg editor in source code mode, and clicking today field on your experimental branch) are solved. I think the solution is to run the build step on the end-user's machine but that's annoying as browserify is supposed to build a script that works anywhere. 

Diffing is near impossible.
screenshot 2015-02-13 20 46 51
A good next step would be to disable uglify https://github.com/keystonejs/keystone/blob/master/gulpfile.js#L32 so we could debug more easily. Afterwards decide if we want to have a `postinstall` script added https://docs.npmjs.com/misc/scripts

**Comment by JohnnyEstilles** [comment]
@morenoh149, thanks for the help troubleshooting this. Regarding the points you brought up:

- changing the build step to `postinstall` is something we would needs to discuss with @JedWatson 
- removing `uglify` is something we could probably consider for the `watch-scripts` gulp task to help with troubleshooting
- keeping the existing `Date` field versus moving to a pure React component is also something that needs to be discussed more with @JedWatson. I don't want to speak for @JedWatson, but in a recent conversation he seemed more in favor of using pure React components (with which I agree). This is why I opened issue #1065, proposing the use of the date time picker included with React Widgets in lieu of `pickaday`.

**Comment by morenoh149** [comment]
@JohnnyEstilles Re `postinstall` https://github.com/substack/ploy#start *`postinstall` is a good place to put bundle steps like browserify.*

**Comment by JohnnyEstilles** [comment]
@morenoh149, Re: moving build to `postinstall`, I do not disagree, I just think we should consult with @JedWatson to make sure we're not overlooking anything.

**Comment by morenoh149** [comment]
oh yeah of course. I was just sharing what I found regarding it.

**Comment by webteckie** [comment]
fyi, the following sequence spins -- onInputChange/setDate happens repeatedly, which I think is what @lojack saw as well and attempted to fix.

image

**Comment by JohnnyEstilles** [comment]
@webteckie ... thanks!. Although I can't really see the loop on the image you sent. I'll take your word for it. So, were you able to identify to identify the set of circumstances that lead to the loop? I ask, because as much as I've tried I haven't been able to reproduce the problem even once.

**Comment by webteckie** [comment]
@JohnnyEstilles the image wasn't meant to show the loop but rather an instance of it while stepping through it after capturing the initial event. In slow motion clicking the button I can see that the date is set in the input field but then I guess the onChange events kicks in and the loop starts. The onInputChange/setDate sequence need to be stopped  somehow once it is done once.

**Comment by JohnnyEstilles** [comment]
@webteckie ... thanks for the explanation. Unfortunately, I don't see/experience that loop when I use the `Date` field component. So, like I've mentioned before. We need to identify the set of circumstances that lead to the loop.

**Comment by JedWatson** [comment]
We can't merge this as-is, there's a lot of required functionality missing.

`format` is used by `renderUI` when `this.shouldRenderField()` returns false, and other issues.

We also need to push the change event back up via `props.onChange` or the rest of the form won't know when the date changes (breaking `dependsOn` and future ajax data submission)

Re `postinstall` discussion, the real answer is to build scripts dynamically when keystone starts based on the _fields you need_.

**Comment by johngroves** [comment]
Awesome, thanks all.

**Comment by joshlasdin** [comment]
I'm running into this problem, does anyone have a workaround in the meantime?

**Comment by JedWatson** [comment]
Has been fixed, see #1038

**Pull request closed without merging**
