### PR TITLE
test(e2e): Add testing for relationship field

### PR DESCRIPTION
**Pull request by jacargentina**
Initial work for testing relationship fields #2291

### CODE REVIEW

**Comment by webteckie** [comment]
@jacargentina we are trying to get rid of the adminUI.js in favor of page objects.  Please see all existing page objects under `test/e2e/adminUI/pages` and see if you can follow the pattern and do something similar.  tnx

**Comment by jstockwin** [comment]
@jacargentina Did you want to have a crack at adding the page objects and test files too? 

If not, I'm planning to get a few of the other fields done over the next few days and can do this one too.

**Comment by jacargentina** [comment]
@jstockwin go with it

**Comment by jstockwin** [comment]
In which case, I'll close this PR. Thanks for adding what you did, if any of it can be converted to page objects easily then I'll start with your code :)

**Pull request closed without merging**
