### PR TITLE
Add a guide on using GraphQL filters

### PR DESCRIPTION
**Pull request by timleslie**

### CODE REVIEW

**Comment by gautamsi** [comment]
Isn't this changing soon? I mean the filter syntaxes with new fields??

**Comment by timleslie** [comment]
> Isn't this changing soon? I mean the filter syntaxes with new fields??

Yep, the filters will be changing, but the shape of these documents will remain largely the same.

**Comment by JedWatson** [comment]
Looking good @timleslie

**Review by dominikwilkowski — APPROVED** [review]
Looks great. Good start

**Review by raveling — APPROVED** [review]
comments sent in Slack ❤️

**Pull request merged**
