### PR TITLE
Fixing links in Markdown docs to use file paths

### PR DESCRIPTION
**Pull request by molomby**
Links in Markdown documents should follow [the guidelines documented in #2041](https://github.com/keystonejs/keystone/issues/2041#issuecomment-566802733). This brings a swathe of existing docs inline with these decisions. These fixes are not exhaustive. 

See also #2114, which should possibly be resolved either before this PR is merged or before the docs site is next updated.

### CODE REVIEW

**Comment by MadeByMike** [comment]
This breaks links on the website. We need to fix/re-implement a solution for that first.

**Comment by molomby** [comment]
@MadeByMike yep, seems like a good idea 👍🏼 Should we slap a high priority on #2114 then? Maybe you can prod the relevant people?

Alternatively, how does the site currently get published? Are there docs on the process? (Meta-docs?! 🙃)

**Comment by timleslie** [comment]
@molomby Now that #2160 is complete could you please review whether there are any useful changes left in this PR?

**Comment by mitchellhamilton** [comment]
I based #2160 on this so we can close this now

**Pull request closed without merging**
