### PR TITLE
React component unit tests

### PR DESCRIPTION
**Pull request by suryagh**
1. React component test setup
2. First test for `ItemsTableCell.js`

@JedWatson @mxstbr I wanted to throw this out there; let me know your views. 

Note: I have not hooked this to `CI` pipeline yet. But that should be easy if we plan to go forward with this.

Edit: `npm run test-react`

### CODE REVIEW

**Comment by suryagh** [comment]
updated the `pr`

**Comment by mxstbr** [comment]
Good idea! I'm a big fan of `enzyme`, what do you think about using that instead of `TestUtils.createRenderer()`?

**Comment by suryagh** [comment]
@mxstbr I looked at the `enzyme`, it looks much better that `test-utils` though the latter if through facebook. Thanks for the pointer. I have updated the `pr`.

**Comment by mxstbr** [comment]
This is great @suryagh, love it! LGTM!

**Comment by JedWatson** [comment]
Looks great, I'm merging this & will update the CI pipeline!

(want to have a play with this now in master 😀)

**Pull request merged**
