### PR TITLE
Remove tinyMCE in HtmlField when dependsOn is disabled

### LINKED ISSUE #2834: [0.4] WYSIWYG editor breaks in Firefox if shown and hidden twice
I added a Html field that dependsOn a Boolean. If I toggle the checkbox twice, a regular textarea appears after the second time that contains just the HTML code of the edits I made earlier. This only happens in Firefox. An error appears in the console:
`NS_ERROR_UNEXPECTED: 1 tinymce.min.js:5:0`

Apparently this is due to an unfixed issue in TinyMCE reported here (the exception throws on the same line):
https://github.com/tinymce/tinymce/issues/794
A workaround is found in this comment:
https://github.com/tinymce/tinymce/issues/794#issuecomment-203701329

### PR DESCRIPTION
**Pull request by geloescht**
* also remove instance from tinymce.editors, as suggested in https://github.com/tinymce/tinymce/issues/794#issuecomment-203701329
* fixes #2834

Note: this does not get rid of the exception NS_ERROR_UNEXPECTED thrown by Firefox. However it does re-create the tinyMCE editor when needed.

### CODE REVIEW

**Comment by mxstbr** [comment]
Awesome, thanks so much @geloescht!
Would you mind fixing the linting errors, then we can merge this:

```
/home/travis/build/keystonejs/keystone/fields/types/html/HtmlField.js
  22:16  error  Expected '===' and instead saw '=='  eqeqeq
  70:8   error  'instance' is already defined        no-redeclare
```

**Comment by geloescht** [comment]
Yup, I acted a little prematurely filing this PR. Should be much better now.

**Comment by mxstbr** [comment]
Awesome, looks good to me, thanks!

**Comment by JedWatson** [comment]
Thanks @geloescht!

**Pull request merged**
