### PR TITLE
initial cypress setup for @keystone-next/website

### PR DESCRIPTION
**Pull request by gwyneplaine**
As specified on the tin. 
Basic cypress setup for the @keystone-next/website package. 

I notice we're using 'execa' for managing cypress and server processes in other CI tests. 
Couldn't get this working properly with `next dev` so i've opted with the recommendation in the docs instead 

`start-server-and-test` found [here](https://github.com/bahmutov/start-server-and-test)

There's some boilerplate in here from running `cypress open` initially, haven't deleted them yet because it may be handy as a reference later when creating actual tests / adding necessary config.

### CODE REVIEW

**Comment by JedWatson** [comment]
The empty file for `docs-next/cypress/videos/examples/home.spec.js.mp4` is a bit weird, videos should be ignored right?

**Comment by JedWatson** [comment]
Also there's a failing cypress test:

```
docs-next/cypress/integration/examples/home.spec.js
```

I'm assuming that's not expected @gwyneplaine?

**Review by timleslie — CHANGES_REQUESTED** [review]
In the past we've found that the cypress tests are sufficiently different from our non-cypress unit tests that it's helpful to have them run as a separate group of things in CI.

Can you tweak the CI config so that these tests get run in the Cypress block, rather than under the generic `package unit tests`?

**Comment by gwyneplaine** [comment]
> In the past we've found that the cypress tests are sufficiently different from our non-cypress unit tests that it's helpful to have them run as a separate group of things in CI.
> 
> Can you tweak the CI config so that these tests get run in the Cypress block, rather than under the generic `package unit tests`?

Yeah this is what i've been working on this morning, realised this is why that one cypress test was failing

**Comment by gwyneplaine** [comment]
> Also there's a failing cypress test:
> 
> ```
> docs-next/cypress/integration/examples/home.spec.js
> ```
> 
> I'm assuming that's not expected @gwyneplaine?

Looks like this is from the bump from 6.x down from 5.6,

**Review by timleslie — APPROVED** [review]
This is great!

**Pull request merged**
