### PR TITLE
Fixed issue with RelationshipField auto complete feature

### PR DESCRIPTION
**Pull request by dijs**
## Description of changes

Fixed issue with RelationshipField auto complete feature
## Related issues (if any)

Auto complete was not forwarding the `q` params to the API
## Testing
- [ ] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by wmertens** [comment]
Wow would not have expected that to be the precedence… Good thing there is an eslint rule for that! Good to merge @JedWatson

**Comment by dijs** [comment]
Hmmm, the errors are not in the files I touched, that is odd.

**Comment by JedWatson** [comment]
This looks good, I saw #3226 and merged it first though. @dijs would you mind confirming that's equivalent?

**Comment by JedWatson** [comment]
@dijs did you get a chance to check that other solution was the same or if there is something in this PR we need? I'm trying to tie up loose ends as we prep for a beta release

**Comment by dijs** [comment]
I did not yet

**Comment by bassjacob** [comment]
Hi @dijs, thanks for this PR. We think https://github.com/keystonejs/keystone/pull/3226 has solved the issue, so we're going to solve this. Please let us know if this isn't the case.

**Pull request closed without merging**
