### PR TITLE
Swap `prepost` for `grappling-hook`

### PR DESCRIPTION
**Pull request by creynders**
With [`grappling-hook`](/keystonejs/grappling-hook) having its pre/post middleware registration rewritten, its fully keystone 0.3.x compatible. This is a replacement for #1239  and uses the new `grappling-hook` version.

Let's finally :shipit: 

I'll make a separate PR for adding a few oft requested hooks.

### CODE REVIEW

**Comment by dcousens** [comment]
Untested ACK from me.  Will test tomorrow. 
LGTM though.

**Comment by creynders** [comment]
@dcousens The (idea of the) last commit was cleared with @JedWatson BTW on slack. A bit too fragmented to paste here.

**Comment by creynders** [comment]
>We’ve got a bit of an ambiguous situation BTW: Currently in keystone `pre:routes` middleware is considered to be express middleware, however it is registered with our pre/post methods, so the question is: do we want to keep them as express middleware or are we going to regard them as grappling-hook middleware that happens to be used as express middleware?

>creynders [14:17]
Code-wise, both are trivial to setup with grappling-hook.

>creynders [14:18]
In concreto: ATM all `pre:routes` middleware is fed directly to `app.use`, i.e. they are all separate express middleware functions

>creynders [14:19]
while in the other case I’d set up a single express middleware function which calls `callHook(‘pre:routes’)`

>Benefit of going for grappling-hook middleware: it’ll allow all grappling-hook kind of middleware:
`function(req, res) //sync` `function(req, res, next) //async` `function(req, res, next, done) //async paralell` (edited)

>creynders [14:22]
And is obviously more consistent with the other hooks we are/will be providing

>creynders [14:23]
And it’s still express middleware compatible, i.e. people won’t know the difference

>jed [14:23] 
I like it

**Comment by JedWatson** [comment]
@creynders don't we want `grappling-hook` ^2.1.0 here?

Super uneasy about the lack of tests over those file field types. Let's fix that soon :persevere:

**Comment by creynders** [comment]
Ah, yes, nice catch @jedwatson

force pushing it in a sec

**Comment by dcousens** [comment]
Can we get this in a keystone branch so that we can work in this PR
together?

**Comment by creynders** [comment]
Sure... but why exactly @dcousens ? Wouldn't it better to land this and then have separate feature branches for adding more hooks?

**Comment by dcousens** [comment]
I was going to help put this under test.

**Comment by dcousens** [comment]
I'm happy to submit the PR to you,  just figured I'd ask.

**Comment by creynders** [comment]
@dcousens Ah no sorry, thought you had a different reason altogether. I'll close this one, and create a new PR from a keystonejs branch

**Comment by JedWatson** [comment]
I think it's fine to merge this and add tests in a separate PR. From my review, it looks good so I'm happy to have it in master. We've also got a stable build out there as of the weekend so it's a safe time to do that. We'll work through any issues that come up.

**Comment by creynders** [comment]
:rainbow: :penguin: :tulip:

**Pull request merged**
