### PR TITLE
Max character option added for password field

### PR DESCRIPTION
**Pull request by ostruzina**
## Description of changes

Adding the `max` character option for the `Password` field type.
Relevant tests added, checking to invalidate superlong password by default and validate superlong password when the option is set to false.
Documentation updated with the description of the new feature.

## Related issues (if any)

https://github.com/keystonejs/keystone/issues/136

## Testing

- [x] Please confirm `npm run test-all` ran successfully.

### CODE REVIEW

**Comment by mxstbr** [comment]
Do we need to validate that the `max` option is not smaller than the `min` option?

**Comment by JedWatson** [comment]
Relevant: https://www.google.com/search?q=bcrypt+max+length

**Comment by ostruzina** [comment]
We have changed the default value for `max` to 72, to align with bcrypt's maximum password length.

We have also added a check that the `max` value is higher than `min`, including related test.
Docs will be updated shortly.

**Comment by mxstbr** [comment]
LGTM, @JedWatson?

**Comment by JedWatson** [comment]
:+1:

We should add something to the docs explaining why we limit passwords to 72 characters by default - i.e. that bcrypt will discard input after that (with a link to the docs)

Otherwise it looks like we've picked an arbitrary limit and made it the default (and it's really not best practice to enforce limits on password complexity, but I think in this case it makes sense)

**Comment by ostruzina** [comment]
We have now added an explanation of the default `max` value to the docs, however, we are not entirely sure about which website is better to link to.

We used https://www.npmjs.com/package/bcrypt-nodejs, as that appears to be the homepage of the library used in Keystone.

Other than that, there is also the bcrypt creators' original paper:
https://www.usenix.org/legacy/events/usenix99/provos/provos_html/index.html
or wiki:
https://en.wikipedia.org/wiki/Bcrypt

The bcrypt-nodejs library's docs do not mention the 72 chars limitation though, and neither does the paper (which refers to the 56 bytes instead).

@mxstbr, @JedWatson: Do you have any other suggestion for a better resource to link to?

**Comment by JedWatson** [comment]
I think the google search I linked above would be a reasonable think to point people at

**Comment by ostruzina** [comment]
Ok then, I changed the bcrypt-nodejs npm page to the google search result page in the readme file.

**Comment by mxstbr** [comment]
Awesome, thanks so much! 🎉

**Pull request merged**
